import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Image } from "expo-image";
import { MaterialIcons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Colors, FontSize, FontWeight, Radius, Spacing } from "@/constants/theme";
import { fetchProducts, type Product } from "@/services/marketplaceService";
import { fetchMarketplaceStoreReputation, type MarketplaceStoreReputation } from "@/services/marketplaceReviewService";

export default function MarketplaceStoreScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(), router = useRouter(), insets = useSafeAreaInsets();
  const [store, setStore] = useState<MarketplaceStoreReputation | null>(null), [products, setProducts] = useState<Product[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(false);
  const load = useCallback(async () => {
    if (!id) return;
    setLoading(true); setError(false);
    try {
      const reputation = await fetchMarketplaceStoreReputation(id);
      const items = await fetchProducts({ sellerId: reputation.store.sellerId, limit: 30 });
      setStore(reputation); setProducts(items.filter((item) => item.store_id === id));
    } catch { setError(true); }
    finally { setLoading(false); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator color={Colors.primary} /><Text style={styles.muted}>Cargando tienda…</Text></View>;
  if (error || !store) return <View style={styles.center}><MaterialIcons name="storefront" size={40} color={Colors.textSubtle} /><Text style={styles.title}>No se pudo cargar la tienda</Text><Pressable style={styles.retry} onPress={() => void load()} accessibilityRole="button"><Text style={styles.retryText}>Reintentar</Text></Pressable></View>;
  return <View style={[styles.screen, { paddingTop: insets.top }]}>
    <View style={styles.header}><Pressable style={styles.iconButton} onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Volver"><MaterialIcons name="arrow-back" size={24} color={Colors.textPrimary} /></Pressable><Text style={styles.headerTitle} numberOfLines={1}>Tienda</Text></View>
    <FlatList data={products} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={styles.columns} contentContainerStyle={{ paddingBottom: insets.bottom + Spacing.xl }} ListHeaderComponent={<View><View style={styles.branding}>{store.store.bannerUrl ? <Image source={{ uri: store.store.bannerUrl }} style={styles.banner} contentFit="cover" /> : <View style={styles.bannerFallback} />}{store.store.logoUrl ? <Image source={{ uri: store.store.logoUrl }} style={styles.logo} contentFit="cover" /> : <View style={styles.logoFallback}><MaterialIcons name="storefront" size={34} color={Colors.primaryLight} /></View>}<Text style={styles.storeName}>{store.store.name}</Text>{store.store.description ? <Text style={styles.description}>{store.store.description}</Text> : null}{store.sellerAggregate.reviewCount > 0 && store.sellerAggregate.averageRating !== null ? <View style={styles.rating}><MaterialIcons name="star" size={17} color={Colors.warning} /><Text style={styles.ratingText}>{store.sellerAggregate.averageRating.toFixed(1)} · {store.sellerAggregate.reviewCount} {store.sellerAggregate.reviewCount === 1 ? "valoración" : "valoraciones"}</Text></View> : <Text style={styles.muted}>Sin valoraciones todavía</Text>}</View><Text style={styles.productsTitle}>Productos</Text></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="inventory-2" size={38} color={Colors.textSubtle} /><Text style={styles.muted}>Esta tienda no tiene productos disponibles.</Text></View>} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => router.push(`/product/${item.id}` as never)} accessibilityRole="button" accessibilityLabel={`Ver ${item.title}`}>{item.images[0] ? <Image source={{ uri: item.images[0] }} style={styles.productImage} contentFit="cover" /> : <View style={[styles.productImage, styles.missing]}><MaterialIcons name="image-not-supported" size={28} color={Colors.textSubtle} /><Text style={styles.missingText}>Imagen no disponible</Text></View>}<Text style={styles.productTitle} numberOfLines={2}>{item.title}</Text><Text style={styles.price}>{item.price.toFixed(2)} BDAG</Text></Pressable>} />
  </View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.bg }, center: { flex: 1, backgroundColor: Colors.bg, alignItems: "center", justifyContent: "center", gap: Spacing.sm, padding: Spacing.lg }, header: { minHeight: 56, flexDirection: "row", alignItems: "center", paddingHorizontal: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border }, iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, headerTitle: { color: Colors.textPrimary, fontSize: FontSize.lg, fontWeight: FontWeight.bold }, title: { color: Colors.textPrimary, fontSize: FontSize.lg, fontWeight: FontWeight.bold, textAlign: "center" }, muted: { color: Colors.textSecondary, textAlign: "center" }, retry: { minHeight: 44, paddingHorizontal: Spacing.lg, borderRadius: Radius.md, backgroundColor: Colors.primary, alignItems: "center", justifyContent: "center" }, retryText: { color: "#fff", fontWeight: FontWeight.bold }, branding: { alignItems: "center", paddingBottom: Spacing.lg }, banner: { width: "100%", height: 140 }, bannerFallback: { width: "100%", height: 80, backgroundColor: Colors.primaryDim }, logo: { width: 82, height: 82, borderRadius: Radius.xl, marginTop: -41, borderWidth: 3, borderColor: Colors.bg, backgroundColor: Colors.surface }, logoFallback: { width: 82, height: 82, borderRadius: Radius.xl, marginTop: -41, borderWidth: 3, borderColor: Colors.bg, backgroundColor: Colors.surface, alignItems: "center", justifyContent: "center" }, storeName: { color: Colors.textPrimary, fontSize: FontSize.xxl, fontWeight: FontWeight.bold, marginTop: Spacing.sm, textAlign: "center", paddingHorizontal: Spacing.md }, description: { color: Colors.textSecondary, textAlign: "center", lineHeight: 20, paddingHorizontal: Spacing.lg, marginTop: 5 }, rating: { flexDirection: "row", gap: 5, alignItems: "center", marginTop: Spacing.sm }, ratingText: { color: Colors.textSecondary, fontWeight: FontWeight.semibold }, productsTitle: { color: Colors.textPrimary, fontSize: FontSize.xl, fontWeight: FontWeight.bold, margin: Spacing.md }, columns: { gap: Spacing.sm, paddingHorizontal: Spacing.md }, card: { flex: 1, maxWidth: "50%", backgroundColor: Colors.surface, borderRadius: Radius.lg, padding: Spacing.sm, marginBottom: Spacing.sm, borderWidth: 1, borderColor: Colors.border }, productImage: { width: "100%", aspectRatio: 1, borderRadius: Radius.md, backgroundColor: Colors.surfaceElevated }, missing: { alignItems: "center", justifyContent: "center", gap: 5 }, missingText: { color: Colors.textSubtle, fontSize: 10, textAlign: "center" }, productTitle: { color: Colors.textPrimary, fontWeight: FontWeight.semibold, marginTop: Spacing.sm, lineHeight: 18 }, price: { color: Colors.primaryLight, fontWeight: FontWeight.bold, marginTop: 5 }, empty: { alignItems: "center", gap: Spacing.sm, padding: Spacing.xl },
});
