import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {dismissAdminReport,formatDate,getAdminReportDetail,reviewAdminReport,searchAdminReports,type AdminReportDetail,type AdminReportSummary} from "../lib/adminApi";

export function AdminReportsPage(){const [status,setStatus]=useState(""),[contentType,setContentType]=useState(""),[items,setItems]=useState<AdminReportSummary[]|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setItems(null);setError(null);void searchAdminReports({status,contentType}).then((page)=>{if(active)setItems(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[status,contentType,nonce]);return <><div className="page-heading"><div><p className="eyebrow">TRUST &amp; SAFETY</p><h2>Reportes</h2><p>Casos enviados por usuarios; sin borrado de contenido en A4.</p></div></div><div className="filters"><select aria-label="Estado" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendientes</option><option value="reviewed">Revisados</option><option value="dismissed">Descartados</option></select><select aria-label="Tipo" value={contentType} onChange={(e)=>setContentType(e.target.value)}><option value="">Todos los tipos</option><option value="video">Video</option><option value="comment">Comentario</option><option value="user">Usuario</option></select></div>{error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!items?<LoadingState label="Buscando reportes…"/>:items.length===0?<EmptyState title="Sin reportes" detail="No hay casos para estos filtros."/>:<section className="table-panel"><div className="orders-table" role="table"><div className="table-head" role="row"><span>Reporte</span><span>Reportante</span><span>Tipo</span><span>Motivo</span><span>Estado</span><span>Creado</span></div>{items.map((report)=><Link className="table-row" role="row" to={`/reports/${report.id}`} key={report.id}><span><strong>{report.id}</strong></span><span>{report.reporter.display_name??report.reporter.username??report.reporter.id}</span><span>{report.reported_content_type}</span><span>{report.reason}</span><span><em className="badge">{report.status}</em></span><span>{formatDate(report.created_at)}</span></Link>)}</div></section>}</>}

export function AdminReportDetailPage(){const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [report,setReport]=useState<AdminReportDetail|null>(null),[note,setNote]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setReport(null);setError(null);void getAdminReportDetail(id).then((value)=>{if(active)setReport(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[id,nonce]);const run=async(action:"review"|"dismiss")=>{if(note.trim().length<2)return setError("Indica una nota de al menos 2 caracteres.");setBusy(true);setError(null);try{if(action==="review")await reviewAdminReport({id,note:note.trim(),idempotencyKey:crypto.randomUUID()});else await dismissAdminReport({id,reason:note.trim(),idempotencyKey:crypto.randomUUID()});setNote("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar el reporte")}finally{setBusy(false)}};if(error&&!report)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;if(!report)return <LoadingState label="Cargando reporte…"/>;return <><div className="page-heading"><div><p className="eyebrow">REPORTE</p><h2>{report.reason}</h2><p>{report.id}</p></div><em className="badge">{report.status}</em></div><section className="detail-grid"><article className="detail-card"><h3>Caso</h3><dl><dt>Tipo</dt><dd>{report.reported_content_type}</dd><dt>Creado</dt><dd>{formatDate(report.created_at)}</dd><dt>Reportante</dt><dd>{report.reporter.display_name??report.reporter.username??report.reporter.id}</dd></dl><p>{report.details??"Sin detalle adicional"}</p></article><article className="detail-card"><h3>Contexto acotado</h3><pre>{JSON.stringify(report.subject,null,2)}</pre></article></section>{report.status!=="dismissed"&&<section className="detail-card"><h3>Resolver caso</h3><textarea aria-label="Nota administrativa" placeholder="Nota o motivo obligatorio" value={note} onChange={(e)=>setNote(e.target.value)}/><div className="button-row">{report.status==="pending"&&hasCapability("reports.cases.review")&&<button disabled={busy} onClick={()=>void run("review")}>Marcar revisado</button>}{hasCapability("reports.cases.resolve")&&<button className="secondary" disabled={busy} onClick={()=>void run("dismiss")}>Descartar</button>}</div>{error&&<p role="alert">{error}</p>}</section>}</>}
