import {useEffect,useState} from "react";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {AdminIdentity,shortId} from "../components/AdminPresentation";
import {ErrorState,LoadingState} from "../components/PageState";
import {assignAdminRole,getAdminRoleCatalog,revokeAdminRole,searchAdminRoleAssignments,searchAdminUsers,type AdminRole,type AdminRoleAssignment,type AdminUserSummary} from "../lib/adminApi";

export function AdminAccessPage(){
  const {hasCapability}=useAdminAuth();
  const [roles,setRoles]=useState<AdminRole[]|null>(null),[assignments,setAssignments]=useState<AdminRoleAssignment[]|null>(null),[selectedUser,setSelectedUser]=useState<AdminUserSummary|null>(null),[userQuery,setUserQuery]=useState(""),[userResults,setUserResults]=useState<AdminUserSummary[]>([]),[searching,setSearching]=useState(false),[roleCode,setRoleCode]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setError(null);void Promise.all([getAdminRoleCatalog(),searchAdminRoleAssignments({active:true})]).then(([nextRoles,page])=>{if(active){setRoles(nextRoles);setAssignments(page.items)}}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[nonce]);
  useEffect(()=>{if(selectedUser||userQuery.trim().length<2){setUserResults([]);return}let active=true;const timer=window.setTimeout(()=>{setSearching(true);void searchAdminUsers({query:userQuery.trim(),limit:8}).then((page)=>{if(active)setUserResults(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"No se pudo buscar usuarios")}).finally(()=>{if(active)setSearching(false)})},250);return()=>{active=false;window.clearTimeout(timer)}},[userQuery,selectedUser]);
  if(error&&!roles)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;
  if(!roles||!assignments)return <LoadingState label="Cargando acceso…"/>;
  const assign=async()=>{if(!selectedUser)return;try{await assignAdminRole({userId:selectedUser.id,roleCode,reason,idempotencyKey:crypto.randomUUID()});setSelectedUser(null);setUserQuery("");setReason("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo asignar")}};
  const revoke=async(id:string)=>{const why=window.prompt("Motivo de revocación");if(!why)return;try{await revokeAdminRole({assignmentId:id,reason:why,idempotencyKey:crypto.randomUUID()});setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo revocar")}};
  const assignable=roles.filter((role)=>role.is_assignable&&!role.is_root);
  return <><div className="page-heading"><div><p className="eyebrow">AUTORIDAD</p><h2>Acceso administrativo</h2><p>Roles ordinarios del sistema canónico. El rol root no es asignable aquí.</p></div></div><section className="detail-grid">{roles.map((role)=><article className="detail-card" key={role.role_code}><h3>{role.display_name}</h3><p>{role.description}</p><small>{role.capability_count} capabilities · {role.is_root?"root / no asignable":role.is_exclusive?"exclusivo":"combinable"}</small></article>)}</section>{hasCapability("admin.roles.assign")&&<section className="detail-card"><h3>Asignar rol ordinario</h3><div className="user-picker"><label htmlFor="admin-user-search">Usuario</label>{selectedUser?<div className="selected-user"><AdminIdentity value={selectedUser}/><button className="secondary" type="button" onClick={()=>setSelectedUser(null)}>Cambiar</button></div>:<><input id="admin-user-search" aria-autocomplete="list" aria-controls="admin-user-results" autoComplete="off" placeholder="Buscar por nombre, usuario o UUID" value={userQuery} onChange={(e)=>setUserQuery(e.target.value)}/>{searching&&<small>Buscando…</small>}<div className="user-picker-results" id="admin-user-results" role="listbox">{userResults.map((user)=><button key={user.id} role="option" type="button" onClick={()=>{setSelectedUser(user);setUserQuery("");setUserResults([])}}><AdminIdentity value={user} compact/><code>{shortId(user.id)}</code></button>)}</div></>}</div><div className="filters"><select aria-label="Rol" value={roleCode} onChange={(e)=>setRoleCode(e.target.value)}><option value="">Selecciona rol</option>{assignable.map((role)=><option key={role.role_code} value={role.role_code}>{role.display_name}</option>)}</select><input aria-label="Motivo" placeholder="Motivo" value={reason} onChange={(e)=>setReason(e.target.value)}/><button disabled={!selectedUser||!roleCode||reason.trim().length<2} onClick={()=>void assign()}>Asignar</button></div></section>}<section className="table-panel"><div className="orders-table" role="table"><div className="table-head" role="row"><span>Usuario</span><span>Rol</span><span>Origen</span><span>Asignado</span><span>Versión</span><span>Acción</span></div>{assignments.map((assignment)=><div className="table-row" role="row" key={assignment.assignment_id}><span><AdminIdentity value={assignment.user} compact/></span><span>{assignment.role_code}</span><span>{assignment.grant_actor_kind}</span><span>{new Date(assignment.granted_at).toLocaleString()}</span><span>{assignment.version}</span><span>{hasCapability("admin.roles.revoke")&&assignment.role_code!=="SUPER_ADMIN"?<button className="secondary" onClick={()=>void revoke(assignment.assignment_id)}>Revocar</button>:"—"}</span></div>)}</div></section>{error&&<p role="alert">{error}</p>}</>}
