import {useEffect,useState,type FormEvent} from "react";
import {Link,useParams} from "react-router-dom";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {formatDate,getAdminUserDetail,issueAdminUserWarning,moderateAdminUser,revokeAdminUserWarning,searchAdminUsers,type AdminUserDetail,type AdminUserSummary,type AdminUserWarning} from "../lib/adminApi";
import {useAdminAuth} from "../auth/AdminAuthProvider";

const accountLabel=(status:"active"|"suspended")=>status==="suspended"?"Suspendida":"Activa";
const warningTone=(count:number)=>count>0?"warn":"";
const actorName=(warning:AdminUserWarning)=>warning.issued_by.display_name??warning.issued_by.username??warning.issued_by.id;

export function AdminUsersPage(){
  const [query,setQuery]=useState(""),[status,setStatus]=useState(""),[items,setItems]=useState<AdminUserSummary[]|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setItems(null);setError(null);void searchAdminUsers({query,status,limit:50}).then((page)=>{if(active)setItems(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[query,status,nonce]);
  const submit=(event:FormEvent)=>event.preventDefault();
  return <><div className="page-heading"><div><p className="eyebrow">PLATAFORMA</p><h2>Usuarios</h2><p>Identidad pública, estado de cuenta y disciplina administrativa.</p></div></div><form className="filters" onSubmit={submit}><label className="search"><span>⌕</span><input aria-label="Buscar usuarios" placeholder="UUID, username o nombre" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select aria-label="Estado de cuenta" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option><option value="active">Activos</option><option value="suspended">Suspendidos</option></select></form>{error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!items?<LoadingState label="Buscando usuarios…"/>:items.length===0?<EmptyState title="Sin usuarios" detail="No hay coincidencias para estos filtros."/>:<section className="table-panel"><div className="orders-table admin-users-table" role="table"><div className="table-head" role="row"><span>Usuario</span><span>Username</span><span>Creación</span><span>Último acceso</span><span>Advertencias</span><span>Estado</span><span>ID</span></div>{items.map((user)=><Link className="table-row" role="row" to={`/users/${user.id}`} key={user.id}><span><strong>{user.display_name??"Sin nombre"}</strong></span><span>{user.username??"—"}</span><span>{formatDate(user.created_at)}</span><span>{formatDate(user.last_sign_in_at)}</span><span><em className={`badge ${warningTone(user.active_warning_count)}`}>{user.active_warning_count}/3</em></span><span><em className={`badge ${user.account_status==="suspended"?"warn":"success"}`}>{accountLabel(user.account_status)}</em></span><span><small>{user.id}</small></span></Link>)}</div></section>}</>;
}

export function AdminUserDetailPage(){
  const {id=""}=useParams(),{hasCapability}=useAdminAuth();
  const [user,setUser]=useState<AdminUserDetail|null>(null),[error,setError]=useState<string|null>(null),[moderationReason,setModerationReason]=useState(""),[warningReason,setWarningReason]=useState(""),[internalNote,setInternalNote]=useState(""),[evidenceType,setEvidenceType]=useState(""),[evidenceId,setEvidenceId]=useState(""),[evidenceNote,setEvidenceNote]=useState(""),[revokeReasons,setRevokeReasons]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setUser(null);setError(null);void getAdminUserDetail(id).then((value)=>{if(active)setUser(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[id,nonce]);
  const runModeration=async(action:"suspend"|"restore")=>{if(moderationReason.trim().length<2)return setError("Indica un motivo de al menos 2 caracteres.");setBusy(true);setError(null);try{await moderateAdminUser({targetUserId:id,action,reason:moderationReason.trim(),idempotencyKey:crypto.randomUUID()});setModerationReason("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo completar la acción")}finally{setBusy(false)}};
  const issueWarning=async()=>{if(!user||warningReason.trim().length<2)return setError("Indica un motivo visible de al menos 2 caracteres.");const next=user.discipline.active_warning_count+1;if(next>3)return setError("El ciclo actual ya alcanzó el límite de 3 advertencias.");if(next===3&&!window.confirm("Esta es la tercera advertencia. La cuenta será suspendida automáticamente."))return;setBusy(true);setError(null);try{await issueAdminUserWarning({targetUserId:id,reason:warningReason.trim(),internalNote:internalNote.trim()||undefined,evidenceType:evidenceType||undefined,evidenceId:evidenceId.trim()||undefined,evidenceNote:evidenceNote.trim()||undefined,idempotencyKey:crypto.randomUUID()});setWarningReason("");setInternalNote("");setEvidenceType("");setEvidenceId("");setEvidenceNote("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo emitir la advertencia")}finally{setBusy(false)}};
  const revokeWarning=async(warning:AdminUserWarning)=>{const reason=(revokeReasons[warning.id]??"").trim();if(reason.length<2)return setError("Indica un motivo de revocación de al menos 2 caracteres.");if(!window.confirm("La advertencia quedará revocada en el historial. La cuenta no se restaurará automáticamente."))return;setBusy(true);setError(null);try{await revokeAdminUserWarning({warningId:warning.id,reason,idempotencyKey:crypto.randomUUID()});setRevokeReasons((current)=>({...current,[warning.id]:""}));setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo revocar la advertencia")}finally{setBusy(false)}};
  if(error&&!user)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;
  if(!user)return <LoadingState label="Cargando usuario…"/>;
  const canModerate=hasCapability("users.accounts.moderate"),canSuspend=hasCapability("users.accounts.suspend")&&user.account_status==="active",canRestore=hasCapability("users.accounts.restore")&&user.account_status==="suspended",nextWarning=user.discipline.active_warning_count+1,thirdWithoutSuspend=nextWarning===3&&!hasCapability("users.accounts.suspend");
  return <><div className="page-heading"><div><p className="eyebrow">USUARIO</p><h2>{user.display_name??user.username??user.id}</h2><p>{user.id}</p></div><em className={`badge ${user.account_status==="suspended"?"warn":"success"}`}>{accountLabel(user.account_status)}</em></div>
    <section className="detail-grid"><article className="detail-card"><h3>Cuenta</h3><dl><dt>Username</dt><dd>{user.username??"—"}</dd><dt>Creada</dt><dd>{formatDate(user.created_at)}</dd><dt>Último acceso</dt><dd>{formatDate(user.last_sign_in_at)}</dd><dt>Suspensión hasta</dt><dd>{formatDate(user.banned_until)}</dd></dl></article><article className="detail-card"><h3>Perfil público</h3><p>{user.bio??"Sin biografía"}</p><dl><dt>Seguidores</dt><dd>{user.public_counters.followers_count}</dd><dt>Siguiendo</dt><dd>{user.public_counters.following_count}</dd></dl></article>{user.active_admin_roles!==null&&<article className="detail-card"><h3>Roles administrativos activos</h3>{user.active_admin_roles.length?user.active_admin_roles.map((role)=><p key={role.assignment_id}><strong>{role.role_code}</strong> · v{role.version}</p>):<p>Ninguno</p>}</article>}</section>
    <section className="detail-card discipline-card"><div className="discipline-heading"><div><p className="eyebrow">DISCIPLINA</p><h3>Advertencias del ciclo actual</h3></div><strong className={`discipline-count level-${Math.min(user.discipline.active_warning_count,3)}`}>{user.discipline.active_warning_count} / 3</strong></div><div className="admin-stat-grid"><div className="admin-stat"><span>Estado disciplinario</span><strong>{user.discipline.enforcement_required?"Suspensión requiere atención":user.discipline.active_warning_count===0?"Sin advertencias":user.discipline.active_warning_count===1?"Advertido":user.discipline.active_warning_count===2?"Advertencia final":user.account_status==="suspended"?"Suspendido":"Umbral alcanzado"}</strong></div><div className="admin-stat"><span>Histórico</span><strong>{user.discipline.historical_warning_count}</strong></div><div className="admin-stat"><span>Inicio del ciclo</span><strong>{formatDate(user.discipline.cycle_started_at)}</strong></div><div className="admin-stat"><span>Última suspensión</span><strong>{formatDate(user.discipline.last_suspension?.completed_at)}</strong></div><div className="admin-stat"><span>Última restauración</span><strong>{formatDate(user.discipline.last_restore?.completed_at)}</strong></div></div>{user.discipline.enforcement_required&&<p className="discipline-attention" role="alert">3 / 3 — La suspensión automática no quedó confirmada. Usa la acción canónica “Suspender cuenta”.</p>}</section>
    {canModerate&&nextWarning<=3&&<section className="detail-card warning-form"><h3>Emitir advertencia</h3><label>Motivo para el usuario<textarea aria-label="Motivo para el usuario" placeholder="Obligatorio (2–500 caracteres)" value={warningReason} onChange={(e)=>setWarningReason(e.target.value)} maxLength={500}/></label><label>Nota interna<textarea aria-label="Nota interna" placeholder="Opcional; nunca se incluye en la notificación" value={internalNote} onChange={(e)=>setInternalNote(e.target.value)} maxLength={1000}/></label><div className="warning-evidence-grid"><label>Tipo de evidencia<select aria-label="Tipo de evidencia" value={evidenceType} onChange={(e)=>setEvidenceType(e.target.value)}><option value="">Sin evidencia</option>{["video","story","comment","message","live","battle","report","marketplace","other"].map((type)=><option key={type} value={type}>{type}</option>)}</select></label><label>ID de evidencia<input aria-label="ID de evidencia" placeholder="UUID opcional" value={evidenceId} onChange={(e)=>setEvidenceId(e.target.value)} disabled={!evidenceType}/></label></div><label>Nota de evidencia<textarea aria-label="Nota de evidencia" placeholder="Opcional" value={evidenceNote} onChange={(e)=>setEvidenceNote(e.target.value)} maxLength={1000} disabled={!evidenceType}/></label><button disabled={busy||warningReason.trim().length<2||thirdWithoutSuspend} onClick={()=>void issueWarning()}>{nextWarning===3?"Emitir advertencia 3/3 y suspender":`Emitir advertencia ${nextWarning}/3`}</button>{thirdWithoutSuspend&&<small>La tercera advertencia requiere también la capability users.accounts.suspend.</small>}</section>}
    <section className="detail-card"><h3>Historial disciplinario</h3>{user.discipline.warnings.length===0&&!user.discipline.last_suspension&&!user.discipline.last_restore?<p className="muted-text">Sin eventos disciplinarios.</p>:<div className="admin-timeline discipline-timeline">{user.discipline.warnings.map((warning)=><div key={warning.id}><i/><div><strong>Advertencia {warning.warning_level_at_issue}/3 · {warning.status==="revoked"?"Revocada":"Activa"}</strong><span>{warning.reason}</span><small>Emitida por {actorName(warning)} · {formatDate(warning.issued_at)}</small>{warning.internal_note&&<small>Nota interna: {warning.internal_note}</small>}{warning.evidence_type&&<small>Evidencia: {warning.evidence_type}{warning.evidence_id?` · ${warning.evidence_id}`:""}{warning.evidence_note?` · ${warning.evidence_note}`:""}</small>}{warning.status==="revoked"&&<small>Revocada por {warning.revoked_by?.display_name??warning.revoked_by?.username??warning.revoked_by?.id??"—"} · {formatDate(warning.revoked_at)} · {warning.revocation_reason}</small>}{canModerate&&warning.status==="active"&&<div className="revoke-warning"><input aria-label={`Motivo para revocar advertencia ${warning.warning_level_at_issue}/3`} placeholder="Motivo de revocación" value={revokeReasons[warning.id]??""} onChange={(e)=>setRevokeReasons((current)=>({...current,[warning.id]:e.target.value}))}/><button className="secondary" disabled={busy} onClick={()=>void revokeWarning(warning)}>Revocar advertencia</button></div>}</div><time>{formatDate(warning.issued_at)}</time></div>)}{user.discipline.last_suspension&&<div><i/><div><strong>Suspensión de cuenta</strong><span>{user.discipline.last_suspension.reason}</span><small>Estado: {user.discipline.last_suspension.status}</small></div><time>{formatDate(user.discipline.last_suspension.completed_at??user.discipline.last_suspension.requested_at)}</time></div>}{user.discipline.last_restore&&<div><i/><div><strong>Restauración de cuenta</strong><span>{user.discipline.last_restore.reason}</span><small>Inicia un nuevo ciclo disciplinario.</small></div><time>{formatDate(user.discipline.last_restore.completed_at??user.discipline.last_restore.requested_at)}</time></div>}</div>}</section>
    {(canSuspend||canRestore)&&<section className="detail-card"><h3>Moderación de cuenta</h3><textarea aria-label="Motivo de moderación" placeholder="Motivo obligatorio" value={moderationReason} onChange={(e)=>setModerationReason(e.target.value)}/><div className="button-row">{canSuspend&&<button disabled={busy} onClick={()=>void runModeration("suspend")}>Suspender cuenta</button>}{canRestore&&<button disabled={busy} onClick={()=>void runModeration("restore")}>Restaurar cuenta</button>}</div><small>La restauración inicia un ciclo disciplinario nuevo; el historial anterior se conserva.</small></section>}
    {error&&<p className="discipline-attention" role="alert">{error}</p>}
  </>;
}
