import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {AdminFact,AdminFactGrid,AdminIdentity,AdminStatusPanel,asRecord,asRows,humanValue,shortId} from "../components/AdminPresentation";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {formatDate} from "../lib/adminApi";
import {approveAdminContentSafetyRule,createAdminContentSafetyRule,getAdminContentSafetyAlert,getAdminContentSafetyAudioDetail,previewAdminContentSafetyRule,previewAdminContentSafetyRuleDraft,retireAdminContentSafetyRule,retryAdminContentSafetyAudio,retryAdminContentSafetyScan,reviewAdminContentSafetyAlert,searchAdminContentSafetyAlerts,searchAdminContentSafetyAudio,searchAdminContentSafetyRules,setAdminContentSafetyRuleEnabled,updateAdminContentSafetyRule} from "../lib/adminSafetyApi";

const severityLabel=(value:unknown)=>value==="critical"?"Crítica":value==="high"?"Alta":value==="medium"?"Media":"Baja";
const statusLabel=(value:unknown)=>value==="open"?"Abierta":value==="in_review"?"En revisión":value==="dismissed"?"Sin infracción":value==="resolved"?"Resuelta":humanValue(value);
const coverageLabel=(value:unknown)=>value==="analyzed"?"Analizado":value==="pending"?"Pendiente":value==="failed"?"Falló":value==="not_configured"?"No configurado":"No aplica";
const coverageTone=(value:unknown):"neutral"|"success"|"warning"|"danger"=>value==="analyzed"?"success":value==="failed"?"danger":value==="pending"?"warning":"neutral";
const targetLabel=(value:unknown)=>value==="video"?"Video":value==="comment"?"Comentario":value==="story"?"Story":value==="live_message"?"Chat LIVE":"Mensaje reportado";
const scopes=["video_caption","comment","story_text","live_chat","reported_message","transcript"];
const categories=["violence","threat","harassment","hate","sexual","self_harm","drugs","weapons","fraud","spam","child_safety","other"];

export function AdminContentSafetyPage(){
  const [severity,setSeverity]=useState(""),[status,setStatus]=useState("open"),[category,setCategory]=useState(""),[target,setTarget]=useState(""),[source,setSource]=useState(""),[coverage,setCoverage]=useState(""),[data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError(null);void searchAdminContentSafetyAlerts({p_severity:severity||null,p_status:status||null,p_category:category||null,p_target_type:target||null,p_source_type:source||null,p_coverage:coverage||null,p_limit:50}).then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar Content Safety")});return()=>{active=false}},[severity,status,category,target,source,coverage,nonce]);
  if(error)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;
  if(!data)return <LoadingState label="Cargando cola de Content Safety…"/>;
  const items=asRows(data.items),stats=asRecord(data.stats),activeRules=Number(data.active_rule_count)||0;
  return <><div className="page-heading"><div><p className="eyebrow">TRUST &amp; SAFETY</p><h2>Content Safety</h2><p>Detección automática para priorizar revisión humana. Una alerta no es una sanción.</p></div><div className="button-row"><Link className="secondary button-link" to="/content-safety/audio">Audio AI</Link><Link className="secondary button-link" to="/content-safety/rules">Gestionar reglas</Link></div></div>
    {activeRules===0&&<AdminStatusPanel title="Motor textual listo · 0 reglas activas" detail="No se inventaron palabras prohibidas. Configura reglas derivadas de la política de Nelyon para comenzar a detectar coincidencias." tone="warning"/>}
    <section className="safety-stat-grid" aria-label="Resumen de alertas">{[{label:"Críticas",value:stats.critical_count},{label:"Altas",value:stats.high_count},{label:"Medias",value:stats.medium_count},{label:"Bajas",value:stats.low_count},{label:"Abiertas",value:stats.open_count},{label:"En revisión",value:stats.in_review_count}].map((item)=><article key={item.label}><span>{item.label}</span><strong>{humanValue(item.value,"0")}</strong></article>)}</section>
    <div className="filters"><select aria-label="Severidad" value={severity} onChange={(event)=>setSeverity(event.target.value)}><option value="">Toda severidad</option><option value="critical">Crítica</option><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></select><select aria-label="Estado de alerta" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">Todos los estados</option><option value="open">Abiertas</option><option value="in_review">En revisión</option><option value="resolved">Resueltas</option><option value="dismissed">Sin infracción</option></select><select aria-label="Categoría" value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">Toda categoría</option>{categories.map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Tipo de contenido" value={target} onChange={(event)=>setTarget(event.target.value)}><option value="">Todo contenido</option><option value="video">Video</option><option value="comment">Comentario</option><option value="story">Story</option><option value="live_message">Chat LIVE</option><option value="message">Mensaje reportado</option></select><select aria-label="Fuente" value={source} onChange={(event)=>setSource(event.target.value)}><option value="">Toda fuente</option><option value="text_rule">Regla textual</option><option value="user_reports">Reportes</option></select><select aria-label="Cobertura" value={coverage} onChange={(event)=>setCoverage(event.target.value)}><option value="">Toda cobertura</option><option value="complete">Completa</option><option value="incomplete">Incompleta</option><option value="pending">Pendiente</option><option value="failed">Fallida</option></select></div>
    {items.length===0?<EmptyState title="Sin alertas" detail={activeRules===0?"No hay reglas activas ni reportes que generen alertas.":"No hay coincidencias para estos filtros."}/>:<section className="table-panel"><table className="human-table safety-alert-table"><thead><tr><th>Prioridad</th><th>Contenido</th><th>Autor</th><th>Señal</th><th>Impacto</th><th>Cobertura</th><th>Estado</th></tr></thead><tbody>{items.map((item)=>{const coverageValue=asRecord(item.coverage);return <tr key={String(item.id)}><td><Link to={`/content-safety/${String(item.id)}`}><strong>{severityLabel(item.priority_bucket)} · {humanValue(item.priority_score)}</strong><small>{severityLabel(item.severity)} · {humanValue(item.category)}</small></Link></td><td><Link to={`/content-safety/${String(item.id)}`}><strong>{targetLabel(item.target_type)}</strong><span className="truncate">{humanValue(item.evidence_excerpt,"Sin extracto textual")}</span><small className="mono">{shortId(item.target_id)}</small></Link></td><td><AdminIdentity value={asRecord(item.author)} compact/></td><td>{humanValue(item.rule_label,item.source_type==="user_reports"?"Reportes de usuarios":item.source_type==="audio_transcript_rule"?"Speech-to-Text AI":"Detector textual")}</td><td><small>{humanValue(item.related_report_count,"0")} reportes · {humanValue(item.reach,"0")} alcance<br/>Warnings {humanValue(item.active_warning_count,"0")}/3</small></td><td><small>Texto {coverageLabel(coverageValue.text)}<br/>Audio {coverageLabel(coverageValue.audio)} · Visual {coverageLabel(coverageValue.visual)}</small></td><td><em className={`badge ${item.status==="open"?"warn":item.status==="resolved"?"success":""}`}>{statusLabel(item.status)}</em><small className="table-secondary">{formatDate(item.created_at)}</small></td></tr>})}</tbody></table></section>}
  </>;
}

export function AdminContentSafetyDetailPage(){
  const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [detail,setDetail]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[note,setNote]=useState(""),[resolution,setResolution]=useState("reviewed"),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setDetail(null);setError(null);void getAdminContentSafetyAlert(id).then((value)=>{if(active)setDetail(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar la alerta")});return()=>{active=false}},[id,nonce]);
  const act=async(action:"take_review"|"dismiss"|"resolve")=>{if(action!=="take_review"&&note.trim().length<2)return setError("Indica una nota de al menos 2 caracteres.");setBusy(true);setError(null);try{await reviewAdminContentSafetyAlert({id,action,resolution:action==="resolve"?resolution:null,note:note.trim()||null,idempotencyKey:crypto.randomUUID()});setNote("");setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo revisar la alerta")}finally{setBusy(false)}};
  const retry=async()=>{const scan=asRecord(detail?.scan);setBusy(true);setError(null);try{await retryAdminContentSafetyScan({id:String(scan.id),idempotencyKey:crypto.randomUUID()});setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo reintentar el scan")}finally{setBusy(false)}};
  if(error&&!detail)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!detail)return <LoadingState label="Cargando alerta…"/>;
  const author=asRecord(detail.author),scan=asRecord(detail.scan),coverage=asRecord(scan.coverage),content=asRecord(detail.content),rule=asRecord(detail.rule),evidence=asRecord(detail.evidence),relatedReports=asRows(detail.related_reports),incomplete=[coverage.audio,coverage.visual].includes("not_configured");
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY · {severityLabel(detail.priority_bucket).toUpperCase()}</p><h2>{targetLabel(detail.target_type)} · {humanValue(detail.category)}</h2><p className="mono">{id}</p></div><div className="button-row"><em className={`badge ${detail.severity==="critical"||detail.severity==="high"?"warn":""}`}>{severityLabel(detail.severity)}</em><em className="badge">{statusLabel(detail.status)}</em></div></div>
    <div className="presentation-grid"><div className="presentation-stack"><section className="presentation-card"><header><h3>Contenido y evidencia</h3></header><p>{humanValue(content.summary,"Sin extracto disponible")}</p><AdminFactGrid><AdminFact label="Tipo" value={targetLabel(detail.target_type)}/><AdminFact label="Prioridad" value={`${humanValue(detail.priority_score)}/100`}/><AdminFact label="Detector" value={humanValue(rule.label,detail.source_type==="user_reports"?"Reportes de usuarios":detail.source_type==="audio_transcript_rule"?"Speech-to-Text AI":"Coincidencia automática")}/><AdminFact label="Versión detector" value={humanValue(scan.detector_version)}/><AdminFact label="Regla" value={humanValue(rule.code,"—")} mono/><AdminFact label="Versión de regla" value={humanValue(evidence.rule_version,humanValue(rule.version))}/><AdminFact label="Política" value={humanValue(evidence.policy_source)}/><AdminFact label="Referencia" value={humanValue(evidence.policy_reference)} mono/><AdminFact label="Locale" value={humanValue(evidence.locale)}/><AdminFact label="Confidence" value={detail.confidence===null||detail.confidence===undefined?"No disponible":humanValue(detail.confidence)}/>{detail.source_type==="audio_transcript_rule"&&<><AdminFact label="Proveedor" value={humanValue(evidence.provider)}/><AdminFact label="Modelo" value={humanValue(evidence.model)} mono/><AdminFact label="Timecode" value={evidence.timecode_start===null||evidence.timecode_start===undefined?"No disponible":`${humanValue(evidence.timecode_start)}s – ${humanValue(evidence.timecode_end)}s`}/></>}</AdminFactGrid>{detail.source_type==="audio_transcript_rule"&&<AdminStatusPanel title="Coincidencia en transcripción AI" detail={humanValue(evidence.matched_transcript_excerpt,"Extracto no disponible")} tone="warning"/>}{Array.isArray(evidence.matched_terms)&&<div className="safety-term-list">{evidence.matched_terms.map((term)=><em className="badge" key={String(term)}>{String(term)}</em>)}</div>}<p className="muted-text">Una coincidencia de IA requiere revisión humana; no confirma una infracción ni aplica sanciones.</p><div className="button-row"><Link className="button-link" to={String(content.path||"/content")}>Abrir contenido canónico</Link>{detail.target_type==="story"&&<Link className="secondary button-link" to={`/stories/${String(detail.target_id)}`}>Abrir Story</Link>}</div></section>
      <section className="presentation-card"><header><h3>Analysis coverage</h3></header><div className="status-list"><AdminStatusPanel title="Texto" detail={coverageLabel(coverage.text)} tone={coverageTone(coverage.text)}/><AdminStatusPanel title="Audio" detail={coverageLabel(coverage.audio)} tone={coverageTone(coverage.audio)}/><AdminStatusPanel title="Visual" detail={coverageLabel(coverage.visual)} tone={coverageTone(coverage.visual)}/><AdminStatusPanel title="Reportes" detail={coverageLabel(coverage.reports)} tone={coverageTone(coverage.reports)}/></div>{incomplete&&<p className="discipline-attention">El análisis automático no cubrió audio/visual. Esta alerta no certifica que el contenido sea seguro.</p>}</section>
      <section className="presentation-card"><header><h3>Reportes relacionados</h3><em className="badge">{relatedReports.length}</em></header>{relatedReports.length===0?<p className="muted-text">Sin reportes asociados.</p>:<div className="status-list">{relatedReports.map((report)=><AdminStatusPanel key={String(report.id)} title={humanValue(report.reason,"Reporte")} detail={`${statusLabel(report.status)} · ${formatDate(report.created_at)}`} tone={report.status==="pending"?"warning":"neutral"}/>)}</div>}<Link className="secondary button-link" to="/reports">Abrir Reports</Link></section></div>
      <aside className="presentation-stack"><section className="presentation-card"><header><h3>Autor</h3></header><AdminIdentity value={author}/><AdminFactGrid><AdminFact label="Warnings actuales" value={`${humanValue(detail.active_warning_count,"0")}/3`}/><AdminFact label="Alcance" value={humanValue(detail.reach,"0")}/><AdminFact label="Reportes pendientes" value={humanValue(detail.pending_report_count,"0")}/><AdminFact label="Reportes 15 min" value={humanValue(detail.reports_last_15m,"0")}/></AdminFactGrid>{typeof author.id==="string"&&<Link className="secondary button-link" to={`/users/${author.id}`}>Abrir usuario / disciplina F2</Link>}</section><section className="presentation-card"><header><h3>Scan</h3></header><AdminFactGrid><AdminFact label="Estado" value={humanValue(scan.status)}/><AdminFact label="Motivo" value={humanValue(scan.requested_reason)}/><AdminFact label="Intentos" value={humanValue(scan.attempt_count)}/><AdminFact label="Iniciado" value={formatDate(scan.started_at)}/><AdminFact label="Completado" value={formatDate(scan.completed_at)}/><AdminFact label="Error" value={humanValue(scan.last_error_code)}/><AdminFact label="Scan ID" value={shortId(scan.id)} mono/></AdminFactGrid>{typeof scan.media_source_scan_id==="string"&&<p className="muted-text">La Story reutiliza el scan del video canónico: <span className="mono">{shortId(scan.media_source_scan_id)}</span></p>}{scan.status==="failed"&&hasCapability("content.items.moderate")&&<button className="secondary" disabled={busy} onClick={()=>void retry()}>Reintentar scan</button>}</section></aside></div>
    {hasCapability("content.items.moderate")&&detail.status!=="resolved"&&detail.status!=="dismissed"&&<section className="detail-card"><h3>Revisión humana</h3><p className="muted-text">Estas acciones solo cambian el estado de la alerta. No ocultan contenido, no emiten warnings y no suspenden cuentas.</p><textarea aria-label="Nota de revisión" placeholder="Nota obligatoria para cerrar" value={note} onChange={(event)=>setNote(event.target.value)}/><select aria-label="Resultado" value={resolution} onChange={(event)=>setResolution(event.target.value)}><option value="reviewed">Revisado</option><option value="content_action_taken">Acción de contenido realizada por autoridad canónica</option><option value="user_action_taken">Acción de usuario realizada por autoridad F2</option></select><div className="button-row">{detail.status==="open"&&<button disabled={busy} onClick={()=>void act("take_review")}>Tomar para revisión</button>}<button className="secondary" disabled={busy} onClick={()=>void act("dismiss")}>Sin infracción</button><button disabled={busy} onClick={()=>void act("resolve")}>Marcar resuelto</button></div>{error&&<p role="alert">{error}</p>}</section>}
  </>;
}

const audioStatusLabel=(value:unknown)=>value==="analyzed"?"Analizado":value==="pending"?"Pendiente":value==="failed"?"Falló":value==="not_applicable"?"No aplica":"No configurado";
const secondsLabel=(value:unknown)=>typeof value==="number"?`${value.toFixed(1)} s`:humanValue(value);

export function AdminContentSafetyAudioPage(){
  const [data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError(null);void searchAdminContentSafetyAudio().then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar Audio AI")});return()=>{active=false}},[nonce]);
  if(error)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!data)return <LoadingState label="Cargando cobertura de Audio AI…"/>;
  const provider=asRecord(data.provider),stats=asRecord(data.stats),items=asRows(data.items);
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY · AUDIO AI</p><h2>Speech-to-Text</h2><p>Speech-to-Text AI analiza audio para generar señales de revisión. No aplica sanciones automáticamente.</p></div><Link className="secondary button-link" to="/content-safety">Volver a alertas</Link></div>
    <AdminStatusPanel title={`${humanValue(provider.name,"Cloudflare Workers AI")} · ${provider.status==="healthy"?"Activo":humanValue(provider.status,"Pendiente")}`} detail={`Modelo ${humanValue(provider.model,"@cf/openai/whisper-large-v3-turbo")} · último éxito ${formatDate(provider.last_success_at)}`} tone={provider.status==="error"?"danger":provider.status==="healthy"?"success":"warning"}/>
    <section className="safety-stat-grid" aria-label="Cobertura de Audio AI">{[{label:"Elegibles",value:stats.eligible},{label:"Pendientes",value:stats.pending},{label:"Analizados",value:stats.analyzed},{label:"Fallidos",value:stats.failed},{label:"No aplica",value:stats.not_applicable},{label:"No configurado",value:stats.not_configured},{label:"Transcripts",value:stats.transcripts},{label:"Provider calls",value:stats.provider_calls}].map((item)=><article key={item.label}><span>{item.label}</span><strong>{humanValue(item.value,"0")}</strong></article>)}</section>
    {items.length===0?<EmptyState title="Sin cobertura multimedia" detail="No hay scans de video o Story para inspeccionar."/>:<section className="table-panel"><table className="human-table"><thead><tr><th>Contenido</th><th>Audio</th><th>Modelo</th><th>Transcripción</th><th>Señales</th><th>Procesado</th></tr></thead><tbody>{items.map((item)=><tr key={String(item.scan_id)}><td><Link to={`/content-safety/audio/${String(item.scan_id)}`}><strong>{targetLabel(item.target_type)}</strong><span className="truncate">{humanValue(item.summary,"Sin texto visible")}</span><small className="mono">{shortId(item.target_id)}</small></Link></td><td><em className={`badge ${item.audio_status==="analyzed"?"success":item.audio_status==="failed"?"danger":item.audio_status==="pending"?"warn":""}`}>{audioStatusLabel(item.audio_status)}</em><small className="table-secondary">{secondsLabel(item.duration_seconds)}</small></td><td><small>{humanValue(item.provider,"—")}<br/><span className="mono">{humanValue(item.model,"—")}</span></small></td><td><small>{item.source_reused===true?"Reutilizada desde video fuente":humanValue(item.transcript_status,"Sin transcript")}<br/>{humanValue(item.detected_language,"Idioma no informado")} · {humanValue(item.word_count,"0")} palabras</small></td><td>{humanValue(item.rule_matches,"0")}</td><td>{formatDate(item.processed_at)}</td></tr>)}</tbody></table></section>}
  </>;
}

export function AdminContentSafetyAudioDetailPage(){
  const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError(null);void getAdminContentSafetyAudioDetail(id).then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar el transcript")});return()=>{active=false}},[id,nonce]);
  const retry=async()=>{setBusy(true);setError(null);try{await retryAdminContentSafetyAudio({id,idempotencyKey:crypto.randomUUID()});setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo reintentar el audio")}finally{setBusy(false)}};
  if(error&&!data)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!data)return <LoadingState label="Cargando detalle de Audio AI…"/>;
  const content=asRecord(data.content),author=asRecord(data.author),transcript=asRecord(data.transcript),segments=asRows(transcript.segments),references=asRows(data.shared_references);
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY · AUDIO AI</p><h2>{targetLabel(data.target_type)} · {audioStatusLabel(data.audio_status)}</h2><p className="mono">{id}</p></div><Link className="secondary button-link" to="/content-safety/audio">Volver a Audio AI</Link></div>
    {data.source_reused===true&&<AdminStatusPanel title="Transcripción reutilizada desde video fuente" detail={`Source scan ${shortId(data.source_scan_id)} · no se realizó otra llamada a Whisper para esta Story.`} tone="success"/>}
    <div className="presentation-grid"><div className="presentation-stack"><section className="presentation-card"><header><h3>Transcripción privada</h3></header>{transcript.no_speech===true?<AdminStatusPanel title="Sin habla detectada" detail="El proveedor completó el análisis y no devolvió voz transcribible." tone="neutral"/>:<p>{humanValue(transcript.text,"Transcripción todavía no disponible")}</p>}<AdminFactGrid><AdminFact label="Palabras" value={humanValue(transcript.word_count,"0")}/><AdminFact label="Idioma detectado" value={humanValue(transcript.detected_language,"No informado")}/><AdminFact label="Fingerprint" value={humanValue(transcript.fingerprint)} mono/><AdminFact label="Rule evaluation" value={humanValue(transcript.rule_eval_status)}/></AdminFactGrid>{segments.length>0&&<div className="status-list">{segments.map((segment,index)=><AdminStatusPanel key={`${String(segment.start)}:${index}`} title={`${secondsLabel(segment.start)} – ${secondsLabel(segment.end)}`} detail={humanValue(segment.text)} tone="neutral"/>)}</div>}<p className="muted-text">Una transcripción AI puede contener errores. Toda coincidencia requiere revisión humana.</p></section>
      <section className="presentation-card"><header><h3>Referencias compartidas</h3><em className="badge">{references.length}</em></header>{references.length===0?<p className="muted-text">Sin Stories activas que reutilicen esta fuente.</p>:references.map((reference)=><Link className="secondary button-link" key={String(reference.id)} to={String(reference.path)}>Abrir Story · {shortId(reference.id)}</Link>)}</section></div>
      <aside className="presentation-stack"><section className="presentation-card"><header><h3>Fuente canónica</h3></header><AdminIdentity value={author}/><AdminFactGrid><AdminFact label="Proveedor" value={humanValue(data.provider)}/><AdminFact label="Modelo" value={humanValue(data.model)} mono/><AdminFact label="Duración" value={secondsLabel(data.duration_seconds)}/><AdminFact label="Asset" value={shortId(data.source_asset_id)} mono/><AdminFact label="Intentos" value={humanValue(data.attempts,"0")}/><AdminFact label="Error" value={humanValue(data.last_error_code)}/><AdminFact label="Cleanup pendiente" value={data.cleanup_pending===true?"Sí":"No"}/><AdminFact label="Completado" value={formatDate(data.completed_at)}/></AdminFactGrid><div className="button-row"><Link className="button-link" to={String(content.path||"/content")}>Abrir contenido canónico</Link>{typeof data.source_target_id==="string"&&<Link className="secondary button-link" to={`/content/video/${data.source_target_id}`}>Abrir video canónico</Link>}</div>{data.audio_status==="failed"&&hasCapability("content.items.moderate")&&<button className="secondary" disabled={busy} onClick={()=>void retry()}>Reintentar transcripción</button>}{error&&<p role="alert">{error}</p>}</section></aside></div>
  </>;
}

const approvalLabel=(value:unknown)=>value==="draft"?"Borrador":value==="approved"?"Aprobada":value==="retired"?"Retirada":humanValue(value);
const policyLabel=(value:unknown)=>value==="community_guidelines"?"Directrices de la Comunidad":value==="terms"?"Términos":value==="owner_manual"?"Decisión manual del propietario":humanValue(value);

function ScopePicker({selected,onChange,disabled=false,label="Scopes"}:{selected:string[];onChange:(value:string[])=>void;disabled?:boolean;label?:string}){
  return <fieldset className="safety-scope-picker" disabled={disabled}><legend>{label}</legend>{scopes.map((scope)=><label key={scope}><input type="checkbox" checked={selected.includes(scope)} onChange={()=>onChange(selected.includes(scope)?selected.filter((value)=>value!==scope):[...selected,scope])}/>{scope}</label>)}</fieldset>;
}

function RulePreview({preview}:{preview:Record<string,unknown>}){
  const counts=asRecord(preview.counts),samples=asRows(preview.samples);
  return <div className="safety-rule-preview" role="status"><AdminStatusPanel title={`${humanValue(preview.total_matching_content,"0")} coincidencias potenciales`} detail="Una coincidencia no significa una infracción. El preview no crea scans, alertas ni acciones." tone="neutral"/><AdminFactGrid><AdminFact label="Videos" value={humanValue(counts.videos,"0")}/><AdminFact label="Stories" value={humanValue(counts.stories,"0")}/><AdminFact label="Comentarios" value={humanValue(counts.comments,"0")}/><AdminFact label="Chat LIVE" value={humanValue(counts.live_chat,"0")}/><AdminFact label="Mensajes reportados" value={humanValue(counts.reported_messages,"0")}/></AdminFactGrid>{samples.length>0&&<div className="status-list">{samples.map((sample)=><AdminStatusPanel key={`${String(sample.target_type)}:${String(sample.target_id)}`} title={`${targetLabel(sample.target_type)} · ${shortId(sample.target_id)}`} detail={humanValue(sample.excerpt)} tone="neutral"/>)}</div>}<small>Máximo {humanValue(preview.sample_limit,"20")} ejemplos · extractos de hasta {humanValue(preview.excerpt_limit,"240")} caracteres · mensajes privados ordinarios excluidos.</small></div>;
}

function ContentSafetyRuleCard({rule,canManage,onSaved}:{rule:Record<string,unknown>;canManage:boolean;onSaved:()=>void}){
  const [label,setLabel]=useState(String(rule.label||""));
  const [category,setCategory]=useState(String(rule.category||"other"));
  const [severity,setSeverity]=useState(String(rule.severity||"medium"));
  const [selectedScopes,setSelectedScopes]=useState<string[]>(Array.isArray(rule.scopes)?rule.scopes.map(String):[]);
  const [policySource,setPolicySource]=useState(String(rule.policy_source||"owner_manual"));
  const [policyReference,setPolicyReference]=useState(String(rule.policy_reference||""));
  const [policyVersion,setPolicyVersion]=useState(String(rule.policy_version||""));
  const [rationale,setRationale]=useState(String(rule.rationale||""));
  const [preview,setPreview]=useState<Record<string,unknown>|null>(null);
  const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  useEffect(()=>{setLabel(String(rule.label||""));setCategory(String(rule.category||"other"));setSeverity(String(rule.severity||"medium"));setSelectedScopes(Array.isArray(rule.scopes)?rule.scopes.map(String):[]);setPolicySource(String(rule.policy_source||"owner_manual"));setPolicyReference(String(rule.policy_reference||""));setPolicyVersion(String(rule.policy_version||""));setRationale(String(rule.rationale||""));setDirty(false);setPreview(null);setError(null)},[rule.id,rule.version,rule.updated_at,rule.label,rule.category,rule.severity,rule.scopes,rule.policy_source,rule.policy_reference,rule.policy_version,rule.rationale]);
  const edit=(change:()=>void)=>{change();setDirty(true);setPreview(null);setError(null)};
  const previewScopes=Array.isArray(preview?.scopes)?preview.scopes.map(String):[];
  const canonicalScopes=Array.isArray(rule.scopes)?rule.scopes.map(String):[];
  const previewValid=preview!==null&&!dirty&&String(preview.rule_id)===String(rule.id)&&Number(preview.rule_version)===Number(rule.version)&&String(preview.definition_fingerprint)===String(rule.definition_fingerprint)&&String(preview.detector_type)===String(rule.detector_type)&&String(preview.locale)===String(rule.locale)&&previewScopes.length===canonicalScopes.length&&previewScopes.every((value,index)=>value===canonicalScopes[index]);
  const previewFingerprint=previewValid?String(preview?.definition_fingerprint):"";
  const run=async(operation:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await operation();setPreview(null);setDirty(false);onSaved()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo gobernar la regla")}finally{setBusy(false)}};
  const test=async()=>{if(dirty)return setError("Guarda los cambios y espera la definición canónica antes de probarla.");setBusy(true);setError(null);try{setPreview(await previewAdminContentSafetyRule({id:String(rule.id),limit:20}))}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo probar la regla")}finally{setBusy(false)}};
  const save=()=>run(()=>updateAdminContentSafetyRule({id:String(rule.id),label:label.trim(),category,severity,scopes:selectedScopes,policySource,policyReference:policyReference.trim(),policyVersion:policyVersion.trim()||null,rationale:rationale.trim()||null,idempotencyKey:crypto.randomUUID()}));
  const approve=()=>{if(!previewValid)return setError("El preview no corresponde a la versión canónica actual.");if(!window.confirm("Aprobar esta regla confirma su procedencia, severidad y alcance. Todavía no se activará."))return;void run(()=>approveAdminContentSafetyRule({id:String(rule.id),definitionFingerprint:previewFingerprint,idempotencyKey:crypto.randomUUID()}))};
  const enable=()=>{if(!previewValid)return setError("El preview no corresponde a la versión canónica actual.");if(!window.confirm("Al activar esta regla, el contenido elegible podrá generar alertas. No se aplicarán sanciones automáticas."))return;void run(()=>setAdminContentSafetyRuleEnabled({id:String(rule.id),enabled:true,definitionFingerprint:previewFingerprint,idempotencyKey:crypto.randomUUID()}))};
  const disable=()=>{if(!window.confirm("Desactivar la regla detendrá nuevas detecciones; no elimina alertas ni historia."))return;void run(()=>setAdminContentSafetyRuleEnabled({id:String(rule.id),enabled:false,idempotencyKey:crypto.randomUUID()}))};
  const retire=()=>{if(!window.confirm("Retirar esta regla la desactiva permanentemente y conserva toda su historia."))return;void run(()=>retireAdminContentSafetyRule({id:String(rule.id),idempotencyKey:crypto.randomUUID()}))};
  const retired=rule.approval_state==="retired",rescan=asRecord(rule.rescan);
  return <article className="presentation-card safety-rule-card"><header><div><h3>{humanValue(rule.label)}</h3><p className="mono">{humanValue(rule.code)} · v{humanValue(rule.version)}</p></div><div className="button-row"><em className={`badge ${rule.approval_state==="approved"?"success":rule.approval_state==="draft"?"warn":""}`}>{approvalLabel(rule.approval_state)}</em><em className={`badge ${rule.enabled===true?"success":""}`}>{rule.enabled===true?"Activa":"Inactiva"}</em></div></header><AdminFactGrid><AdminFact label="Patrón inmutable" value={humanValue(rule.pattern)}/><AdminFact label="Detector" value={humanValue(rule.detector_type)}/><AdminFact label="Categoría" value={humanValue(rule.category)}/><AdminFact label="Severidad" value={severityLabel(rule.severity)}/><AdminFact label="Locale" value={humanValue(rule.locale)}/><AdminFact label="Origen" value={policyLabel(rule.policy_source)}/><AdminFact label="Referencia" value={humanValue(rule.policy_reference)} mono/><AdminFact label="Versión política" value={humanValue(rule.policy_version)}/><AdminFact label="Aprobada por" value={humanValue(asRecord(rule.approved_by).display_name,humanValue(asRecord(rule.approved_by).username))}/><AdminFact label="Aprobada" value={formatDate(rule.approved_at)}/><AdminFact label="Actualizada" value={formatDate(rule.updated_at)}/><AdminFact label="Rescan" value={humanValue(rescan.state,"idle")}/><AdminFact label="Progreso rescan" value={`${humanValue(rescan.queued_count,"0")} / ${humanValue(rescan.eligible_count,"0")}`}/></AdminFactGrid><p className="muted-text">{humanValue(rule.rationale,"Sin rationale adicional")}</p><div className="safety-term-list">{(Array.isArray(rule.scopes)?rule.scopes:[]).map((scope)=><em className="badge" key={String(scope)}>{String(scope)}</em>)}</div>
    {canManage&&!retired&&<details><summary>Editar gobierno</summary><div className="safety-rule-editor"><div className="filters"><input aria-label={`Nombre ${humanValue(rule.code)}`} value={label} onChange={(event)=>edit(()=>setLabel(event.target.value))}/><select aria-label={`Categoría ${humanValue(rule.code)}`} value={category} onChange={(event)=>edit(()=>setCategory(event.target.value))}>{categories.map((value)=><option key={value}>{value}</option>)}</select><select aria-label={`Severidad ${humanValue(rule.code)}`} value={severity} onChange={(event)=>edit(()=>setSeverity(event.target.value))}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select><select aria-label={`Policy source ${humanValue(rule.code)}`} value={policySource} onChange={(event)=>edit(()=>setPolicySource(event.target.value))}><option value="terms">Términos</option><option value="community_guidelines">Directrices</option><option value="owner_manual">Owner manual</option></select></div><div className="filters"><input aria-label={`Policy reference ${humanValue(rule.code)}`} value={policyReference} onChange={(event)=>edit(()=>setPolicyReference(event.target.value))}/><input aria-label={`Policy version ${humanValue(rule.code)}`} value={policyVersion} onChange={(event)=>edit(()=>setPolicyVersion(event.target.value))}/></div><textarea aria-label={`Rationale ${humanValue(rule.code)}`} value={rationale} onChange={(event)=>edit(()=>setRationale(event.target.value))} placeholder="Obligatorio para owner_manual"/><ScopePicker selected={selectedScopes} onChange={(value)=>edit(()=>setSelectedScopes(value))}/><button className="secondary" disabled={busy||!dirty} onClick={()=>void save()}>Guardar como borrador</button><small>{dirty?"Cambios sin guardar: preview, aprobación y activación están bloqueados.":"Editar gobierno revoca aprobación y desactiva la regla hasta una nueva revisión humana."}</small></div></details>}
    {canManage&&!retired&&<div className="button-row"><button className="secondary" disabled={busy||dirty} onClick={()=>void test()}>Probar regla</button>{rule.approval_state==="draft"&&<button disabled={busy||!previewValid} onClick={approve}>Aprobar regla</button>}{rule.approval_state==="approved"&&rule.enabled!==true&&<button disabled={busy||!previewValid} onClick={enable}>Activar</button>}{rule.approval_state==="approved"&&rule.enabled===true&&<button className="secondary" disabled={busy} onClick={disable}>Desactivar</button>}<button className="danger" disabled={busy} onClick={retire}>Retirar</button></div>}{preview&&<RulePreview preview={preview}/>} {error&&<p role="alert">{error}</p>}</article>;
}

export function AdminContentSafetyRulesPage(){
  const {hasCapability}=useAdminAuth();
  const [data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0),[busy,setBusy]=useState(false);
  const [code,setCode]=useState(""),[label,setLabel]=useState(""),[category,setCategory]=useState("other"),[detector,setDetector]=useState("keyword"),[pattern,setPattern]=useState(""),[severity,setSeverity]=useState("medium"),[locale,setLocale]=useState("und"),[selectedScopes,setSelectedScopes]=useState<string[]>(["video_caption"]),[policySource,setPolicySource]=useState("owner_manual"),[policyReference,setPolicyReference]=useState(""),[policyVersion,setPolicyVersion]=useState(""),[rationale,setRationale]=useState(""),[preview,setPreview]=useState<Record<string,unknown>|null>(null);
  useEffect(()=>{let active=true;setData(null);setError(null);void searchAdminContentSafetyRules().then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudieron cargar las reglas")});return()=>{active=false}},[nonce]);
  const validate=()=>{if(!/^[a-z][a-z0-9_]{2,63}$/.test(code.trim()))return "El code debe usar snake_case técnico.";if(label.trim().length<2||pattern.trim().length<1||selectedScopes.length===0||policyReference.trim().length<3)return "Completa nombre, patrón, referencia y al menos un scope.";if(policySource==="owner_manual"&&rationale.trim().length<2)return "Owner manual requiere rationale.";return null};
  const test=async()=>{const issue=validate();if(issue)return setError(issue);setBusy(true);setError(null);try{setPreview(await previewAdminContentSafetyRuleDraft({detectorType:detector,pattern:pattern.trim(),scopes:selectedScopes,locale,limit:20}))}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo probar la regla")}finally{setBusy(false)}};
  const create=async()=>{const issue=validate();if(issue)return setError(issue);setBusy(true);setError(null);try{await createAdminContentSafetyRule({code:code.trim(),label:label.trim(),category,detectorType:detector,pattern:pattern.trim(),severity,scopes:selectedScopes,locale,policySource,policyReference:policyReference.trim(),policyVersion:policyVersion.trim()||null,rationale:rationale.trim()||null,idempotencyKey:crypto.randomUUID()});setCode("");setLabel("");setPattern("");setPolicyReference("");setPolicyVersion("");setRationale("");setPreview(null);setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo crear la regla")}finally{setBusy(false)}};
  if(error&&!data)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!data)return <LoadingState label="Cargando reglas…"/>;
  const rules=asRows(data.items),stats=asRecord(data.stats),canManage=hasCapability("content.items.moderate");
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY</p><h2>Política y reglas textuales</h2><p>Policy → borrador → preview → aprobación humana → activación controlada.</p></div><Link className="secondary button-link" to="/content-safety">Volver a alertas</Link></div><AdminStatusPanel title="Gobierno listo · sin términos inventados" detail="Los documentos actuales definen categorías de conducta, no un termset literal con severidad. Las reglas activas permanecen en 0 hasta una decisión humana explícita." tone="warning"/><section className="safety-stat-grid" aria-label="Gobierno de reglas">{[{label:"Total",value:stats.total},{label:"Borrador",value:stats.draft},{label:"Aprobadas",value:stats.approved},{label:"Activas",value:stats.enabled},{label:"Retiradas",value:stats.retired}].map((item)=><article key={item.label}><span>{item.label}</span><strong>{humanValue(item.value,"0")}</strong></article>)}</section>{rules.length===0?<EmptyState title="0 reglas configuradas" detail="El motor y el preview están listos. El propietario debe aportar o aprobar explícitamente cada término, locale, severity y scope."/>:<section className="safety-rule-list">{rules.map((rule)=><ContentSafetyRuleCard key={String(rule.id)} rule={rule} canManage={canManage} onSaved={()=>setNonce((value)=>value+1)}/>)}</section>}
    {canManage&&<section className="detail-card safety-rule-form"><h3>Crear borrador</h3><p className="muted-text">Crear guarda siempre un borrador desactivado. No genera scans, alertas ni sanciones.</p><div className="filters"><input aria-label="Code de regla" placeholder="code_snake_case" value={code} onChange={(event)=>setCode(event.target.value)}/><input aria-label="Nombre de regla" placeholder="Nombre" value={label} onChange={(event)=>setLabel(event.target.value)}/><select aria-label="Categoría de regla" value={category} onChange={(event)=>setCategory(event.target.value)}>{categories.map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Detector" value={detector} onChange={(event)=>setDetector(event.target.value)}><option value="keyword">Keyword</option><option value="phrase">Phrase</option></select><select aria-label="Severidad de regla" value={severity} onChange={(event)=>setSeverity(event.target.value)}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select><select aria-label="Locale" value={locale} onChange={(event)=>setLocale(event.target.value)}><option value="und">und</option><option value="es">es</option><option value="en">en</option></select></div><input aria-label="Palabra o frase" placeholder="Literal aprobado; no se generan variantes" value={pattern} onChange={(event)=>{setPattern(event.target.value);setPreview(null)}}/><div className="filters"><select aria-label="Policy source" value={policySource} onChange={(event)=>setPolicySource(event.target.value)}><option value="terms">Términos</option><option value="community_guidelines">Directrices de la Comunidad</option><option value="owner_manual">Decisión manual del propietario</option></select><input aria-label="Policy reference" placeholder="terms#prohibited-content u owner-policy-2026-09" value={policyReference} onChange={(event)=>setPolicyReference(event.target.value)}/><input aria-label="Policy version" placeholder="Versión (opcional)" value={policyVersion} onChange={(event)=>setPolicyVersion(event.target.value)}/></div><textarea aria-label="Rationale" placeholder="Rationale obligatorio para owner_manual" value={rationale} onChange={(event)=>setRationale(event.target.value)}/><ScopePicker selected={selectedScopes} onChange={(value)=>{setSelectedScopes(value);setPreview(null)}}/><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void test()}>Probar regla</button><button disabled={busy} onClick={()=>void create()}>Guardar borrador</button></div>{preview&&<RulePreview preview={preview}/>} {error&&<p role="alert">{error}</p>}<small>Pattern, detector y locale no se editan: para cambiar su significado se crea otra regla y se retira la anterior.</small></section>}
  </>;
}
