import {useEffect,useRef,useState,type ReactNode} from "react";
import {Link,useParams} from "react-router-dom";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {
  getAdminFinanceOverview,getAdminFinanceReconciliation,getAdminFinancialTransactionDetail,
  getAdminSystemHealth,getAdminSystemJobDetail,searchAdminFinanceAnomalies,
  searchAdminFinanceAudit,searchAdminFinancialTransactions,searchAdminGlobalAudit,
  searchAdminLedgerAccounts,searchAdminSystemAudit,searchAdminSystemJobs,type JsonRecord
} from "../lib/adminObservabilityApi";

function useRead<T>(load:()=>Promise<T>,queryKey:string){const loadRef=useRef(load),[value,setValue]=useState<T|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);loadRef.current=load;useEffect(()=>{let active=true;setValue(null);setError(null);void loadRef.current().then((result)=>{if(active)setValue(result)}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Error de consulta")});return()=>{active=false}},[nonce,queryKey]);return{value,error,retry:()=>setNonce((x)=>x+1)}}
function Frame({eyebrow,title,detail,children}:{eyebrow:string;title:string;detail:string;children:ReactNode}){return <><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{detail}</p></div></div>{children}</>}
function ReadResult({value,error,retry,empty="Sin resultados"}:{value:unknown;error:string|null;retry:()=>void;empty?:string}){if(error)return <ErrorState message={error} onRetry={retry}/>;if(value===null)return <LoadingState label="Consultando…"/>;if(Array.isArray(value)&&value.length===0)return <EmptyState title={empty} detail="La consulta canónica no devolvió filas."/>;return <section className="detail-card"><pre>{JSON.stringify(value,null,2)}</pre></section>}

export function AdminFinanceOverviewPage(){const state=useRead(getAdminFinanceOverview,"overview");return <Frame eyebrow="FINANCE · READ ONLY" title="Finanzas" detail="Resumen del ledger canónico sin acciones financieras."><ReadResult {...state}/></Frame>}

export function AdminLedgerAccountsPage(){const [accountType,setAccountType]=useState(""),[currency,setCurrency]=useState("");const state=useRead(()=>searchAdminLedgerAccounts({p_account_type:accountType||null,p_currency:currency||null,p_limit:100}),`${accountType}|${currency}`);return <Frame eyebrow="CANONICAL LEDGER" title="Cuentas" detail="Balances y propietarios con identidad pública mínima."><div className="filters"><input aria-label="Tipo de cuenta" placeholder="Tipo de cuenta" value={accountType} onChange={(e)=>setAccountType(e.target.value)}/><input aria-label="Moneda" placeholder="Moneda" value={currency} onChange={(e)=>setCurrency(e.target.value)}/></div><ReadResult value={state.value?.items??null} error={state.error} retry={state.retry}/></Frame>}

export function AdminFinancialTransactionsPage(){const [operation,setOperation]=useState(""),[status,setStatus]=useState("");const state=useRead(()=>searchAdminFinancialTransactions({p_operation_type:operation||null,p_status:status||null,p_limit:100}),`${operation}|${status}`);return <Frame eyebrow="CANONICAL FINANCE" title="Transacciones" detail="Listado seguro sin metadata, idempotency keys ni wallets."><div className="filters"><input aria-label="Tipo de operación" placeholder="Tipo de operación" value={operation} onChange={(e)=>setOperation(e.target.value)}/><input aria-label="Estado" placeholder="Estado" value={status} onChange={(e)=>setStatus(e.target.value)}/></div>{state.error?<ErrorState message={state.error} onRetry={state.retry}/>:!state.value?<LoadingState label="Consultando…"/>:<section className="detail-card">{state.value.items.length===0?<EmptyState title="Sin transacciones" detail="No hay coincidencias."/>:state.value.items.map((item)=><p key={String(item.id)}><Link to={`/finance/transactions/${String(item.id)}`}>{String(item.operation_type)} · {String(item.amount)} {String(item.currency)}</Link> <small>{String(item.status)}</small></p>)}</section>}</Frame>}

export function AdminFinancialTransactionDetailPage(){const {id=""}=useParams();const state=useRead(()=>getAdminFinancialTransactionDetail(id),id);return <Frame eyebrow="FINANCE AUDIT" title="Detalle financiero" detail="Requiere ledger read y finance audit en servidor."><ReadResult {...state}/></Frame>}
export function AdminFinanceReconciliationPage(){const state=useRead(getAdminFinanceReconciliation,"reconciliation");return <Frame eyebrow="OBSERVATION ONLY" title="Reconciliación" detail="Estado observado; ningún reconciliador se ejecuta desde esta pantalla."><ReadResult {...state}/></Frame>}
export function AdminFinanceAnomaliesPage(){const [rule,setRule]=useState("");const state=useRead(()=>searchAdminFinanceAnomalies({p_rule_code:rule||null,p_limit:100}),rule);return <Frame eyebrow="PROVEN CONTRACTS" title="Anomalías" detail="Sólo invariantes demostrados; no hay reparación automática."><div className="filters"><input aria-label="Código de regla" placeholder="Código de regla" value={rule} onChange={(e)=>setRule(e.target.value)}/></div><ReadResult {...state}/></Frame>}

function AuditPage({kind}:{kind:"global"|"finance"|"system"}){const [action,setAction]=useState("");const loader=kind==="global"?()=>searchAdminGlobalAudit({p_action:action||null,p_limit:100}):kind==="finance"?()=>searchAdminFinanceAudit({p_action:action||null,p_limit:100}):()=>searchAdminSystemAudit({p_action:action||null,p_limit:100});const state=useRead(loader,`${kind}|${action}`);const title=kind==="global"?"Audit global":kind==="finance"?"Audit financiero":"Audit de sistema";return <Frame eyebrow="REDACTED AUDIT" title={title} detail="Proyección allow-listed; nunca expone metadata cruda, fingerprint ni idempotency key."><div className="filters"><input aria-label="Acción audit" placeholder="Acción" value={action} onChange={(e)=>setAction(e.target.value)}/></div><ReadResult value={state.value?.items??null} error={state.error} retry={state.retry}/></Frame>}
export const AdminGlobalAuditPage=()=> <AuditPage kind="global"/>;
export const AdminFinanceAuditPage=()=> <AuditPage kind="finance"/>;
export const AdminSystemAuditPage=()=> <AuditPage kind="system"/>;

export function AdminSystemHealthPage(){const state=useRead(getAdminSystemHealth,"health");return <Frame eyebrow="SYSTEM OBSERVABILITY" title="Salud del sistema" detail="Hechos agregados sin umbrales arbitrarios ni controles mutadores."><ReadResult {...state}/></Frame>}
export function AdminSystemJobsPage(){const [query,setQuery]=useState("");const state=useRead(()=>searchAdminSystemJobs({p_query:query||null,p_limit:100}),query);const items=state.value&&Array.isArray(state.value.items)?state.value.items.filter((x):x is JsonRecord=>x!==null&&typeof x==="object"&&!Array.isArray(x)):null;return <Frame eyebrow="PG_CRON · READ ONLY" title="Jobs" detail="Schedules y resultados sanitizados; no se devuelve SQL ni mensajes crudos."><div className="filters"><input aria-label="Buscar job" placeholder="Nombre del job" value={query} onChange={(e)=>setQuery(e.target.value)}/></div>{state.error?<ErrorState message={state.error} onRetry={state.retry}/>:items===null?<LoadingState label="Consultando jobs…"/>:<section className="detail-card">{items.length===0?<EmptyState title="Sin jobs" detail="No hay coincidencias."/>:items.map((job)=><p key={String(job.job_id)}><Link to={`/system/jobs/${String(job.job_id)}`}>{String(job.job_name)}</Link> <small>{job.active===true?"activo":"inactivo"} · {String(job.schedule)}</small></p>)}</section>}</Frame>}
export function AdminSystemJobDetailPage(){const {id=""}=useParams();const state=useRead(()=>getAdminSystemJobDetail(id),id);return <Frame eyebrow="PG_CRON · SAFE HISTORY" title="Historial del job" detail="Máximo 100 runs; sólo estado, timestamps, duración y presencia de error."><ReadResult {...state}/></Frame>}
