import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {cancelAdminLiveBattle,formatDate,getAdminLiveBattleDetail,searchAdminLiveBattles,type AdminBattleSummary} from "../lib/adminApi";

export function AdminBattlesPage(){const [status,setStatus]=useState(""),[query,setQuery]=useState(""),[items,setItems]=useState<AdminBattleSummary[]|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setItems(null);setError(null);void searchAdminLiveBattles({status,query}).then((page)=>{if(active)setItems(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[status,query,nonce]);return <><div className="page-heading"><div><p className="eyebrow">COMPETITIVE OPERATIONS</p><h2>Battles</h2><p>Lifecycle, scores y proyecciones competitivas canónicas.</p></div></div><div className="filters"><label className="search"><span>⌕</span><input aria-label="Buscar Battle" placeholder="Battle, serie o participante" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select aria-label="Estado Battle" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option>{["pending","accepted","countdown","active","completed","rejected","cancelled","expired"].map((value)=><option key={value}>{value}</option>)}</select></div>{error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!items?<LoadingState label="Buscando Battles…"/>:items.length===0?<EmptyState title="Sin Battles" detail="No hay coincidencias."/>:<section className="table-panel"><div className="orders-table" role="table"><div className="table-head" role="row"><span>Battle</span><span>Participantes</span><span>Estado</span><span>Round</span><span>Score</span><span>Creada</span></div>{items.map((item)=><Link className="table-row" role="row" to={`/battles/${item.id}`} key={item.id}><span><strong>{item.id}</strong><small>Serie {item.series_id}</small></span><span>{item.challenger.display_name??item.challenger.username} vs {item.opponent.display_name??item.opponent.username}</span><span><em className="badge">{item.status}</em></span><span>{item.round_number}</span><span>{item.challenger_score}–{item.opponent_score}</span><span>{formatDate(item.created_at)}</span></Link>)}</div></section>}</>}

export function AdminBattleDetailPage(){const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [detail,setDetail]=useState<Record<string,unknown>|null>(null),[reason,setReason]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setDetail(null);setError(null);void getAdminLiveBattleDetail(id).then((value)=>{if(active)setDetail(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[id,nonce]);const battle=detail?.battle&&typeof detail.battle==="object"?detail.battle as Record<string,unknown>:{};const open=["pending","accepted","countdown","active"].includes(String(battle.status));const cancel=async()=>{const why=reason.trim();if(why.length<2)return setError("Escribe un motivo de al menos 2 caracteres.");if(!window.confirm("¿Cancelar este Battle mediante el lifecycle canónico?"))return;setBusy(true);setError(null);try{await cancelAdminLiveBattle({battleId:id,reason:why,idempotencyKey:crypto.randomUUID()});setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo cancelar") }finally{setBusy(false)}};if(error&&!detail)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;if(!detail)return <LoadingState label="Cargando Battle…"/>;return <><div className="page-heading"><div><p className="eyebrow">BATTLE</p><h2>{id}</h2><p>Estado y proyecciones canónicas.</p></div><em className="badge">{String(battle.status??"—")}</em></div><section className="detail-card"><h3>Detalle seguro</h3><pre>{JSON.stringify(detail,null,2)}</pre></section>{open&&hasCapability("battles.sessions.moderate")?<section className="detail-card"><h3>Cancelar Battle</h3><textarea aria-label="Motivo Battle" placeholder="Motivo obligatorio" value={reason} onChange={(e)=>setReason(e.target.value)}/><button className="danger" disabled={busy} onClick={()=>void cancel()}>Cancelar Battle</button><small>No modifica score, gifts, ledger ni wallets.</small>{error?<p role="alert">{error}</p>:null}</section>:null}</>}
