import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {AdminFact,AdminFactGrid,AdminIdentity,AdminMediaPreview,asRecord,humanValue,shortId} from "../components/AdminPresentation";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {formatDate,getAdminMediaUrl,getAdminStoryDetail,moderateAdminStory,searchAdminStories,type AdminStorySummary} from "../lib/adminApi";

export function AdminStoriesPage(){
  const [query,setQuery]=useState(""),[visibility,setVisibility]=useState(""),[items,setItems]=useState<AdminStorySummary[]|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setItems(null);setError(null);void searchAdminStories({query,visibility}).then((page)=>{if(active)setItems(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[query,visibility,nonce]);
  return <><div className="page-heading"><div><p className="eyebrow">TRUST &amp; SAFETY</p><h2>Stories</h2><p>Visibilidad reversible sin alterar expiración ni lifecycle de media.</p></div></div><div className="filters"><label className="search"><span>⌕</span><input aria-label="Buscar Stories" placeholder="ID o autor" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select aria-label="Visibilidad de Story" value={visibility} onChange={(e)=>setVisibility(e.target.value)}><option value="">Toda visibilidad</option><option value="visible">Visible</option><option value="hidden">Oculta</option></select></div>{error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!items?<LoadingState label="Buscando Stories…"/>:items.length===0?<EmptyState title="Sin Stories" detail="No hay Stories para estos filtros."/>:<section className="table-panel"><table className="human-table"><thead><tr><th>Preview</th><th>Story</th><th>Autor</th><th>Expira</th><th>Estado</th><th>Creada</th></tr></thead><tbody>{items.map((story)=><tr key={story.id}><td><Link className={`admin-media-thumb ${story.media_type}`} to={`/stories/${story.id}`} aria-label="Abrir Story">{story.preview_url?<img src={story.preview_url} alt="Vista previa de la Story"/>:<span>{story.media_type}</span>}</Link></td><td><Link to={`/stories/${story.id}`}><strong>{story.story_kind}</strong><small>{story.media_type} · {shortId(story.id)}</small></Link></td><td><AdminIdentity value={story.owner} compact/></td><td>{formatDate(story.expires_at)}</td><td><em className={`badge ${story.visibility==="hidden"?"warn":"success"}`}>{story.visibility}</em></td><td>{formatDate(story.created_at)}</td></tr>)}</tbody></table></section>}</>
}

export function AdminStoryDetailPage(){
  const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [detail,setDetail]=useState<Record<string,unknown>|null>(null),[reason,setReason]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0),[mediaUrl,setMediaUrl]=useState<string|null>(null),[mediaError,setMediaError]=useState<string|null>(null),[mediaNonce,setMediaNonce]=useState(0),[mediaLoading,setMediaLoading]=useState(false);
  useEffect(()=>{let active=true;setDetail(null);setError(null);void getAdminStoryDetail(id).then((value)=>{if(active)setDetail(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[id,nonce]);
  const assetId=typeof detail?.media_asset_id==="string"?detail.media_asset_id:null,publicPreview=typeof detail?.preview_url==="string"?detail.preview_url:null;
  useEffect(()=>{if(!assetId||publicPreview){setMediaUrl(publicPreview);setMediaError(null);return}let active=true;setMediaLoading(true);setMediaError(null);void getAdminMediaUrl(assetId,{surface:"story",entityId:id}).then((url)=>{if(active)setMediaUrl(url)}).catch((e)=>{if(active)setMediaError(e instanceof Error?e.message:"No se pudo abrir la Story")}).finally(()=>{if(active)setMediaLoading(false)});return()=>{active=false}},[assetId,publicPreview,id,mediaNonce]);
  const visibility=detail?.visibility==="hidden"?"hidden":"visible",action=visibility==="hidden"?"restore":"hide";
  const run=async()=>{if(reason.trim().length<2)return setError("Indica un motivo de al menos 2 caracteres.");setBusy(true);setError(null);try{await moderateAdminStory({id,action,reason:reason.trim(),idempotencyKey:crypto.randomUUID()});setReason("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo moderar la Story")}finally{setBusy(false)}};
  if(error&&!detail)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;if(!detail)return <LoadingState label="Cargando Story…"/>;
  const owner=asRecord(detail.owner),composition=asRecord(detail.composition);
  return <><div className="page-heading"><div><p className="eyebrow">STORY</p><h2>{humanValue(detail.story_kind,"Story")}</h2><p className="mono">{id}</p></div><em className={`badge ${visibility==="hidden"?"warn":"success"}`}>{visibility}</em></div><div className="presentation-grid"><div className="presentation-stack"><section className="presentation-card"><header><h3>Vista previa</h3></header><div className="admin-media-frame"><AdminMediaPreview url={mediaUrl} kind={String(detail.media_type??"image")} alt="Vista previa administrativa de la Story" loading={mediaLoading} error={mediaError} onRetry={()=>setMediaNonce((x)=>x+1)} restricted={!publicPreview&&!!assetId}/></div></section><section className="presentation-card"><header><h3>Composición</h3></header>{Object.keys(composition).length?<AdminFactGrid>{Object.entries(composition).map(([key,value])=><AdminFact key={key} label={key.replaceAll("_"," ")} value={typeof value==="object"?"Configuración protegida":humanValue(value)}/>)}</AdminFactGrid>:<p className="muted-text">Sin composición adicional.</p>}</section></div><aside className="presentation-stack"><section className="presentation-card"><header><h3>Autor</h3></header><AdminIdentity value={owner}/></section><section className="presentation-card"><header><h3>Información</h3></header><AdminFactGrid><AdminFact label="Tipo" value={humanValue(detail.story_kind)}/><AdminFact label="Media" value={humanValue(detail.media_type)}/><AdminFact label="Creada" value={formatDate(detail.created_at)}/><AdminFact label="Expira" value={formatDate(detail.expires_at)}/><AdminFact label="Visibilidad" value={visibility}/><AdminFact label="Story ID" value={shortId(detail.id)} mono/>{Boolean(detail.shared_video_id)&&<AdminFact label="Video compartido" value={shortId(detail.shared_video_id)} mono/>}{Boolean(detail.shared_content_type)&&<AdminFact label="Contenido compartido" value={humanValue(detail.shared_content_type)}/>}</AdminFactGrid></section></aside></div>{hasCapability("stories.items.moderate")&&<section className="detail-card"><h3>{action==="hide"?"Ocultar":"Restaurar"} Story</h3><textarea aria-label="Motivo" placeholder="Motivo obligatorio" value={reason} onChange={(e)=>setReason(e.target.value)}/><div className="button-row"><button className={action==="hide"?"danger":""} disabled={busy} onClick={()=>void run()}>{action==="hide"?"Ocultar Story":"Restaurar Story"}</button></div>{error&&<p role="alert">{error}</p>}<small>La expiración, media y propiedad no se modifican.</small></section>}</>
}
