import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {AdminFact,AdminFactGrid,AdminIdentity,shortId} from "../components/AdminPresentation";
import {AdminReportSubject} from "../components/AdminReportSubject";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {dismissAdminReport,formatDate,getAdminReportDetail,reviewAdminReport,searchAdminReports,type AdminReportDetail,type AdminReportSummary} from "../lib/adminApi";

export function AdminReportsPage(){const [status,setStatus]=useState(""),[contentType,setContentType]=useState(""),[query,setQuery]=useState(""),[items,setItems]=useState<AdminReportSummary[]|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setItems(null);setError(null);void searchAdminReports({status,contentType,query}).then((page)=>{if(active)setItems(page.items)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[status,contentType,query,nonce]);return <><div className="page-heading"><div><p className="eyebrow">TRUST &amp; SAFETY</p><h2>Reportes</h2><p>Casos administrados mediante capabilities y contexto acotado.</p></div></div><div className="filters"><label className="search"><span>⌕</span><input aria-label="Buscar reportes" placeholder="ID o motivo" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select aria-label="Estado" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendientes</option><option value="reviewed">Revisados</option><option value="dismissed">Descartados</option></select><select aria-label="Tipo reportado" value={contentType} onChange={(e)=>setContentType(e.target.value)}><option value="">Todos los tipos</option>{["video","comment","user","story","message"].map((value)=><option key={value}>{value}</option>)}</select></div>{error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!items?<LoadingState label="Buscando reportes…"/>:items.length===0?<EmptyState title="Sin reportes" detail="No hay coincidencias para estos filtros."/>:<section className="table-panel"><table className="human-table"><thead><tr><th>Reporte</th><th>Reportante</th><th>Motivo</th><th>Tipo</th><th>Estado</th><th>Creado</th></tr></thead><tbody>{items.map((report)=><tr key={report.id}><td><Link to={`/reports/${report.id}`}><strong>{shortId(report.id)}</strong></Link></td><td><AdminIdentity value={report.reporter} compact/></td><td><span className="truncate">{report.reason}</span></td><td>{report.reported_content_type}</td><td><em className={`badge ${report.status==="pending"?"warn":""}`}>{report.status}</em></td><td>{formatDate(report.created_at)}</td></tr>)}</tbody></table></section>}</>}

export function AdminReportDetailPage(){const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [report,setReport]=useState<AdminReportDetail|null>(null),[note,setNote]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setReport(null);setError(null);void getAdminReportDetail(id).then((value)=>{if(active)setReport(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[id,nonce]);const run=async(action:"review"|"dismiss")=>{if(note.trim().length<2)return setError("Indica una nota de al menos 2 caracteres.");setBusy(true);setError(null);try{if(action==="review")await reviewAdminReport({id,note:note.trim(),idempotencyKey:crypto.randomUUID()});else await dismissAdminReport({id,reason:note.trim(),idempotencyKey:crypto.randomUUID()});setNote("");setNonce((x)=>x+1)}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar el reporte")}finally{setBusy(false)}};if(error&&!report)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;if(!report)return <LoadingState label="Cargando reporte…"/>;return <><div className="page-heading"><div><p className="eyebrow">REPORTE</p><h2>{report.reason}</h2><p className="mono">{report.id}</p></div><em className={`badge ${report.status==="pending"?"warn":""}`}>{report.status}</em></div><div className="presentation-grid"><section className="presentation-card"><header><h3>Contenido reportado</h3></header><AdminReportSubject subject={report.subject} reportId={report.id}/></section><aside className="presentation-stack"><section className="presentation-card"><header><h3>Reportante</h3></header><AdminIdentity value={report.reporter}/></section><section className="presentation-card"><header><h3>Caso</h3></header><AdminFactGrid><AdminFact label="Tipo" value={report.reported_content_type}/><AdminFact label="Estado" value={report.status}/><AdminFact label="Creado" value={formatDate(report.created_at)}/><AdminFact label="Subject ID" value={shortId(report.reported_content_id)} mono/></AdminFactGrid><p>{report.details??"Sin detalle adicional"}</p></section></aside></div>{report.status!=="dismissed"&&<section className="detail-card"><h3>Resolver caso</h3><textarea aria-label="Nota administrativa" placeholder="Nota o motivo obligatorio" value={note} onChange={(e)=>setNote(e.target.value)}/><div className="button-row">{report.status==="pending"&&hasCapability("reports.cases.review")&&<button disabled={busy} onClick={()=>void run("review")}>Marcar revisado</button>}{hasCapability("reports.cases.resolve")&&<button className="secondary" disabled={busy} onClick={()=>void run("dismiss")}>Descartar</button>}</div>{error&&<p role="alert">{error}</p>}</section>}</>}
