import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useAdminAuth} from "../auth/AdminAuthProvider";
import {AdminFact,AdminFactGrid,AdminIdentity,AdminStatusPanel,asRecord,asRows,humanValue,shortId} from "../components/AdminPresentation";
import {EmptyState,ErrorState,LoadingState} from "../components/PageState";
import {formatDate} from "../lib/adminApi";
import {createAdminContentSafetyRule,getAdminContentSafetyAlert,retryAdminContentSafetyScan,reviewAdminContentSafetyAlert,searchAdminContentSafetyAlerts,searchAdminContentSafetyRules,updateAdminContentSafetyRule} from "../lib/adminSafetyApi";

const severityLabel=(value:unknown)=>value==="critical"?"Crítica":value==="high"?"Alta":value==="medium"?"Media":"Baja";
const statusLabel=(value:unknown)=>value==="open"?"Abierta":value==="in_review"?"En revisión":value==="dismissed"?"Sin infracción":value==="resolved"?"Resuelta":humanValue(value);
const coverageLabel=(value:unknown)=>value==="analyzed"?"Analizado":value==="pending"?"Pendiente":value==="failed"?"Falló":value==="not_configured"?"No configurado":"No aplica";
const coverageTone=(value:unknown):"neutral"|"success"|"warning"|"danger"=>value==="analyzed"?"success":value==="failed"?"danger":value==="pending"?"warning":"neutral";
const targetLabel=(value:unknown)=>value==="video"?"Video":value==="comment"?"Comentario":value==="story"?"Story":value==="live_message"?"Chat LIVE":"Mensaje reportado";
const scopes=["video_caption","comment","story_text","live_chat","reported_message","transcript"];
const categories=["violence","threat","harassment","hate","sexual","self_harm","drugs","weapons","fraud","spam","child_safety","other"];

export function AdminContentSafetyPage(){
  const [severity,setSeverity]=useState(""),[status,setStatus]=useState("open"),[category,setCategory]=useState(""),[target,setTarget]=useState(""),[source,setSource]=useState(""),[coverage,setCoverage]=useState(""),[data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setData(null);setError(null);void searchAdminContentSafetyAlerts({p_severity:severity||null,p_status:status||null,p_category:category||null,p_target_type:target||null,p_source_type:source||null,p_coverage:coverage||null,p_limit:50}).then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar Content Safety")});return()=>{active=false}},[severity,status,category,target,source,coverage,nonce]);
  if(error)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;
  if(!data)return <LoadingState label="Cargando cola de Content Safety…"/>;
  const items=asRows(data.items),stats=asRecord(data.stats),activeRules=Number(data.active_rule_count)||0;
  return <><div className="page-heading"><div><p className="eyebrow">TRUST &amp; SAFETY</p><h2>Content Safety</h2><p>Detección automática para priorizar revisión humana. Una alerta no es una sanción.</p></div><Link className="secondary button-link" to="/content-safety/rules">Gestionar reglas</Link></div>
    {activeRules===0&&<AdminStatusPanel title="Motor textual listo · 0 reglas activas" detail="No se inventaron palabras prohibidas. Configura reglas derivadas de la política de Nelyon para comenzar a detectar coincidencias." tone="warning"/>}
    <section className="safety-stat-grid" aria-label="Resumen de alertas">{[{label:"Críticas",value:stats.critical_count},{label:"Altas",value:stats.high_count},{label:"Medias",value:stats.medium_count},{label:"Bajas",value:stats.low_count},{label:"Abiertas",value:stats.open_count},{label:"En revisión",value:stats.in_review_count}].map((item)=><article key={item.label}><span>{item.label}</span><strong>{humanValue(item.value,"0")}</strong></article>)}</section>
    <div className="filters"><select aria-label="Severidad" value={severity} onChange={(event)=>setSeverity(event.target.value)}><option value="">Toda severidad</option><option value="critical">Crítica</option><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></select><select aria-label="Estado de alerta" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">Todos los estados</option><option value="open">Abiertas</option><option value="in_review">En revisión</option><option value="resolved">Resueltas</option><option value="dismissed">Sin infracción</option></select><select aria-label="Categoría" value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">Toda categoría</option>{categories.map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Tipo de contenido" value={target} onChange={(event)=>setTarget(event.target.value)}><option value="">Todo contenido</option><option value="video">Video</option><option value="comment">Comentario</option><option value="story">Story</option><option value="live_message">Chat LIVE</option><option value="message">Mensaje reportado</option></select><select aria-label="Fuente" value={source} onChange={(event)=>setSource(event.target.value)}><option value="">Toda fuente</option><option value="text_rule">Regla textual</option><option value="user_reports">Reportes</option></select><select aria-label="Cobertura" value={coverage} onChange={(event)=>setCoverage(event.target.value)}><option value="">Toda cobertura</option><option value="complete">Completa</option><option value="incomplete">Incompleta</option><option value="pending">Pendiente</option><option value="failed">Fallida</option></select></div>
    {items.length===0?<EmptyState title="Sin alertas" detail={activeRules===0?"No hay reglas activas ni reportes que generen alertas.":"No hay coincidencias para estos filtros."}/>:<section className="table-panel"><table className="human-table safety-alert-table"><thead><tr><th>Prioridad</th><th>Contenido</th><th>Autor</th><th>Señal</th><th>Impacto</th><th>Cobertura</th><th>Estado</th></tr></thead><tbody>{items.map((item)=>{const coverageValue=asRecord(item.coverage);return <tr key={String(item.id)}><td><Link to={`/content-safety/${String(item.id)}`}><strong>{severityLabel(item.priority_bucket)} · {humanValue(item.priority_score)}</strong><small>{severityLabel(item.severity)} · {humanValue(item.category)}</small></Link></td><td><Link to={`/content-safety/${String(item.id)}`}><strong>{targetLabel(item.target_type)}</strong><span className="truncate">{humanValue(item.evidence_excerpt,"Sin extracto textual")}</span><small className="mono">{shortId(item.target_id)}</small></Link></td><td><AdminIdentity value={asRecord(item.author)} compact/></td><td>{humanValue(item.rule_label,item.source_type==="user_reports"?"Reportes de usuarios":"Detector textual")}</td><td><small>{humanValue(item.related_report_count,"0")} reportes · {humanValue(item.reach,"0")} alcance<br/>Warnings {humanValue(item.active_warning_count,"0")}/3</small></td><td><small>Texto {coverageLabel(coverageValue.text)}<br/>Audio {coverageLabel(coverageValue.audio)} · Visual {coverageLabel(coverageValue.visual)}</small></td><td><em className={`badge ${item.status==="open"?"warn":item.status==="resolved"?"success":""}`}>{statusLabel(item.status)}</em><small className="table-secondary">{formatDate(item.created_at)}</small></td></tr>})}</tbody></table></section>}
  </>;
}

export function AdminContentSafetyDetailPage(){
  const {id=""}=useParams(),{hasCapability}=useAdminAuth();const [detail,setDetail]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[note,setNote]=useState(""),[resolution,setResolution]=useState("reviewed"),[busy,setBusy]=useState(false),[nonce,setNonce]=useState(0);
  useEffect(()=>{let active=true;setDetail(null);setError(null);void getAdminContentSafetyAlert(id).then((value)=>{if(active)setDetail(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudo cargar la alerta")});return()=>{active=false}},[id,nonce]);
  const act=async(action:"take_review"|"dismiss"|"resolve")=>{if(action!=="take_review"&&note.trim().length<2)return setError("Indica una nota de al menos 2 caracteres.");setBusy(true);setError(null);try{await reviewAdminContentSafetyAlert({id,action,resolution:action==="resolve"?resolution:null,note:note.trim()||null,idempotencyKey:crypto.randomUUID()});setNote("");setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo revisar la alerta")}finally{setBusy(false)}};
  const retry=async()=>{const scan=asRecord(detail?.scan);setBusy(true);setError(null);try{await retryAdminContentSafetyScan({id:String(scan.id),idempotencyKey:crypto.randomUUID()});setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo reintentar el scan")}finally{setBusy(false)}};
  if(error&&!detail)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!detail)return <LoadingState label="Cargando alerta…"/>;
  const author=asRecord(detail.author),scan=asRecord(detail.scan),coverage=asRecord(scan.coverage),content=asRecord(detail.content),rule=asRecord(detail.rule),evidence=asRecord(detail.evidence),relatedReports=asRows(detail.related_reports),incomplete=[coverage.audio,coverage.visual].includes("not_configured");
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY · {severityLabel(detail.priority_bucket).toUpperCase()}</p><h2>{targetLabel(detail.target_type)} · {humanValue(detail.category)}</h2><p className="mono">{id}</p></div><div className="button-row"><em className={`badge ${detail.severity==="critical"||detail.severity==="high"?"warn":""}`}>{severityLabel(detail.severity)}</em><em className="badge">{statusLabel(detail.status)}</em></div></div>
    <div className="presentation-grid"><div className="presentation-stack"><section className="presentation-card"><header><h3>Contenido y evidencia</h3></header><p>{humanValue(content.summary,"Sin extracto disponible")}</p><AdminFactGrid><AdminFact label="Tipo" value={targetLabel(detail.target_type)}/><AdminFact label="Prioridad" value={`${humanValue(detail.priority_score)}/100`}/><AdminFact label="Detector" value={humanValue(rule.label,detail.source_type==="user_reports"?"Reportes de usuarios":"Señal automática")}/><AdminFact label="Versión detector" value={humanValue(scan.detector_version)}/><AdminFact label="Regla" value={humanValue(rule.code,"—")} mono/><AdminFact label="Confidence" value={detail.confidence===null||detail.confidence===undefined?"No disponible":humanValue(detail.confidence)}/></AdminFactGrid>{Array.isArray(evidence.matched_terms)&&<div className="safety-term-list">{evidence.matched_terms.map((term)=><em className="badge" key={String(term)}>{String(term)}</em>)}</div>}<div className="button-row"><Link className="button-link" to={String(content.path||"/content")}>Abrir contenido canónico</Link>{detail.target_type==="story"&&<Link className="secondary button-link" to={`/stories/${String(detail.target_id)}`}>Abrir Story</Link>}</div></section>
      <section className="presentation-card"><header><h3>Analysis coverage</h3></header><div className="status-list"><AdminStatusPanel title="Texto" detail={coverageLabel(coverage.text)} tone={coverageTone(coverage.text)}/><AdminStatusPanel title="Audio" detail={coverageLabel(coverage.audio)} tone={coverageTone(coverage.audio)}/><AdminStatusPanel title="Visual" detail={coverageLabel(coverage.visual)} tone={coverageTone(coverage.visual)}/><AdminStatusPanel title="Reportes" detail={coverageLabel(coverage.reports)} tone={coverageTone(coverage.reports)}/></div>{incomplete&&<p className="discipline-attention">El análisis automático no cubrió audio/visual. Esta alerta no certifica que el contenido sea seguro.</p>}</section>
      <section className="presentation-card"><header><h3>Reportes relacionados</h3><em className="badge">{relatedReports.length}</em></header>{relatedReports.length===0?<p className="muted-text">Sin reportes asociados.</p>:<div className="status-list">{relatedReports.map((report)=><AdminStatusPanel key={String(report.id)} title={humanValue(report.reason,"Reporte")} detail={`${statusLabel(report.status)} · ${formatDate(report.created_at)}`} tone={report.status==="pending"?"warning":"neutral"}/>)}</div>}<Link className="secondary button-link" to="/reports">Abrir Reports</Link></section></div>
      <aside className="presentation-stack"><section className="presentation-card"><header><h3>Autor</h3></header><AdminIdentity value={author}/><AdminFactGrid><AdminFact label="Warnings actuales" value={`${humanValue(detail.active_warning_count,"0")}/3`}/><AdminFact label="Alcance" value={humanValue(detail.reach,"0")}/><AdminFact label="Reportes pendientes" value={humanValue(detail.pending_report_count,"0")}/><AdminFact label="Reportes 15 min" value={humanValue(detail.reports_last_15m,"0")}/></AdminFactGrid>{typeof author.id==="string"&&<Link className="secondary button-link" to={`/users/${author.id}`}>Abrir usuario / disciplina F2</Link>}</section><section className="presentation-card"><header><h3>Scan</h3></header><AdminFactGrid><AdminFact label="Estado" value={humanValue(scan.status)}/><AdminFact label="Motivo" value={humanValue(scan.requested_reason)}/><AdminFact label="Intentos" value={humanValue(scan.attempt_count)}/><AdminFact label="Iniciado" value={formatDate(scan.started_at)}/><AdminFact label="Completado" value={formatDate(scan.completed_at)}/><AdminFact label="Error" value={humanValue(scan.last_error_code)}/><AdminFact label="Scan ID" value={shortId(scan.id)} mono/></AdminFactGrid>{typeof scan.media_source_scan_id==="string"&&<p className="muted-text">La Story reutiliza el scan del video canónico: <span className="mono">{shortId(scan.media_source_scan_id)}</span></p>}{scan.status==="failed"&&hasCapability("content.items.moderate")&&<button className="secondary" disabled={busy} onClick={()=>void retry()}>Reintentar scan</button>}</section></aside></div>
    {hasCapability("content.items.moderate")&&detail.status!=="resolved"&&detail.status!=="dismissed"&&<section className="detail-card"><h3>Revisión humana</h3><p className="muted-text">Estas acciones solo cambian el estado de la alerta. No ocultan contenido, no emiten warnings y no suspenden cuentas.</p><textarea aria-label="Nota de revisión" placeholder="Nota obligatoria para cerrar" value={note} onChange={(event)=>setNote(event.target.value)}/><select aria-label="Resultado" value={resolution} onChange={(event)=>setResolution(event.target.value)}><option value="reviewed">Revisado</option><option value="content_action_taken">Acción de contenido realizada por autoridad canónica</option><option value="user_action_taken">Acción de usuario realizada por autoridad F2</option></select><div className="button-row">{detail.status==="open"&&<button disabled={busy} onClick={()=>void act("take_review")}>Tomar para revisión</button>}<button className="secondary" disabled={busy} onClick={()=>void act("dismiss")}>Sin infracción</button><button disabled={busy} onClick={()=>void act("resolve")}>Marcar resuelto</button></div>{error&&<p role="alert">{error}</p>}</section>}
  </>;
}

function ContentSafetyRuleRow({rule,canManage,onSaved}:{rule:Record<string,unknown>;canManage:boolean;onSaved:()=>void}){
  const [severity,setSeverity]=useState(String(rule.severity||"medium")),[selectedScopes,setSelectedScopes]=useState<string[]>(Array.isArray(rule.scopes)?rule.scopes.map(String):[]),[enabled,setEnabled]=useState(rule.enabled===true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const save=async()=>{if(selectedScopes.length===0)return setError("Selecciona al menos un scope.");setBusy(true);setError(null);try{await updateAdminContentSafetyRule({id:String(rule.id),severity,scopes:selectedScopes,enabled,idempotencyKey:crypto.randomUUID()});onSaved()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo actualizar la regla")}finally{setBusy(false)}};
  return <tr><td><strong>{humanValue(rule.label)}</strong><small className="mono">{humanValue(rule.code)} · v{humanValue(rule.version)}</small></td><td>{humanValue(rule.category)}</td><td>{humanValue(rule.detector_type)}</td><td>{humanValue(rule.pattern)}</td><td><select aria-label={`Severidad ${humanValue(rule.label)}`} value={severity} disabled={!canManage||busy} onChange={(event)=>setSeverity(event.target.value)}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select></td><td><fieldset className="safety-scope-picker compact" disabled={!canManage||busy}><legend className="sr-only">Scopes {humanValue(rule.label)}</legend>{scopes.map((scope)=><label key={scope}><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={()=>setSelectedScopes((current)=>current.includes(scope)?current.filter((value)=>value!==scope):[...current,scope])}/>{scope}</label>)}</fieldset></td><td><label className="checkbox-row"><input type="checkbox" checked={enabled} disabled={!canManage||busy} onChange={(event)=>setEnabled(event.target.checked)}/>Activa</label>{canManage&&<button className="secondary" disabled={busy} onClick={()=>void save()}>Guardar</button>}{error&&<small role="alert">{error}</small>}</td></tr>;
}

export function AdminContentSafetyRulesPage(){
  const {hasCapability}=useAdminAuth();const [data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0),[busy,setBusy]=useState(false),[label,setLabel]=useState(""),[category,setCategory]=useState("other"),[detector,setDetector]=useState("keyword"),[pattern,setPattern]=useState(""),[severity,setSeverity]=useState("medium"),[selectedScopes,setSelectedScopes]=useState<string[]>(["video_caption"]),[enabled,setEnabled]=useState(false);
  useEffect(()=>{let active=true;setData(null);setError(null);void searchAdminContentSafetyRules().then((value)=>{if(active)setData(value)}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"No se pudieron cargar las reglas")});return()=>{active=false}},[nonce]);
  const create=async()=>{if(label.trim().length<2||pattern.trim().length<1||selectedScopes.length===0)return setError("Completa nombre, patrón y al menos un scope.");setBusy(true);setError(null);try{await createAdminContentSafetyRule({label:label.trim(),category,detectorType:detector,pattern:pattern.trim(),severity,scopes:selectedScopes,enabled,idempotencyKey:crypto.randomUUID()});setLabel("");setPattern("");setEnabled(false);setNonce((value)=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo crear la regla")}finally{setBusy(false)}};
  if(error&&!data)return <ErrorState message={error} onRetry={()=>setNonce((value)=>value+1)}/>;if(!data)return <LoadingState label="Cargando reglas…"/>;const rules=asRows(data.items);
  return <><div className="page-heading"><div><p className="eyebrow">CONTENT SAFETY</p><h2>Reglas</h2><p>Las reglas son configuradas por administradores humanos; F4 no inventa política.</p></div><Link className="secondary button-link" to="/content-safety">Volver a alertas</Link></div>{rules.length===0?<AdminStatusPanel title="0 reglas configuradas" detail="El motor está listo, pero no existe una lista canónica de palabras o frases aprobada para activar automáticamente." tone="warning"/>:<section className="table-panel"><table className="human-table"><thead><tr><th>Regla</th><th>Categoría</th><th>Detector</th><th>Patrón</th><th>Severidad</th><th>Scopes</th><th>Estado</th></tr></thead><tbody>{rules.map((rule)=><ContentSafetyRuleRow key={String(rule.id)} rule={rule} canManage={hasCapability("content.items.moderate")} onSaved={()=>setNonce((value)=>value+1)}/>)}</tbody></table></section>}
    {hasCapability("content.items.moderate")&&<section className="detail-card safety-rule-form"><h3>Crear regla</h3><div className="filters"><input aria-label="Nombre de regla" placeholder="Nombre" value={label} onChange={(event)=>setLabel(event.target.value)}/><select aria-label="Categoría de regla" value={category} onChange={(event)=>setCategory(event.target.value)}>{categories.map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Detector" value={detector} onChange={(event)=>setDetector(event.target.value)}><option value="keyword">Keyword</option><option value="phrase">Phrase</option></select><select aria-label="Severidad de regla" value={severity} onChange={(event)=>setSeverity(event.target.value)}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div><input aria-label="Palabra o frase" placeholder="Palabra o frase derivada de política aprobada" value={pattern} onChange={(event)=>setPattern(event.target.value)}/><fieldset className="safety-scope-picker"><legend>Scopes</legend>{scopes.map((scope)=><label key={scope}><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={()=>setSelectedScopes((current)=>current.includes(scope)?current.filter((value)=>value!==scope):[...current,scope])}/>{scope}</label>)}</fieldset><label className="checkbox-row"><input type="checkbox" checked={enabled} onChange={(event)=>setEnabled(event.target.checked)}/>Habilitar al crear</label><div className="button-row"><button disabled={busy} onClick={()=>void create()}>Crear regla</button></div>{error&&<p role="alert">{error}</p>}<small>Cambiar un patrón requiere crear una nueva regla; las reglas usadas no se eliminan físicamente.</small></section>}
  </>;
}
