import { useEffect,useMemo,useState,type FormEvent } from "react";
import { Link,useSearchParams } from "react-router-dom";
import { EmptyState,ErrorState,LoadingState } from "../components/PageState";
import { formatBdag,formatDate,searchOrders,type AdminRange,type OrderCursor,type OrderPage } from "../lib/adminApi";

export function MarketplaceOrdersPage(){const [params,setParams]=useSearchParams();const query=params.get("q")??"",status=params.get("status")??"",range=(params.get("range")??"30d")as AdminRange,source=params.get("source")??"";const [draft,setDraft]=useState(query),[page,setPage]=useState<OrderPage|null>(null),[error,setError]=useState<string|null>(null),[cursors,setCursors]=useState<Array<OrderCursor|undefined>>([undefined]),[index,setIndex]=useState(0),[nonce,setNonce]=useState(0);const key=useMemo(()=>`${query}|${status}|${range}|${source}`,[query,status,range,source]);useEffect(()=>{setCursors([undefined]);setIndex(0)},[key]);useEffect(()=>{let active=true;setPage(null);setError(null);void searchOrders({query,status,range,sourceSurface:source,cursor:cursors[index],limit:50}).then((value)=>{if(active)setPage(value)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[query,status,range,source,cursors,index,nonce]);const update=(name:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(name,value);else next.delete(name);setParams(next)};const submit=(e:FormEvent)=>{e.preventDefault();update("q",draft)};return <>
  <div className="page-heading"><div><p className="eyebrow">OPERACIONES</p><h2>Pedidos</h2><p>Búsqueda paginada sobre el historial canónico.</p></div></div>
  <form className="filters" onSubmit={submit}><label className="search"><span>⌕</span><input aria-label="Buscar pedidos" placeholder="ID, número, comprador o tienda" value={draft} onChange={(e)=>setDraft(e.target.value)}/></label><select aria-label="Estado" value={status} onChange={(e)=>update("status",e.target.value)}><option value="">Todos los estados</option>{["confirmed","processing","shipped","delivered","refunded","partially_refunded","cancelled","expired"].map((x)=><option key={x}>{x}</option>)}</select><select aria-label="Origen" value={source} onChange={(e)=>update("source",e.target.value)}><option value="">Todos los orígenes</option>{["creator_showcase","feed","reel","direct_creator_link","live"].map((x)=><option key={x}>{x}</option>)}</select><select aria-label="Rango" value={range} onChange={(e)=>update("range",e.target.value)}><option value="7d">7 días</option><option value="30d">30 días</option><option value="90d">90 días</option><option value="all">Todo</option></select><button>Buscar</button></form>
  {error?<ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>:!page?<LoadingState label="Buscando pedidos…"/>:page.orders.length===0?<EmptyState title="Sin resultados" detail="Ajusta los filtros para buscar otros pedidos."/>:<section className="table-panel"><div className="orders-table" role="table"><div className="table-head" role="row"><span>Pedido</span><span>Comprador</span><span>Tienda</span><span>Importe</span><span>Pago / entrega</span><span>Estado</span></div>{page.orders.map((order)=><Link className="table-row" role="row" to={`/marketplace/orders/${order.id}`} key={order.id}><span><strong>{order.order_number}</strong><small>{formatDate(order.created_at)}</small></span><span>{order.buyer_name}</span><span><strong>{order.store_name}</strong><small>{order.seller_name}</small></span><span>{formatBdag(order.amount)}</span><span><small>{order.payment_status??"Sin pago"}</small><small>{order.fulfillment_status??"Sin envío"}</small></span><span><em className={`badge ${order.dispute_open||order.reversed?"warn":""}`}>{order.status}</em>{order.creator_commerce&&<small>{order.source_surfaces.join(", ")}</small>}</span></Link>)}</div><footer className="pagination"><button className="secondary" disabled={index===0} onClick={()=>setIndex((x)=>x-1)}>Anterior</button><span>Página {index+1}</span><button className="secondary" disabled={!page.next_cursor} onClick={()=>{if(page.next_cursor){setCursors((old)=>[...old.slice(0,index+1),page.next_cursor??undefined]);setIndex((x)=>x+1)}}}>Siguiente</button></footer></section>}
  </>}
