import { useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { ErrorState,LoadingState } from "../components/PageState";
import { formatBdag,formatDate,getOrderDetail,type OrderDetail } from "../lib/adminApi";

const obj=(value:unknown)=>(value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null);const text=(v:unknown)=>v===null||v===undefined?"—":String(v);
export function MarketplaceOrderDetailPage(){const {orderId=""}=useParams();const [data,setData]=useState<OrderDetail|null>(null),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);useEffect(()=>{let active=true;setData(null);setError(null);void getOrderDetail(orderId).then((v)=>{if(active)setData(v)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Error")});return()=>{active=false}},[orderId,nonce]);if(error)return <ErrorState message={error} onRetry={()=>setNonce((x)=>x+1)}/>;if(!data)return <LoadingState label="Armando trazabilidad del pedido…"/>;const order=data.order,buyer=obj(data.buyer),seller=obj(data.seller),store=obj(data.store),payment=obj(data.payment),allocation=obj(data.payment_allocation),shipping=obj(data.shipping),shipment=obj(shipping?.shipment),settlement=obj(data.settlement),dispute=obj(data.dispute),reversal=obj(data.reversal);return <div className="detail"><Link to="/marketplace/orders" className="back-link">← Volver a pedidos</Link><section className="detail-hero"><div><p className="eyebrow">PEDIDO</p><h2>{text(order.order_number)}</h2><p>{formatDate(order.created_at)}</p></div><div><span className="badge">{text(order.status)}</span><strong>{formatBdag(order.total as string|number)}</strong></div></section>
  <div className="detail-grid"><Section title="Resumen"><Fact label="Comprador" value={text(buyer?.display_name||buyer?.username)}/><Fact label="Vendedor" value={text(seller?.display_name)}/><Fact label="Tienda" value={text(store?.name)}/><Fact label="Moneda" value={text(order.currency)}/></Section><Section title="Pago"><Fact label="Estado" value={text(payment?.status)}/><Fact label="Bruto" value={payment?formatBdag(payment.gross_amount as string|number):"—"}/><Fact label="Pagado" value={formatDate(payment?.paid_at)}/><Fact label="Asignación" value={text(allocation?.status)}/></Section><Section title="Envío"><Fact label="Estado" value={text(shipment?.status)}/><Fact label="Transportista" value={text(shipment?.carrier_name)}/><Fact label="Tracking" value={text(shipment?.tracking_number)}/><Fact label="Entregado" value={formatDate(shipment?.delivered_at)}/></Section></div>
  <Section title="Artículos"><div className="item-list">{data.items.map((item)=><article className="item-card" key={text(item.id)}><div><strong>{text(item.product_title)}</strong><small>{text(item.variant_title||item.sku)} · {text(item.quantity)} unidad(es)</small></div><strong>{formatBdag(item.line_total as string|number)}</strong>{obj(item.creator)&&<div className="creator-trace"><span>Creador: {text(obj(item.creator)?.creator_display_name||obj(item.creator)?.creator_username)}</span><span>Origen: {text(obj(item.creator)?.source_surface)}</span><span>GMV de línea: {formatBdag(obj(item.creator)?.item_gmv as string|number)}</span><span>Comisión: {formatBdag(obj(item.creator)?.allocation_amount as string|number)}</span></div>}</article>)}</div></Section>
  {data.creator_allocations.length>0&&<Section title="Creator Commerce"><Trace rows={data.creator_allocations} fields={["creator_user_id","order_item_id","item_gmv","commission_amount"]}/></Section>}
  {settlement&&<Section title="Liquidación"><Fact label="Estado" value={text(settlement.status)}/><Fact label="Vendedor" value={formatBdag(settlement.seller_net_amount as string|number)}/><Fact label="Plataforma" value={formatBdag(settlement.platform_fee_amount as string|number)}/><Fact label="Creadores" value={formatBdag(settlement.creator_commission_amount as string|number)}/><Trace rows={data.settlement_legs} fields={["leg_type","beneficiary_user_id","amount","status"]}/></Section>}
  {(dispute||reversal)&&<Section title="Disputa / reversión">{dispute&&<><Fact label="Disputa" value={text(dispute.status)}/><Fact label="Motivo" value={text(dispute.reason_code)}/></>}{reversal&&<><Fact label="Reversión" value={formatBdag(reversal.gross_amount as string|number)}/><Fact label="Fecha" value={formatDate(reversal.created_at)}/><Trace rows={data.reversal_legs} fields={["leg_type","beneficiary_user_id","original_amount","reversal_amount"]}/></>}</Section>}
  <Section title="Cronología"><div className="timeline">{data.timeline.length===0?<p className="muted-text">Sin eventos adicionales.</p>:data.timeline.map((event)=><div key={text(event.id)}><span/><strong>{text(event.event_type)}</strong><small>{formatDate(event.created_at)}</small></div>)}</div></Section>
  </div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="panel detail-section"><div className="panel-title"><h3>{title}</h3></div>{children}</section>}
function Fact({label,value}:{label:string;value:string}){return <div className="fact"><span>{label}</span><strong>{value}</strong></div>}
function Trace({rows,fields}:{rows:Array<Record<string,unknown>>;fields:string[]}){return <div className="trace-table">{rows.map((row,index)=><div key={text(row.id??index)}>{fields.map((field)=><span key={field}><small>{field.replaceAll("_"," ")}</small>{text(row[field])}</span>)}</div>)}</div>}
