import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';

const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const migration = read('supabase/migrations/20260721120000_terminal_voip_activation_cutoff.sql');
const outbox = read('supabase/migrations/20260713140000_terminal_call_push_outbox.sql');
const dispatcher = read('supabase/functions/dispatch-call-push-deliveries/index.ts');
const swift = read('modules/onspace-callkit/ios/OnSpaceCallCoordinator.swift');

const transpiled = ts.transpileModule(dispatcher, {
  compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  reportDiagnostics: true,
});
assert.deepEqual(
  (transpiled.diagnostics ?? []).filter(item => item.category === ts.DiagnosticCategory.Error),
  [],
  'terminal dispatcher must transpile without syntax diagnostics',
);

const terminalEvents = [
  'call_cancelled',
  'call_expired',
  'call_rejected',
  'call_ended',
  'call_answered_elsewhere',
];

// Authoritative, auditable and idempotent cutoff/classification.
assert.match(migration, /terminal_voip_activation_cutoff timestamptz/);
assert.match(migration, /terminal_voip_stale_classified_at timestamptz/);
assert.match(migration, /terminal_voip_pre_activation_stale_count integer/);
assert.match(migration, /coalesce\([\s\S]*terminal_voip_activation_cutoff[\s\S]*statement_timestamp\(\)/);
assert.match(migration, /cpd\.created_at < cutoff\.activated_at/);
assert.match(migration, /status = 'skipped'/);
assert.match(migration, /error_code = 'PRE_ACTIVATION_STALE'/);
assert.match(migration, /error_message = 'terminal delivery predates activation cutoff'/);
assert.doesNotMatch(migration, /delete\s+from\s+public\.call_push_deliveries/i);
assert.doesNotMatch(migration, /set[\s\S]{0,160}payload\s*=/i,
  'classification must not alter immutable payloads');

// Claim is post-cutoff, terminal-only, capable-device-only and fenced.
assert.match(migration, /cpd\.created_at >= v_cutoff/);
assert.match(migration, /cpd\.presentation_version = 0/);
assert.match(migration, /cpd\.error_code is distinct from 'PRE_ACTIVATION_STALE'/);
assert.match(migration, /cd\.terminal_voip_version >= 1/);
assert.match(migration, /cpd\.status = 'pending'[\s\S]*cpd\.next_attempt_at is null or cpd\.next_attempt_at <= clock_timestamp/);
assert.match(migration, /cpd\.status = 'failed'[\s\S]*cpd\.next_attempt_at is not null/,
  'permanent failures must not loop');
assert.match(migration, /cpd\.status = 'processing'[\s\S]*interval '60 seconds'/,
  'expired processing ownership must be recoverable');
assert.match(migration, /for update of cpd skip locked/);
assert.match(migration, /attempt_count = cpd\.attempt_count \+ 1/);
assert.match(migration, /payload jsonb,\s+attempt_count integer/);
assert.doesNotMatch(migration, /incoming_call/,
  'terminal cutoff migration must not claim or classify incoming D4D');

// Flag remains the first gate; worker uses expected-attempt fencing and
// distinguishes retryable/permanent APNs failures.
const flagGate = dispatcher.indexOf("CALL_TERMINAL_VOIP_ENABLED");
const claimCall = dispatcher.indexOf(".rpc('claim_pending_call_push_deliveries'");
assert.ok(flagGate >= 0 && claimCall > flagGate, 'flag=false must return before claim');
assert.match(dispatcher, /\.eq\('status', 'processing'\)\s*\.eq\('attempt_count', delivery\.attempt_count\)/);
assert.match(dispatcher, /isRetryableApnsResult/);
assert.match(dispatcher, /result\.status === 0 \|\| result\.status === 429 \|\| result\.status >= 500/);
assert.match(dispatcher, /next_attempt_at: retryable \? new Date[\s\S]*: null/);
assert.match(dispatcher, /isInvalidApnsDeviceToken[\s\S]*voip_push_token: null, terminal_voip_version: 0/);
assert.match(dispatcher, /apns-id|deliveryId: delivery\.delivery_id/);
assert.match(dispatcher, /const BATCH_LIMIT = 25/);

// Every terminal payload is immutable, deduplicated and understood by Swift.
for (const event of terminalEvents) {
  assert.ok(outbox.includes(`'${event}'`), `${event} must be generated by the outbox`);
  assert.ok(dispatcher.includes(`'${event}'`), `${event} must be accepted by the dispatcher`);
  assert.ok(swift.includes(`"${event}"`), `${event} must be accepted by the native tombstone handler`);
}
assert.match(outbox, /jsonb_build_object\(\s*'type', v_event_type,\s*'call_id', v_call\.id::text,\s*'status', v_status,\s*'reason', v_reason,\s*'timestamp'/);
assert.match(outbox, /on conflict \(call_id, device_id, event_type, provider\) do nothing/);
assert.match(swift, /persistTerminalTombstone\(callId: callId, eventType: event\)/);
assert.match(swift, /if hasTerminalTombstone\(callId: callIdRaw\)[\s\S]*finishOnce\(\)/,
  'a late incoming push must not resurrect a tombstoned call');

// Deterministic cutoff/claim model.
const cutoff = 1_000;
const eligible = row => terminalEvents.includes(row.event) &&
  row.provider === 'apns_voip' && row.presentationVersion === 0 &&
  row.createdAt >= cutoff && row.capability >= 1 && row.attempts < 3 &&
  row.error !== 'PRE_ACTIVATION_STALE' && (
    (row.status === 'pending' && (row.nextAttemptAt == null || row.nextAttemptAt <= 2_000)) ||
    (row.status === 'failed' && row.nextAttemptAt != null && row.nextAttemptAt <= 2_000) ||
    (row.status === 'processing' && row.lastAttemptAt < 2_000 - 60)
  );

const base = {
  event: 'call_ended', provider: 'apns_voip', presentationVersion: 0,
  createdAt: 1_001, capability: 1, attempts: 0, error: null,
  status: 'pending', nextAttemptAt: null, lastAttemptAt: 0,
};
assert.equal(eligible({ ...base, createdAt: 999 }), false);
assert.equal(eligible(base), true);
assert.equal(eligible({ ...base, event: 'incoming_call' }), false);
assert.equal(eligible({ ...base, error: 'PRE_ACTIVATION_STALE' }), false);
assert.equal(eligible({ ...base, status: 'failed', nextAttemptAt: null }), false);
assert.equal(eligible({ ...base, status: 'failed', nextAttemptAt: 1_500 }), true);
assert.equal(eligible({ ...base, status: 'processing', lastAttemptAt: 1_000 }), true);
assert.equal(eligible({ ...base, status: 'sent' }), false);

const rows = Array.from({ length: 17 }, (_, index) => ({ id: index, ...base, createdAt: 999 }));
const classified = rows.map(row => row.createdAt < cutoff
  ? { ...row, status: 'skipped', error: 'PRE_ACTIVATION_STALE' }
  : row);
assert.equal(classified.length, 17, 'classification preserves all historical rows');
assert.equal(classified.filter(row => row.error === 'PRE_ACTIVATION_STALE').length, 17);

console.log('IOS-C Block 4 terminal cutoff tests: PASS');
