import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
const sql=readFileSync(new URL('../supabase/migrations/20260810130000_marketplace_ads_delivery_eligibility_clock.sql',import.meta.url),'utf8');
const corrective=readFileSync(new URL('../supabase/migrations/20260810140000_complete_marketplace_ads_eligibility_transitions.sql',import.meta.url),'utf8');
test('Ads eligibility clock is server authoritative and bounded',()=>{assert.match(sql,/clock_timestamp\(\)/);assert.match(sql,/least\(p_at_time,c\.ends_at\)/);assert.match(sql,/greatest\(c\.eligibility_checkpoint_at,c\.starts_at/);assert.match(sql,/for update/)});
test('Ads eligibility covers every delivery authority',()=>{for(const token of['marketplace_sellers','marketplace_stores','products','marketplace_product_variants','marketplace_inventory_levels','on_hand-l.reserved>0'])assert.match(sql,new RegExp(token))});
test('Ads eligibility hooks capture reservation boundaries without money movement',()=>{assert.match(sql,/old\.on_hand-old\.reserved>0/);assert.match(sql,/new\.on_hand-new\.reserved>0/);for(const token of['ledger_debit','ledger_credit','spend_marketplace_ad_budget','insert into public.financial_transactions'])assert.doesNotMatch(sql,new RegExp(token))});
test('Ads eligibility reconciliation rejects impossible clock state',()=>{assert.match(sql,/paused_eligible/);assert.match(sql,/terminal_eligible/);assert.match(sql,/unfunded_elapsed/)});
test('scheduled campaigns accumulate from start only while underlying state stays healthy',()=>{assert.match(corrective,/eligibility_reason='scheduled'and next_state/);assert.ok(corrective.indexOf("seller_restricted")<corrective.indexOf("'scheduled'::text"))});
test('variant and inventory inserts establish an exact eligibility boundary',()=>{assert.match(corrective,/marketplace_ad_variant_clock_after_insert after insert/);assert.match(corrective,/marketplace_ad_inventory_clock_after_insert after insert/)});
