import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read=(path)=>readFileSync(path,"utf8"),migration=read("supabase/migrations/20260811029000_marketplace_admin_operations_core.sql"),closure=read("supabase/migrations/20260811030000_marketplace_admin_operations_closure.sql"),api=read("apps/admin-web/src/lib/adminApi.ts"),closureWeb=read("apps/admin-web/src/tests/operationsClosure.test.tsx"),app=read("apps/admin-web/src/App.tsx"),shell=read("apps/admin-web/src/layout/AdminShell.tsx"),proof=read("scripts/prove-marketplace-admin-operations-core.mjs"),auditor=read("scripts/audit-marketplace-b8b-remote.mjs"),appConfig=read("app.json");

test("B8B is a forward-only Marketplace admin-web phase",()=>{assert.match(migration,/marketplace_admin_operations_core/);assert.match(app,/marketplace\/disputes/);assert.match(app,/marketplace\/sellers/);assert.match(app,/marketplace\/products/);assert.match(shell,/Operaciones internas/);assert.doesNotMatch(app,/B8C|B8D/)});
test("all privileged mutation entrypoints derive and require the B8S admin actor",()=>{for(const name of["admin_resolve_marketplace_dispute","admin_moderate_marketplace_seller","admin_moderate_marketplace_product"]){const start=migration.indexOf(`function public.${name}`),body=migration.slice(start,migration.indexOf("end$$",start));assert(start>0);assert.match(body,/marketplace_require_admin\(\)/);assert.doesNotMatch(body,/p_(actor|admin|resolver)_id/)}assert.match(migration,/set search_path=pg_catalog,public/)});
test("dispute wrapper reuses canonical financial authority and never calculates finance",()=>{const start=migration.indexOf("function public.admin_resolve_marketplace_dispute"),body=migration.slice(start,migration.indexOf("end$$",start));assert.match(body,/resolve_marketplace_dispute\(v_actor/);assert.doesNotMatch(body,/ledger_(debit|credit)|commission_amount\s*[:=]|gross_amount\s*[*]/);assert.match(body,/p_outcome not in\('manual_review','refund_buyer','release_seller','reject_claim'\)/)});
test("seller wrapper reuses canonical moderation authorities and blocks self moderation",()=>{for(const fn of["approve_marketplace_seller","reject_marketplace_seller","suspend_marketplace_seller","restore_marketplace_seller"])assert.match(migration,new RegExp(fn));assert.match(migration,/v_actor=p_seller_id/)});
test("product authority only moderates eligibility",()=>{const start=migration.indexOf("function public.admin_moderate_marketplace_product"),body=migration.slice(start,migration.indexOf("end$$",start));assert.match(body,/moderation_status/);assert.match(body,/then'paused'/);assert.doesNotMatch(body,/price\s*=|stock\s*=|commission|inventory_levels/)});
test("audit is server-written immutable and idempotency safe",()=>{assert.match(migration,/create table public.marketplace_admin_action_audit/);assert.match(migration,/unique\(actor_id,idempotency_key\)/);assert.match(migration,/marketplace_admin_action_audit_immutable/);assert.match(migration,/revoke all on public.marketplace_admin_action_audit from public,anon,authenticated/);assert.match(proof,/audit_insert:false,audit_update:false,audit_delete:false/)});
test("read projections are null-safe bounded keyset RPCs",()=>{assert.equal((closure.match(/p_limit is null or p_limit<1 or p_limit>100/g)??[]).length,3);assert.doesNotMatch(closure,/p_limit not between/);assert.match(closure,/p_limit integer default 50/);assert.match(closure,/\(d.created_at,d.id\)<\(p_cursor_created_at,p_cursor_id\)/);assert.match(closure,/\(s.created_at,s.user_id\)<\(p_cursor_created_at,p_cursor_id\)/);assert.match(closure,/\(p.created_at,p.id\)<\(p_cursor_created_at,p_cursor_id\)/)});
test("reason contracts persist every accepted value without truncation",()=>{assert.match(closure,/char_length\(reason_code\)between 2 and 500/);assert.match(migration,/char_length\(v_reason\)not between 2 and 100/);assert.equal((migration.match(/char_length\(v_reason\)not between 2 and 500/g)??[]).length,2);assert.match(proof,/dispute100Accepted/);assert.match(proof,/seller500Accepted/);assert.match(proof,/product500Accepted/);assert.match(proof,/overLimitAuditRows:0/)});
test("web deeply validates dispute receipts and submits no financial fields",()=>{for(const marker of["searchDisputes","validateDisputeDetail","validateDisputeOperationReceipt","validateFinalFinancialResult","searchSellers","validateSellerDetail","searchProducts","validateProductDetail","resolveDispute","moderateSeller","moderateProduct"])assert.match(api,new RegExp(marker));for(const marker of["intermediateReceipt","finalReceipt","malformed intermediate","malformed final UUID, money, timestamp, and allocation","preserves retry idempotency","maxReasonLength"])assert.match(closureWeb,new RegExp(marker));assert.doesNotMatch(api,/p_(gross|amount|bps|creator|seller_net|ledger)/)});
test("proof covers security, limits, reasons, finance, real concurrency, reconciliation and cleanup",()=>{for(const marker of["anonymousDenied","metadataForgeryDenied","nullRejected22023","oneHundredOneRejected22023","dispute101Rejected","seller501Rejected","product501Rejected","overLimitStateUnchanged","heldRefundCanonical","releaseSellerCanonical","rejectClaimNoMoney","manualReviewNoMoney","sameKeyIdempotent","simultaneousConflictingFinalOutcomes","conflictingFinalOutcomeProtected","exactlyOneCanonicalDecision","noPartialFinancialState","selfModerationDenied","publicEligibilityProtected","appendOnly","allZero","fixtures"])assert.match(proof,new RegExp(marker));assert.match(proof,/new Client/g);assert.match(proof,/Promise\.allSettled/);assert.match(proof,/B8B_PROOF_REQUIRES_DISPOSABLE_DATABASE/)});
test("C1 remains Build 22 and does not start B8C or B8D",()=>{assert.match(appConfig,/"buildNumber": "22"/);assert.doesNotMatch(app+closure+closureWeb,/B8C|B8D/)});
test("remote auditor is read-only and checks C1 contracts plus inherited grants",()=>{for(const marker of["--expect-pre-b8b-c1","--require-b8b-c1","20260811029000","20260811030000","disputes_limit_null_safe","sellers_limit_null_safe","products_limit_null_safe","audit_reason_500","audit_client_write_denied"])assert.match(auditor,new RegExp(marker));assert.doesNotMatch(auditor,/insert into|update public|delete from/)});
