import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';const sql=readFileSync(new URL('../supabase/migrations/20260810100000_marketplace_ads_financial_authority.sql',import.meta.url),'utf8');const reconciliation=readFileSync(new URL('../supabase/migrations/20260810120000_complete_marketplace_ads_financial_audit.sql',import.meta.url),'utf8');
test('ads uses isolated prepaid accounts',()=>{assert.match(sql,/marketplace_ads_escrow/);assert.match(sql,/marketplace_ads_revenue/);assert.doesNotMatch(sql,/ensure_marketplace_escrow_account/)});
test('funding is atomic, locked and idempotent',()=>{assert.match(sql,/activate_marketplace_ad_campaign/);assert.match(sql,/for update/);assert.match(sql,/funding_idempotency_key/);assert.match(sql,/ledger_debit\(tx,seller_account/);assert.match(sql,/ledger_credit\(tx,escrow_account/)});
test('spend is internal, exact and bounded',()=>{assert.match(sql,/spend_marketplace_ad_budget/);assert.match(sql,/auth\.role\(\)<>'service_role'/);assert.match(sql,/if amount>remaining/);assert.match(sql,/then'exhausted'/)});
test('release is terminal, idempotent and zeroes remaining',()=>{assert.match(sql,/release_marketplace_ad_unused_budget/);assert.match(sql,/marketplace_ad_not_releasable/);assert.match(sql,/released_bdag=released_bdag\+amount/)});
test('financial events are immutable and reconciled',()=>{assert.match(sql,/marketplace_ad_financial_events_immutable/);assert.match(sql,/funding_reconciliation/);assert.match(sql,/escrow_liability_difference/)});
test('reconciliation proves directional accounts and event transaction identity',()=>{for(const token of['funding_unexpected_entries','spend_unexpected_entries','release_unexpected_entries','release_wrong_recipient','event_transaction_mismatches'])assert.match(reconciliation,new RegExp(token));assert.match(reconciliation,/destination_owner is distinct from seller_id/);assert.match(reconciliation,/reference_id is distinct from campaign_id::text/)});
test('reconciliation audits transaction orphans and real campaign accounting',()=>{for(const token of['orphan_ads_transactions','orphan_ads_events','fund_transaction_event_count_difference','campaign_accounting_mismatches'])assert.match(reconciliation,new RegExp(token));assert.match(reconciliation,/coalesce\(e\.spend_amount,0\)<>c\.spent_bdag/);assert.match(reconciliation,/coalesce\(e\.fund_amount,0\)<>c\.total_budget_bdag/)});
test('pause and resume never move ledger funds',()=>{const transitions=sql.slice(sql.indexOf('pause_marketplace_ad_campaign'),sql.indexOf('finalize_expired_marketplace_ad_campaigns'));assert.doesNotMatch(transitions,/ledger_(debit|credit)/)});
