import assert from 'node:assert/strict';import test from 'node:test';import {readFileSync} from 'node:fs';
const service=readFileSync('services/marketplaceOrderService.ts','utf8');const checkout=readFileSync('app/checkout.tsx','utf8');const reservation=readFileSync('app/checkout/reservation/[id].tsx','utf8');const cart=readFileSync('app/cart.tsx','utf8');const context=readFileSync('contexts/MarketplaceCartContext.tsx','utf8');const layout=readFileSync('app/_layout.tsx','utf8');

test('cart routes authenticated buyers to checkout and guests to login',()=>{assert.match(cart,/router\.push\('\/checkout'/);assert.match(cart,/Inicia sesión para reservar/);assert.match(cart,/router\.push\('\/login'/);});
test('service sends only variant identity and quantity as checkout items',()=>{assert.match(service,/p_items:items\.map\(item=>\(\{variant_id:item\.variantId,quantity:item\.quantity\}\)\)/);assert.doesNotMatch(service,/p_items:[^\n]*(?:price|seller|store|product|subtotal|currency)/);});
test('shipping is validated in memory and never persisted or included in diagnostics',()=>{assert.match(service,/validateShippingAddress/);assert.match(checkout,/field-level|nextErrors|setErrors/);assert.doesNotMatch(`${service}\n${checkout}`,/AsyncStorage|console\.error\([^\n]*(?:address|p_items|accessToken|userId|serviceRole)/i);});
test('submission lock and idempotency key survive uncertain retries',()=>{assert.match(checkout,/submitLockRef\.current/);assert.match(checkout,/idempotencyRef/);assert.match(checkout,/randomUUID\(\)/);assert.match(checkout,/fetchMyActiveCheckout\(\)/);assert.match(checkout,/finally\s*\{\s*submitLockRef\.current = false/);});
test('success removes only submitted cart keys and opens authoritative reservation',()=>{assert.match(context,/removeItems\(keys:string\[\]\)/);assert.match(checkout,/cart\.removeItems\(availableItems\.map\(\(item\) => item\.key\)\)/);assert.match(checkout,/checkout\/reservation\/\[id\]/);});
test('reservation screen keeps authoritative focus load, countdown and cancellation while payment is gated',()=>{assert.match(reservation,/useFocusEffect/);assert.match(reservation,/setInterval\(tick,\s*1000\)/);assert.match(reservation,/expireMarketplaceCheckoutReservations/);assert.match(reservation,/Cancelar reserva/);assert.match(reservation,/Confirmar compra/);assert.match(reservation,/accessibilityState=\{\{ disabled: paying \|\| remaining <= 0 \}\}/);});
test('navigation registers only checkout routes and client performs no money mutation',()=>{assert.match(layout,/Stack\.Screen name="checkout"/);assert.match(layout,/checkout\/reservation\/\[id\]/);const client=`${service}\n${checkout}\n${reservation}`;assert.doesNotMatch(client,/atomic_ledger_transfer|ledger_entries|updateDAGBalance|USDT|payment_intent|stripe|blockchain/i);});
test('unknown RPC failures use safe diagnostics and are not mislabeled as connectivity failures',()=>{assert.match(service,/\{rpc,code:safeDiagnosticValue\(value\.code\),message:safeDiagnosticValue\(value\.message\),details:safeDiagnosticValue\(value\.details\),hint:safeDiagnosticValue\(value\.hint\)\}/);assert.match(service,/marketplace_order_transport/);assert.match(checkout,/No se pudo crear la reserva/);assert.match(checkout,/Ocurrió un error al validar la reserva/);assert.match(checkout,/code==='marketplace_order_transport'/);});
