import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,existsSync,readdirSync}from "node:fs";
import {join}from "node:path";

const root=process.cwd(),migration=readFileSync(join(root,"supabase/migrations/20260811031000_marketplace_admin_intelligence_ops.sql"),"utf8"),closure=readFileSync(join(root,"supabase/migrations/20260811032000_marketplace_admin_intelligence_closure.sql"),"utf8"),api=readFileSync(join(root,"apps/admin-web/src/lib/adminIntelligenceApi.ts"),"utf8"),pages=readFileSync(join(root,"apps/admin-web/src/pages/MarketplaceIntelligencePages.tsx"),"utf8"),webTests=readFileSync(join(root,"apps/admin-web/src/tests/intelligenceWeb.test.tsx"),"utf8"),app=readFileSync(join(root,"apps/admin-web/src/App.tsx"),"utf8"),shell=readFileSync(join(root,"apps/admin-web/src/layout/AdminShell.tsx"),"utf8"),proof=readFileSync(join(root,"scripts/prove-marketplace-admin-intelligence-ops.mjs"),"utf8"),auditor=readFileSync(join(root,"scripts/audit-marketplace-b8c-remote.mjs"),"utf8");
const rpcNames=["get_marketplace_admin_creator_commerce_overview","search_marketplace_admin_creators","get_marketplace_admin_creator_detail","search_marketplace_admin_promotions","get_marketplace_admin_promotion_detail","search_marketplace_admin_ads","get_marketplace_admin_ad_detail","get_marketplace_admin_health","search_marketplace_admin_activity"];

test("B8C is one forward-only admin intelligence migration",()=>{assert(existsSync(join(root,"supabase/migrations/20260811031000_marketplace_admin_intelligence_ops.sql")));assert(!readdirSync(join(root,"supabase/migrations")).some((name)=>name.startsWith("20260811031")&&name!=="20260811031000_marketplace_admin_intelligence_ops.sql"));for(const historical of["20260811027000_marketplace_admin_identity_hardening.sql","20260811028000_marketplace_admin_web_foundation.sql","20260811029000_marketplace_admin_operations_core.sql","20260811030000_marketplace_admin_operations_closure.sql"])assert(existsSync(join(root,"supabase/migrations",historical)))});
test("B8C-C1 is forward-only and preserves every frozen migration",()=>{assert(existsSync(join(root,"supabase/migrations/20260811032000_marketplace_admin_intelligence_closure.sql")));for(const historical of["20260811027000_marketplace_admin_identity_hardening.sql","20260811028000_marketplace_admin_web_foundation.sql","20260811029000_marketplace_admin_operations_core.sql","20260811030000_marketplace_admin_operations_closure.sql","20260811031000_marketplace_admin_intelligence_ops.sql"])assert(existsSync(join(root,"supabase/migrations",historical)))});
test("all B8C RPCs independently require frozen admin authority and fixed path",()=>{for(const name of rpcNames){const start=migration.indexOf(`function public.${name}`),next=migration.indexOf("create or replace function",start+30),body=migration.slice(start,next<0?migration.length:next);assert(start>=0,name);assert.match(body,/marketplace_require_admin\(\)/,name);assert.match(body,/set search_path=pg_catalog,public/,name);if(name!=="search_marketplace_admin_activity")assert.doesNotMatch(body,/p_(actor|admin)_id/,name);else assert.match(body,/a\.actor_id=p_actor_id/)}});
test("creator projections reuse item-level B7D truth and aggregate top surfaces",()=>{assert.match(migration,/marketplace_creator_commerce_analytics_facts/);assert.match(migration,/surface_totals as\(/);assert.match(migration,/group by f\.creator_user_id,f\.source_surface/);assert.match(migration,/sum\(commission_released\)-sum\(commission_reversed\)/);for(const surface of["creator_showcase","feed","reel","direct_creator_link","live"])assert(proof.includes(surface));assert.doesNotMatch(migration,/commission_generated\s*[:=].*\*/i)});
test("creator ranges exactly separate B7D sales, release, reversal, and engagement clocks",()=>{for(const name of["get_marketplace_admin_creator_commerce_overview","search_marketplace_admin_creators_v2","get_marketplace_admin_creator_detail"]){const start=closure.indexOf(`function public.${name}`),next=closure.indexOf("create or replace function",start+30),body=closure.slice(start,next<0?closure.length:next);assert(start>=0,name);assert.match(body,/v_end timestamptz:=clock_timestamp\(\)/);assert.match(body,/paid_at>=v_start/);assert.match(body,/paid_at<v_end/);assert.match(body,/released_at>=v_start/);assert.match(body,/released_at<v_end/);assert.match(body,/reversed_at>=v_start/);assert.match(body,/reversed_at<v_end/);assert.match(body,/occurred_at>=v_start/);assert.match(body,/occurred_at<v_end/);assert.doesNotMatch(body,/commission_released[^;]*paid_at>=v_start/);assert.doesNotMatch(body,/commission_reversed[^;]*paid_at>=v_start/)}assert.match(closure,/released-reversed|commission_released/);for(const marker of["oldSaleNewRelease7d","oldSaleNewReversal7d","currentSaleUnreleased","occurredAtEngagement","futureVEndExcluded","b7dSameCreatorRangeMatch","releaseOnlyCreatorMembership"])assert(proof.includes(marker))});
test("historical creator BPS is read from immutable attribution snapshots",()=>{assert.match(closure,/marketplace_order_item_creator_attributions a/);assert.match(closure,/a\.commission_bps historical_bps/);assert.match(api,/historical_bps/);assert.match(pages,/BPS históricos/);assert.match(proof,/preservedAfterOfferChange/);assert.match(proof,/multiCreatorHistoricalBps/);assert.doesNotMatch(closure+api,/historical_bps[^\n]*(attributed_gmv|commission_generated)\s*[/\*]/)});
test("promotion snapshots and canonical effective price are observational",()=>{assert.match(migration,/marketplace_effective_price/);assert.match(migration,/base_unit_price/);assert.match(migration,/discount_amount/);assert.doesNotMatch(migration,/update\s+public\.marketplace_product_promotions/i);assert.doesNotMatch(pages,/editar.*(precio|descuento)|guardar promoción/i)});
test("Ads financial authority remains inaccessible to authenticated admin",()=>{for(const name of["spend_marketplace_ad_budget","release_marketplace_ad_unused_budget","finalize_marketplace_ad_campaign_delivery","finalize_expired_marketplace_ad_campaigns"]){assert.match(migration,new RegExp(`revoke all on function[^;]*${name}`,"s"));assert.doesNotMatch(api,new RegExp(`rpc\\(["']${name}`))}assert.match(proof,/internalFinancialGrantsToAuthenticated/);assert.doesNotMatch(api,/p_(amount|budget|spend|release)/)});
test("all list projections are explicitly NULL-safe and keyset bounded",()=>{for(const name of["search_marketplace_admin_creators","search_marketplace_admin_promotions","search_marketplace_admin_ads","search_marketplace_admin_activity"]){const start=migration.indexOf(`function public.${name}`),next=migration.indexOf("create or replace function",start+30),body=migration.slice(start,next<0?migration.length:next);assert.match(body,/p_limit is null/);assert.match(body,/p_limit<1/);assert.match(body,/p_limit>100/);assert.match(body,/p_limit\+1/);assert.match(body,/next_cursor/);assert.doesNotMatch(body,/\boffset\b/i)}});
test("web performs deep runtime validation and controlled errors",()=>{for(const token of["validateCreatorOverview","validateCreatorDetail","validatePromotionPage","validatePromotionDetail","validateAdsPage","validateAdDetail","validateHealth","validateActivityPage"])assert(api.includes(token));for(const token of["uuid(","timestamp(","money(","int(","bool(","arr(","obj("])assert(api.includes(token));assert.doesNotMatch(api,/data\s+as\s+(Creator|Promotion|Ad|Health|Activity)/);assert.match(pages,/ErrorState/)});
test("required creator, promotion, Ads, health and activity contracts reject malformed payloads",()=>{for(const token of["surfaces","promotionTypes","promotionStates","promotionStatuses","adStatuses","adEligibilityReasons","adFinancialEventTypes","adEventTypes","validateHealthCounters"])assert(api.includes(token));for(const phrase of["required count","invalid Creator surface","historical BPS and missing order UUID","release and reversal timestamps","Promotions missing value","Promotion snapshot money","Ads missing eligibility boolean","Ads delivery","Ads finalization","Ads financial and delivery events","string and boolean values for numeric Health counters","Health attention severity","Activity cursor and UUID"])assert(webTests.includes(phrase),phrase)});
test("Health classification distinguishes observations from canonical failure counters",()=>{assert.match(closure,/confirmed_state_breakdown/);assert.match(closure,/escrow_expected_held_total/);assert.match(closure,/escrow_actual_balance/);assert.match(proof,/refunded_settlement_breakdown/);assert.match(proof,/legitimateNonzeroObservationsHealthy/);assert.match(proof,/expectedActualEqualityHealthy/);assert.match(proof,/expectedActualMismatchUnhealthy/)});
test("Health web validation enforces exact group-specific JSON contracts",()=>{for(const token of["healthCounterKeys","validatePaymentsHealthCounters","validateSettlementsHealthCounters","validateAdsFinanceHealthCounters","validateIntegerHealthCounters","groups.complete",".duplicate"])assert(api.includes(token),token);assert.doesNotMatch(api,/validateHealthCounterValue/);for(const phrase of["string and boolean values for numeric Health counters","array and object shape substitutions","complete unique canonical Health group set","negative Health counts","legitimate nonzero observations","realistic malformed JSON with retry","valid canonical unhealthy Health response"])assert(webTests.includes(phrase),phrase);assert.doesNotMatch(webTests,/Symbol\(|undefined\s*[,}]/)});
test("B8C routes remain in admin web and B8D/mobile are untouched",()=>{for(const path of["creator-commerce","promotions","ads","health","activity"])assert(app.includes(`/marketplace/${path}`));for(const label of["Creator Commerce","Promociones","Ads","Salud","Actividad"])assert(shell.includes(label));assert(!existsSync(join(root,"app/marketplace/health.tsx")));assert.doesNotMatch(migration+closure+api+pages,/B8D|marketplace:repair|ledger_debit|ledger_credit/);const appJson=JSON.parse(readFileSync(join(root,"app.json"),"utf8"));assert.equal(String(appJson.expo.ios.buildNumber),"22")});
test("security proof covers identities, mismatch rollback, audit immutability and fixture hygiene",()=>{for(const token of["anonymousDenied","ordinaryDenied","metadataForgeryDenied","adminAllowed","controlledMismatchSurfaced","rollbackHealthy","immutable","fixtures"])assert(proof.includes(token));assert.match(proof,/B8C_PROOF_REQUIRES_DISPOSABLE_DATABASE/);for(const flag of["--expect-pre-b8c","--require-b8c","--expect-pre-b8c-c1","--require-b8c-c1"])assert(auditor.includes(flag))});
