import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';const sql=readFileSync('supabase/migrations/20260801062000_fix_marketplace_fulfillment_access.sql','utf8'),svc=readFileSync('services/marketplaceFulfillmentService.ts','utf8'),parsers=readFileSync('services/marketplaceFulfillmentParsers.mjs','utf8'),buyer=readFileSync('app/orders/index.tsx','utf8'),seller=readFileSync('app/seller/orders/index.tsx','utf8'),detail=readFileSync('app/orders/[id].tsx','utf8');
test('shipment and event base reads are revoked while RPC grants remain',()=>{assert.match(sql,/revoke select on public\.marketplace_order_shipments from public,anon,authenticated/);assert.match(sql,/revoke select on public\.marketplace_order_events from public,anon,authenticated/);assert.match(sql,/grant execute on function public\.fetch_my_marketplace_order/)});
test('buyer detail requires owned paid checkout and payment',()=>{assert.match(sql,/o\.buyer_id<>auth\.uid\(\)/);assert.match(sql,/c\.status='paid' and p\.status='paid'/)});
test('seller detail requires ownership approval active store paid payment and held allocation',()=>{assert.match(sql,/o\.seller_id<>auth\.uid\(\)/);assert.match(sql,/status='approved'/);assert.match(sql,/seller_id=auth\.uid\(\) and status='active'/);assert.match(sql,/status='held'/)});
test('seller list validates status and active owned store',()=>{assert.match(sql,/p_status not in \('confirmed','processing','shipped'/);assert.match(sql,/select id into v_store.*seller_id=auth\.uid\(\).*status='active'/s)});
test('service cursor threshold uses effective limit not fifty',()=>{assert.match(parsers,/items\.length\s*===\s*effectiveLimit/);assert.doesNotMatch(parsers,/items\.length\s*===\s*50/);assert.match(svc,/Math\.min\(50/)});
test('lists page by twenty append uniquely and lock duplicate requests',()=>{for(const code of[buyer,seller]){assert.match(code,/PAGE\s*=\s*20/);assert.match(code,/onEndReached/);assert.match(code,/lock\.current/);assert.match(code,/new Map/);assert.match(code,/nextCursor/)}assert.match(buyer,/components\/ui\/SafeImage/)});
test('buyer sanitized detail never renders seller note',()=>{assert.doesNotMatch(detail,/sellerNote|created_by|reason_code|metadata/)});
test('hardening remains nonfinancial and inventory neutral',()=>{assert.doesNotMatch(sql,/ledger_debit|ledger_credit|update public\.marketplace_payments|update public\.marketplace_payment_allocations|update public\.marketplace_inventory|status='delivered'|escrow_released/)});
