import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { useBusinessAuth } from "../../auth/BusinessAuthProvider";
import { BusinessMediaPicker } from "../../components/BusinessMedia";
import { FormField, InlineError, PageHeader, StatusBadge } from "../../components/BusinessUI";
import type { BusinessMediaItem } from "../../lib/businessMediaApi";
import { formatMoney } from "../../lib/businessFormat";
import { assignShippingProfile, configureVariants, getProduct, mutateInventory, productAction, saveProductDraft, searchShippingProfiles, setProductMedia, updateVariant, variantAction, type Cursor, type ProductDetail, type ShippingProfile } from "../../lib/sellerCenterApi";

function message(code: unknown) {
  const labels: Record<string, string> = { marketplace_product_media_required: "Añade al menos una imagen.", marketplace_product_not_ready_shipping_incomplete: "Completa y asigna un perfil de envío.", marketplace_product_not_ready_out_of_stock: "Añade inventario disponible.", marketplace_product_not_ready_inventory_not_configured: "Configura el inventario de las variantes.", marketplace_product_not_ready_no_active_variant: "Activa al menos una variante." };
  return typeof code === "string" ? labels[code] ?? code.replaceAll("_", " ") : null;
}

export function BusinessProductDetailPage() {
  const { productId = "" } = useParams(); const { currentBusiness, hasCapability } = useBusinessAuth();
  const canManage = hasCapability("business.catalog.manage"); const canInventory = hasCapability("business.inventory.manage"); const canReadInventory = canInventory || hasCapability("business.inventory.read"); const canMedia = canManage && (hasCapability("business.media.read") || hasCapability("business.media.manage"));
  const [detail, setDetail] = useState<ProductDetail | null>(null); const [profiles, setProfiles] = useState<ShippingProfile[]>([]); const [profileCursor, setProfileCursor] = useState<Cursor | null>(null); const [loadingProfiles, setLoadingProfiles] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [picker, setPicker] = useState(false); const [pendingImages, setPendingImages] = useState<string[]>([]);
  const load = useCallback(async () => { if (!currentBusiness || !productId) return; setLoading(true); setError(null); try { const [product, shipping] = await Promise.all([getProduct(currentBusiness.businessOwnerId, productId), searchShippingProfiles(currentBusiness.businessOwnerId).catch(() => ({ items: [], nextCursor: null }))]); setDetail(product); setProfiles(shipping.items); setProfileCursor(shipping.nextCursor); setPendingImages(product.media.filter((item) => item.slot === "image").map((item) => String(item.asset_id))); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar el producto"); } finally { setLoading(false); } }, [currentBusiness, productId]);
  useEffect(() => { void load(); }, [load]);
  async function run(action: () => Promise<void>, label: string) { setError(null); setSuccess(null); try { await action(); setSuccess(label); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo completar la acción"); } }
  async function loadMoreProfiles() { if (!currentBusiness || !profileCursor) return; setLoadingProfiles(true); setError(null); try { const page = await searchShippingProfiles(currentBusiness.businessOwnerId, profileCursor); setProfiles((current) => { const seen = new Set(current.map((profile) => profile.id)); const result = [...current]; for (const profile of page.items) { if (seen.has(profile.id)) continue; seen.add(profile.id); result.push(profile); } return result; }); setProfileCursor(page.nextCursor); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudieron cargar más perfiles"); } finally { setLoadingProfiles(false); } }
  async function saveGeneral(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail || !canManage) return; const form = new FormData(event.currentTarget); await run(() => saveProductDraft({ p_product_id: productId, p_category_id: String(form.get("category")), p_title: String(form.get("title")), p_description: String(form.get("description")), p_price: Number(form.get("price")), p_brand: String(form.get("brand")) || null, p_compare_at_price: form.get("compare") ? Number(form.get("compare")) : null, p_stock: Number(detail.product.stock ?? 0), p_tags: String(form.get("tags") ?? "").split(",").map((item) => item.trim()).filter(Boolean), p_shipping_profile_id: detail.product.shipping_profile_id ?? null, p_product_type: String(detail.product.product_type ?? "physical"), p_title_configured: true, p_price_configured: true, p_category_configured: true }), "Producto guardado"); }
  async function saveImages() { await run(() => setProductMedia(productId, pendingImages, pendingImages[0] ?? null), "Media actualizada"); }
  if (loading) return <div className="seller-state">Cargando producto…</div>;
  if (!detail) return <><InlineError message={error} /><Link to="/products">Volver al catálogo</Link></>;
  const product = detail.product; const readiness = message(product.readiness_reason);
  return <><PageHeader eyebrow="Editor de producto" title={String(product.title)} description="La publicación y sus requisitos siguen bajo la autoridad canónica del Marketplace." action={<div className="header-actions"><StatusBadge status={String(product.status)} /><Link className="secondary-button" to="/products">Volver</Link></div>} /><div className="editor-section-nav"><a href="#general">General</a><a href="#media">Media</a><a href="#variants">Variantes</a>{canReadInventory && <a href="#inventory">Inventario</a>}<a href="#shipping">Envío</a></div><InlineError message={error} />{success && <div className="inline-success" role="status">{success}</div>}{readiness && <div className="readiness-panel"><strong>Antes de publicar</strong><p>{readiness}</p></div>}
    <section className="editor-card" id="general"><h2>Información general</h2><form className="seller-form" onSubmit={(event) => void saveGeneral(event)}><FormField label="Título"><input name="title" required maxLength={80} disabled={!canManage} defaultValue={String(product.title)} /></FormField><FormField label="Descripción"><textarea name="description" rows={5} maxLength={2000} disabled={!canManage} defaultValue={String(product.description ?? "")} /></FormField><div className="two-column"><FormField label="Categoría"><select name="category" disabled={!canManage} defaultValue={String(product.category_id)}>{detail.categories.map((category) => <option key={String(category.id)} value={String(category.id)}>{String(category.name)}</option>)}</select></FormField><FormField label="Marca"><input name="brand" disabled={!canManage} defaultValue={String(product.brand ?? "")} /></FormField></div><div className="two-column"><FormField label="Precio BDAG"><input name="price" type="number" min="0.00000001" step="0.01" required disabled={!canManage} defaultValue={String(product.price)} /></FormField><FormField label="Precio comparativo"><input name="compare" type="number" min="0" step="0.01" disabled={!canManage} defaultValue={String(product.compare_at_price ?? "")} /></FormField></div><FormField label="Etiquetas"><input name="tags" disabled={!canManage} defaultValue={Array.isArray(product.tags) ? product.tags.join(", ") : ""} /></FormField>{canManage && <div className="form-actions"><button className="primary-button" type="submit">Guardar</button><button className="secondary-button" type="button" onClick={() => void run(() => productAction("publish", productId), "Producto publicado")}>Publicar</button><button className="text-button" type="button" onClick={() => void run(() => productAction("pause", productId), "Producto pausado")}>Pausar</button><button className="danger-button" type="button" onClick={() => void run(() => productAction("delete", productId), "Producto eliminado")}>Eliminar</button></div>}</form></section>
    <section className="editor-card" id="media"><div className="section-heading"><div><h2>Media</h2><p>Imágenes reutilizadas desde Business Media, sin alterar su identidad READY.</p></div>{canMedia && <button className="secondary-button" type="button" onClick={() => setPicker(true)}>Elegir de Media</button>}</div><div className="product-media-strip">{detail.media.filter((item) => pendingImages.includes(String(item.asset_id))).map((item) => <div key={String(item.asset_id)}><img src={String(item.url)} alt="Media del producto" />{canMedia && <button type="button" onClick={() => setPendingImages((current) => current.filter((id) => id !== item.asset_id))}>Quitar</button>}</div>)}{pendingImages.filter((id) => !detail.media.some((item) => item.asset_id === id)).map((id) => <div className="pending-media" key={id}>Nueva imagen</div>)}</div>{canMedia && <button className="primary-button" type="button" onClick={() => void saveImages()}>Guardar media</button>}<BusinessMediaPicker open={picker} selectedId={null} title="Añadir imagen al producto" onClose={() => setPicker(false)} onSelect={(item: BusinessMediaItem) => { setPendingImages((current) => current.includes(item.assetId) ? current : [...current, item.assetId].slice(0, 5)); setPicker(false); }} /></section>
    <section className="editor-card" id="variants"><h2>Variantes</h2><div className="variant-list">{detail.variants.map((variant) => <VariantRow key={variant.id} variant={variant} variants={detail.variants} canManage={canManage} onRun={run} />)}</div>{canManage && <VariantConfigurator productId={productId} basePrice={Number(product.price)} onRun={run} />}</section>
    {canReadInventory && <section className="editor-card" id="inventory"><h2>Inventario</h2><div className="inventory-grid">{detail.variants.map((variant) => <article key={variant.id}><strong>{variant.sku}</strong><span>En mano: {variant.onHand ?? "—"}</span><span>Reservado: {variant.reserved ?? "—"}</span><span>Disponible: {variant.available ?? "—"}</span><span>Low stock: {variant.lowStockThreshold ?? "—"}</span>{canInventory && <div className="compact-actions"><button type="button" onClick={() => { const value = Number(window.prompt("Nuevo inventario", String(variant.onHand ?? 0))); if (Number.isFinite(value)) void run(() => mutateInventory("set", variant.id, value), "Inventario actualizado"); }}>Fijar</button><button type="button" onClick={() => { const value = Number(window.prompt("Ajuste (+/-)", "1")); if (Number.isFinite(value)) void run(() => mutateInventory("adjust", variant.id, value), "Inventario ajustado"); }}>Ajustar</button><button type="button" onClick={() => { const value = Number(window.prompt("Umbral low stock", String(variant.lowStockThreshold ?? 0))); if (Number.isFinite(value)) void run(() => mutateInventory("threshold", variant.id, value), "Umbral actualizado"); }}>Umbral</button></div>}</article>)}</div></section>}
    <section className="editor-card" id="shipping"><h2>Envío</h2><p>Perfil actual: {profiles.find((profile) => profile.id === product.shipping_profile_id)?.name ?? "Sin asignar"}</p>{canManage && <div className="inline-controls"><select aria-label="Perfil de envío" defaultValue={String(product.shipping_profile_id ?? "")} id="product-shipping-profile"><option value="">Selecciona un perfil</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select><button className="secondary-button" type="button" onClick={() => { const selected = (document.getElementById("product-shipping-profile") as HTMLSelectElement).value; if (selected) void run(() => assignShippingProfile(productId, selected), "Perfil asignado"); }}>Asignar</button>{profileCursor && <button className="text-button" type="button" disabled={loadingProfiles} onClick={() => void loadMoreProfiles()}>{loadingProfiles ? "Cargando…" : "Ver más perfiles"}</button>}</div>}<Link to="/products/shipping">Gestionar perfiles</Link></section>
  </>;
}

function VariantRow({ variant, variants, canManage, onRun }: { variant: ProductDetail["variants"][number]; variants: ProductDetail["variants"]; canManage: boolean; onRun: (action: () => Promise<void>, label: string) => Promise<void> }) {
  const [sku, setSku] = useState(variant.sku); const [price, setPrice] = useState(String(variant.price)); const [choosingReplacement, setChoosingReplacement] = useState(false); const [replacementId, setReplacementId] = useState("");
  const activeVariants = variants.filter((candidate) => candidate.status === "active"); const replacementOptions = activeVariants.filter((candidate) => candidate.id !== variant.id); const lastActive = variant.status === "active" && activeVariants.length <= 1; const archiveDisabled = lastActive || (variant.isDefault && replacementOptions.length === 0);
  async function archive() { if (variant.isDefault) { setChoosingReplacement(true); return; } await onRun(() => variantAction("archive", variant.id, null), "Variante archivada"); }
  async function archiveDefault() { if (!replacementId) return; await onRun(() => variantAction("archive", variant.id, replacementId), "Variante archivada"); setChoosingReplacement(false); setReplacementId(""); }
  return <article className="variant-row"><div><strong>{variant.title ?? variant.sku}</strong><small>{variant.isDefault ? "Predeterminada" : variant.status}</small></div><input aria-label={`SKU ${variant.sku}`} disabled={!canManage} value={sku} onChange={(event) => setSku(event.target.value)} /><input aria-label={`Precio ${variant.sku}`} type="number" step="0.01" disabled={!canManage} value={price} onChange={(event) => setPrice(event.target.value)} /><span>{formatMoney(variant.price)}</span>{canManage && <div className="compact-actions"><button type="button" onClick={() => void onRun(() => updateVariant({ p_variant_id: variant.id, p_sku: sku, p_price: Number(price), p_compare_at_price: variant.compareAtPrice, p_status: variant.status === "archived" ? "inactive" : variant.status, p_image_asset_id: variant.imageAssetId, p_title: variant.title, p_barcode: variant.barcode }), "Variante guardada")}>Guardar</button>{!variant.isDefault && variant.status !== "archived" && <button type="button" onClick={() => void onRun(() => variantAction("default", variant.id), "Variante predeterminada actualizada")}>Predeterminada</button>}{variant.status === "archived" ? <button type="button" onClick={() => void onRun(() => variantAction("restore", variant.id), "Variante restaurada")}>Restaurar</button> : <button type="button" disabled={archiveDisabled} title={archiveDisabled ? "Debe existir otra variante activa" : undefined} onClick={() => void archive()}>Archivar</button>}</div>}{choosingReplacement && <div className="variant-replacement"><label htmlFor={`replacement-${variant.id}`}>Selecciona la nueva variante predeterminada</label><select id={`replacement-${variant.id}`} value={replacementId} onChange={(event) => setReplacementId(event.target.value)}><option value="">Selecciona una variante</option>{replacementOptions.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.title ?? candidate.sku}</option>)}</select><div className="compact-actions"><button className="danger-button" type="button" disabled={!replacementId} onClick={() => void archiveDefault()}>Confirmar archivo</button><button className="text-button" type="button" onClick={() => { setChoosingReplacement(false); setReplacementId(""); }}>Cancelar</button></div></div>}</article>;
}

function VariantConfigurator({ productId, basePrice, onRun }: { productId: string; basePrice: number; onRun: (action: () => Promise<void>, label: string) => Promise<void> }) {
  const [name, setName] = useState("Tamaño"); const [values, setValues] = useState("");
  function configure() { const list = values.split(",").map((value) => value.trim()).filter(Boolean); if (!list.length) return; const variants = list.map((value, index) => ({ sku: `${name}-${value}`.toUpperCase().replace(/[^A-Z0-9]+/g, "-"), title: value, price: basePrice, compare_at_price: null, status: "active", is_default: index === 0, image_asset_id: null, barcode: null, option_values: [value], on_hand: 0, low_stock_threshold: 0 })); void onRun(() => configureVariants(productId, [{ name, values: list }], variants), "Variantes configuradas"); }
  return <div className="variant-configurator"><h3>Configurar combinaciones</h3><input aria-label="Nombre de opción" value={name} onChange={(event) => setName(event.target.value)} /><input aria-label="Valores de opción" placeholder="Pequeño, Mediano, Grande" value={values} onChange={(event) => setValues(event.target.value)} /><button className="secondary-button" type="button" onClick={configure}>Crear combinaciones</button></div>;
}
