import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { useBusinessAuth } from "../../auth/BusinessAuthProvider";
import { FormField, InlineError, PageHeader, StatusBadge } from "../../components/BusinessUI";
import { formatDate, formatMoney } from "../../lib/businessFormat";
import { getOrder, shipOrder, startOrderProcessing } from "../../lib/sellerCenterApi";

export function BusinessOrderDetailPage() {
  const { orderId = "" } = useParams(); const { currentBusiness, hasCapability } = useBusinessAuth(); const canFulfill = hasCapability("business.orders.fulfill");
  const ownerId = currentBusiness?.businessOwnerId ?? "";
  const [order, setOrder] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const requestRef = useRef(0);
  const load = useCallback(async () => { if (!ownerId || !orderId) return; const request = ++requestRef.current; setLoading(true); setError(null); try { const next = await getOrder(ownerId, orderId); if (request === requestRef.current) setOrder(next); } catch (cause) { if (request === requestRef.current) setError(cause instanceof Error ? cause.message : "No se pudo cargar el pedido"); } finally { if (request === requestRef.current) setLoading(false); } }, [orderId, ownerId]);
  useEffect(() => { setOrder(null); setSuccess(null); void load(); return () => { requestRef.current += 1; }; }, [load]); async function run(action: () => Promise<void>, label: string) { setError(null); try { await action(); setSuccess(label); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo completar la acción"); } }
  async function ship(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await run(() => shipOrder(orderId, { carrier: String(form.get("carrier")), service: String(form.get("service")), tracking: String(form.get("tracking")), url: String(form.get("url")), note: String(form.get("note")) }), "Pedido marcado como enviado"); }
  if (loading) return <div className="seller-state">Cargando pedido…</div>; if (!order) return <><InlineError message={error} /><Link to="/orders">Volver</Link></>;
  const items = Array.isArray(order.items) ? order.items as Record<string, unknown>[] : []; const address = order.shipping_address as Record<string, unknown> | null;
  return <><PageHeader eyebrow="Pedido" title={String(order.order_number)} description={formatDate(String(order.created_at))} action={<div className="header-actions"><StatusBadge status={String(order.status)} /><Link className="secondary-button" to="/orders">Volver</Link></div>} /><InlineError message={error} />{success && <div className="inline-success">{success}</div>}<div className="order-detail-grid"><section className="editor-card"><h2>Artículos</h2>{items.map((item) => <div className="order-line" key={String(item.id)}><div><strong>{String(item.product_title)}</strong><small>{String(item.variant_title ?? item.sku)}</small></div><span>× {String(item.quantity)}</span><strong>{formatMoney(Number(item.line_total), String(item.currency))}</strong></div>)}<div className="order-total"><span>Total</span><strong>{formatMoney(Number(order.total), String(order.currency))}</strong></div></section><aside className="editor-card"><h2>Entrega</h2>{canFulfill && address ? <address>{String(address.recipient_name)}<br />{String(address.line1)} {String(address.line2 ?? "")}<br />{String(address.city)}, {String(address.region)} {String(address.postal_code)}<br />{String(address.country)}<br />{String(address.phone ?? "")}</address> : <p className="readonly-note">La dirección completa solo está disponible con business.orders.fulfill.</p>}</aside></div>{canFulfill && order.status === "confirmed" && <section className="editor-card"><h2>Procesamiento</h2><button className="primary-button" type="button" onClick={() => void run(() => startOrderProcessing(orderId), "Procesamiento iniciado")}>Iniciar procesamiento</button></section>}{canFulfill && order.status === "processing" && <section className="editor-card"><h2>Envío y tracking</h2><form className="seller-form" onSubmit={(event) => void ship(event)}><div className="two-column"><FormField label="Transportista"><input name="carrier" required minLength={2} /></FormField><FormField label="Servicio"><input name="service" /></FormField></div><FormField label="Número de tracking"><input name="tracking" required minLength={2} /></FormField><FormField label="URL de tracking"><input name="url" type="url" /></FormField><FormField label="Nota"><textarea name="note" rows={3} /></FormField><button className="primary-button" type="submit">Marcar enviado</button></form></section>}</>;
}
