import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter,Route,Routes } from "react-router-dom";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { AdminRoute } from "../auth/AdminRoute";
import { useAdminAuth } from "../auth/AdminAuthProvider";
import { formatDate,getOrderDetail,getOverview,searchOrders,validateOrderDetail } from "../lib/adminApi";
import { supabase } from "../lib/supabase";
import { LoginPage } from "../pages/LoginPage";
import { MarketplaceOrderDetailPage } from "../pages/MarketplaceOrderDetailPage";
import { MarketplaceOrdersPage } from "../pages/MarketplaceOrdersPage";
import { MarketplaceOverviewPage } from "../pages/MarketplaceOverviewPage";

vi.mock("../auth/AdminAuthProvider",()=>({useAdminAuth:vi.fn()}));
vi.mock("../lib/supabase",()=>({supabase:{rpc:vi.fn(),auth:{getSession:vi.fn(),onAuthStateChange:vi.fn(),signInWithPassword:vi.fn(),signOut:vi.fn()}}}));
vi.mock("../lib/adminApi",async(importOriginal)=>{const original=await importOriginal<typeof import("../lib/adminApi")>();return{...original,getOverview:vi.fn(),searchOrders:vi.fn(),getOrderDetail:vi.fn()};});
const auth=vi.mocked(useAdminAuth),overview=vi.mocked(getOverview),orders=vi.mocked(searchOrders),detail=vi.mocked(getOrderDetail);
const admin={user_id:"10000000-0000-4000-8000-000000000001",username:"ops",display_name:"Ops",admin:true as const,capabilities:["marketplace:read"]};
const baseAuth={loading:false,session:{user:{id:admin.user_id}} as never,admin,denied:false,error:null,login:vi.fn(),logout:vi.fn(),retry:vi.fn()};

beforeEach(()=>{vi.clearAllMocks();auth.mockReturnValue(baseAuth);});

describe("authentication boundary",()=>{
  it("renders and submits the email/password login form",async()=>{const login=vi.fn().mockResolvedValue(undefined);auth.mockReturnValue({...baseAuth,session:null,admin:null,login});render(<MemoryRouter><LoginPage/></MemoryRouter>);await userEvent.type(screen.getByLabelText("Correo"),"admin@onspace.test");await userEvent.type(screen.getByLabelText("Contraseña"),"secret");await userEvent.click(screen.getByRole("button",{name:"Ingresar"}));expect(login).toHaveBeenCalledWith("admin@onspace.test","secret");});
  it("redirects an anonymous visitor to login",()=>{auth.mockReturnValue({...baseAuth,session:null,admin:null});render(<MemoryRouter initialEntries={["/marketplace"]}><Routes><Route path="/login" element={<p>login destination</p>}/><Route element={<AdminRoute/>}><Route path="/marketplace" element={<p>private</p>}/></Route></Routes></MemoryRouter>);expect(screen.getByText("login destination")).toBeInTheDocument();});
  it("shows access denied for an authenticated non-admin",()=>{auth.mockReturnValue({...baseAuth,admin:null,denied:true,error:"marketplace_admin_forbidden"});render(<MemoryRouter><Routes><Route element={<AdminRoute/>}><Route index element={<p>private</p>}/></Route></Routes></MemoryRouter>);expect(screen.getByText("Acceso restringido")).toBeInTheDocument();expect(screen.queryByText("private")).not.toBeInTheDocument();});
  it("renders the protected outlet for an authorized admin",()=>{render(<MemoryRouter><Routes><Route element={<AdminRoute/>}><Route index element={<p>admin content</p>}/></Route></Routes></MemoryRouter>);expect(screen.getByText("admin content")).toBeInTheDocument();});
  it("logs out from the denied state",async()=>{const logout=vi.fn().mockResolvedValue(undefined);auth.mockReturnValue({...baseAuth,admin:null,denied:true,error:"forbidden",logout});render(<MemoryRouter><Routes><Route element={<AdminRoute/>}><Route index element={<p>private</p>}/></Route></Routes></MemoryRouter>);await userEvent.click(screen.getByRole("button",{name:"Cerrar sesión"}));expect(logout).toHaveBeenCalledOnce();});
});

const overviewPayload={range:"30d" as const,generated_at:"2026-08-14T12:00:00Z",commerce:{orders:4,paid_orders:3,paid_gmv:"100.00000000",units:5,pending_fulfillment:1,shipped:1,delivered:1,refunded_orders:1,reversed_orders:1,reversed_gross:"20.00000000"},sellers:{approved:2,active_stores:2},products:{active_published:8,requiring_attention:1},creator_commerce:{attributed_orders:2,attributed_gmv:"70.00000000",commission_generated:"7.00000000",commission_released:"7.00000000",commission_reversed:"2.00000000",commission_net:"5.00000000"},operations:{open_disputes:1,held_allocations:1}};
describe("Marketplace overview",()=>{
  it("renders canonical metrics and changes server range",async()=>{overview.mockResolvedValue(overviewPayload);render(<MarketplaceOverviewPage/>);expect(await screen.findByText("100.00000000 BDAG")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"7D"}));await waitFor(()=>expect(overview).toHaveBeenLastCalledWith("7d"));});
  it("shows an RPC error and retry action",async()=>{overview.mockRejectedValue(new Error("network"));render(<MarketplaceOverviewPage/>);expect(await screen.findByText("No se pudo cargar")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Reintentar"})).toBeInTheDocument();});
});

const order={id:"20000000-0000-4000-8000-000000000001",order_number:"ORD-1",created_at:"2026-08-14T12:00:00Z",status:"confirmed",currency:"BDAG",amount:"30.00000000",buyer_name:"Buyer",seller_name:"Seller",store_id:"30000000-0000-4000-8000-000000000001",store_name:"Store",item_count:1,payment_status:"paid",fulfillment_status:null,settlement_status:null,dispute_open:false,reversed:false,creator_commerce:true,source_surfaces:["feed"]};
describe("Marketplace orders",()=>{
  it("loads a bounded order page and preserves filters in URL state",async()=>{orders.mockResolvedValue({range:"30d",orders:[order],next_cursor:null,page_size:1});render(<MemoryRouter initialEntries={["/marketplace/orders?status=confirmed&range=30d"]}><MarketplaceOrdersPage/></MemoryRouter>);expect(await screen.findByText("ORD-1")).toBeInTheDocument();expect(orders).toHaveBeenCalledWith(expect.objectContaining({status:"confirmed",range:"30d",limit:50}));});
  it("renders an empty result state",async()=>{orders.mockResolvedValue({range:"30d",orders:[],next_cursor:null,page_size:0});render(<MemoryRouter><MarketplaceOrdersPage/></MemoryRouter>);expect(await screen.findByText("Sin resultados")).toBeInTheDocument();});
  it("submits search text without exposing session data",async()=>{orders.mockResolvedValue({range:"30d",orders:[],next_cursor:null,page_size:0});render(<MemoryRouter><MarketplaceOrdersPage/></MemoryRouter>);const input=screen.getByLabelText("Buscar pedidos");fireEvent.change(input,{target:{value:"ORD-2"}});fireEvent.submit(input.closest("form")!);await waitFor(()=>expect(orders).toHaveBeenCalledWith(expect.objectContaining({query:"ORD-2"})));});
});

const ids={buyer:"10000000-0000-4000-8000-000000000010",seller:"10000000-0000-4000-8000-000000000011",store:"10000000-0000-4000-8000-000000000012",item:"10000000-0000-4000-8000-000000000013",product:"10000000-0000-4000-8000-000000000014",variant:"10000000-0000-4000-8000-000000000015",creator:"10000000-0000-4000-8000-000000000016",source:"10000000-0000-4000-8000-000000000017",allocation:"10000000-0000-4000-8000-000000000018",payment:"10000000-0000-4000-8000-000000000019",paymentAllocation:"10000000-0000-4000-8000-000000000020",settlement:"10000000-0000-4000-8000-000000000021",settlementLeg:"10000000-0000-4000-8000-000000000022",dispute:"10000000-0000-4000-8000-000000000023",reversal:"10000000-0000-4000-8000-000000000024",reversalLeg:"10000000-0000-4000-8000-000000000025",event:"10000000-0000-4000-8000-000000000026"};
const validDetail={
  order:{id:order.id,order_number:"ORD-1",status:"delivered",currency:"BDAG",subtotal:"100.00000000",shipping_amount:"0.00000000",total:"100.00000000",created_at:"2026-08-14T12:00:00Z",confirmed_at:"2026-08-14T12:01:00Z",processing_at:"2026-08-14T12:02:00Z",shipped_at:"2026-08-14T12:03:00Z",delivered_at:"2026-08-14T12:04:00Z"},
  buyer:{id:ids.buyer,username:"buyer",display_name:"Buyer"},seller:{id:ids.seller,display_name:"Seller",status:"approved"},store:{id:ids.store,name:"Store",slug:"store",status:"active"},
  items:[{id:ids.item,product_id:ids.product,variant_id:ids.variant,product_title:"Product",variant_title:null,sku:"SKU",image_url:null,currency:"BDAG",unit_price:"100.00000000",quantity:1,line_total:"100.00000000",creator:{creator_user_id:ids.creator,creator_username:"creator",creator_display_name:"Creator",source_surface:"live",source_entity_id:ids.source,historical_bps:700,item_gmv:"100.00000000",allocation_amount:"7.00000000",allocation_id:ids.allocation}}],
  payment:{id:ids.payment,status:"paid",currency:"BDAG",gross_amount:"100.00000000",escrow_amount:"100.00000000",fee_bps:1000,paid_at:"2026-08-14T12:01:00Z",refunded_at:null},payment_allocation:{id:ids.paymentAllocation,status:"released",gross_amount:"100.00000000",platform_fee_amount:"10.00000000",seller_net_amount:"83.00000000",creator_commission_amount:"7.00000000",released_at:"2026-08-14T12:05:00Z",refunded_at:null},
  shipping:{address:{recipient_name:"Buyer",line1:"1 Main",line2:null,city:"Miami",region:"FL",postal_code:"33101",country:"US"},shipment:{status:"delivered",carrier_name:"Carrier",service_level:null,tracking_number:"TRACK",tracking_url:null,shipped_at:"2026-08-14T12:03:00Z",estimated_delivery_at:null,delivered_at:"2026-08-14T12:04:00Z"}},
  creator_attributions:[{order_item_id:ids.item,creator_user_id:ids.creator,source_surface:"live",source_entity_id:ids.source,product_id:ids.product,variant_id:ids.variant,historical_bps:700,attributed_at:"2026-08-14T12:00:00Z"}],creator_allocations:[{id:ids.allocation,order_item_id:ids.item,creator_user_id:ids.creator,commission_bps:700,item_gmv:"100.00000000",commission_amount:"7.00000000",created_at:"2026-08-14T12:01:00Z"}],
  settlement:{id:ids.settlement,status:"completed",gross_amount:"100.00000000",seller_net_amount:"83.00000000",platform_fee_amount:"10.00000000",creator_commission_amount:"7.00000000",released_at:"2026-08-14T12:05:00Z"},settlement_legs:[{id:ids.settlementLeg,leg_type:"creator_commission",beneficiary_user_id:ids.creator,amount:"7.00000000",status:"completed",created_at:"2026-08-14T12:05:00Z"}],
  dispute:{id:ids.dispute,status:"resolved",reason_code:"other",buyer_note:null,created_at:"2026-08-14T12:06:00Z",resolved_at:"2026-08-14T12:07:00Z"},reversal:{id:ids.reversal,gross_amount:"100.00000000",currency:"BDAG",reason_code:"refund",created_at:"2026-08-14T13:00:00Z"},reversal_legs:[{id:ids.reversalLeg,leg_type:"creator_commission",beneficiary_user_id:ids.creator,original_amount:"7.00000000",reversal_amount:"7.00000000",created_at:"2026-08-14T13:00:00Z"}],timeline:[{id:ids.event,event_type:"delivery_confirmed",from_status:"shipped",to_status:"delivered",actor_role:"buyer",reason_code:null,created_at:"2026-08-14T12:30:00Z"}]
};

describe("order detail payload validation",()=>{
  it("accepts the complete contract and nullable sections",()=>{expect(validateOrderDetail(validDetail).order.id).toBe(order.id);expect(validateOrderDetail({...validDetail,payment:null,payment_allocation:null,shipping:{address:null,shipment:null},settlement:null,dispute:null,reversal:null}).payment).toBeNull();});
  it("rejects a malformed order UUID",()=>{const payload=structuredClone(validDetail);payload.order.id="not-a-uuid";expect(()=>validateOrderDetail(payload)).toThrow("order.id");});
  it("rejects a malformed financial amount",()=>{const payload=structuredClone(validDetail);payload.payment.gross_amount="NaN";expect(()=>validateOrderDetail(payload)).toThrow("payment.gross_amount");});
  it("rejects a malformed timestamp and formatDate remains non-throwing",()=>{const payload=structuredClone(validDetail);payload.order.created_at="not-a-date";expect(()=>validateOrderDetail(payload)).toThrow("order.created_at");expect(formatDate("not-a-date")).toBe("—");});
  it("rejects malformed nested creator allocation data",()=>{const payload=structuredClone(validDetail);Object.assign(payload.items[0].creator,{allocation_amount:{}});expect(()=>validateOrderDetail(payload)).toThrow("items[0].creator.allocation_amount");});
  it("rejects malformed nested array/object shapes",()=>{const allocations=structuredClone(validDetail);Object.assign(allocations,{creator_allocations:{}});expect(()=>validateOrderDetail(allocations)).toThrow("creator_allocations");const shipping=structuredClone(validDetail);Object.assign(shipping,{shipping:[]});expect(()=>validateOrderDetail(shipping)).toThrow("shipping");});
  it("makes getOrderDetail reject a malformed RPC response",async()=>{const payload=structuredClone(validDetail);payload.order.id="not-a-uuid";vi.mocked(supabase.rpc).mockResolvedValue({data:payload,error:null} as never);const actual=await vi.importActual<typeof import("../lib/adminApi")>("../lib/adminApi");await expect(actual.getOrderDetail(order.id)).rejects.toThrow("order.id");});
});

describe("order detail UI",()=>{
  it("renders item-level creator, payment, settlement, reversal, and timeline facts",async()=>{detail.mockResolvedValue(validateOrderDetail(validDetail));render(<MemoryRouter initialEntries={[`/marketplace/orders/${order.id}`]}><Routes><Route path="/marketplace/orders/:orderId" element={<MarketplaceOrderDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Product")).toBeInTheDocument();expect(screen.getByText("Origen: live")).toBeInTheDocument();expect(screen.getByText("Liquidación")).toBeInTheDocument();expect(screen.getByText("Disputa / reversión")).toBeInTheDocument();});
  it("renders the controlled retry state for a malformed response rejection",async()=>{detail.mockRejectedValue(new Error("Respuesta inválida: order.id"));render(<MemoryRouter initialEntries={[`/marketplace/orders/${order.id}`]}><Routes><Route path="/marketplace/orders/:orderId" element={<MarketplaceOrderDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("No se pudo cargar")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Reintentar"})).toBeInTheDocument();expect(screen.queryByText(/undefined BDAG|NaN|Invalid Date/)).not.toBeInTheDocument();});
});
