import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter,Route,Routes } from "react-router-dom";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { moderateProduct,resolveDispute,searchDisputes,searchProducts,searchSellers,validateDisputeDetail,validateProductDetail,validateSellerDetail } from "../lib/adminApi";
import { MarketplaceDisputeDetailPage } from "../pages/MarketplaceDisputeDetailPage";
import { MarketplaceDisputesPage } from "../pages/MarketplaceDisputesPage";
import { MarketplaceProductsPage } from "../pages/MarketplaceProductsPage";
import { MarketplaceSellersPage } from "../pages/MarketplaceSellersPage";

vi.mock("../lib/supabase",()=>({supabase:{rpc:vi.fn(),auth:{getSession:vi.fn(),onAuthStateChange:vi.fn(),signInWithPassword:vi.fn(),signOut:vi.fn()}}}));
vi.mock("../lib/adminApi",async(importOriginal)=>{const original=await importOriginal<typeof import("../lib/adminApi")>();return{...original,searchDisputes:vi.fn(),searchSellers:vi.fn(),searchProducts:vi.fn(),getDisputeDetail:vi.fn(),resolveDispute:vi.fn(),moderateProduct:vi.fn()}});
const id=(suffix:string)=>`10000000-0000-4000-8000-${suffix.padStart(12,"0")}`;
const dispute=vi.mocked(searchDisputes),sellers=vi.mocked(searchSellers),products=vi.mocked(searchProducts);
const remoteDisputeDetail={dispute:{id:id("1"),status:"open",reason_code:"not_received",buyer_note:null,created_at:"2026-08-16T12:00:00Z",resolved_at:null},order:{id:id("2"),order_number:"ORD-QA",status:"shipped",currency:"BDAG",total:"35.00000000",created_at:"2026-08-16T11:00:00Z"},buyer:{id:id("7"),username:"buyer",display_name:"Buyer"},seller:{id:id("4"),display_name:"Seller",status:"approved"},store:{id:id("5"),name:"Store",slug:"store",status:"active"},payment:{id:id("8"),status:"paid",currency:"BDAG",gross_amount:"35.00000000",paid_at:"2026-08-16T11:01:00Z",refunded_at:null},allocation:{id:id("9"),status:"held",gross_amount:"35.00000000",platform_fee_amount:"3.50000000",seller_net_amount:"31.50000000",creator_commission_amount:"0.00000000",released_at:null,refunded_at:null},shipment:{status:"shipped",carrier_name:"Carrier",tracking_number:"TRACK",shipped_at:"2026-08-16T11:30:00Z",delivered_at:null},settlement:null,settlement_legs:[],reversal:null,reversal_legs:[],creator_attributions:[],creator_allocations:[],review_actions:[],final_decision:null,timeline:[],admin_actions:[]};

beforeEach(()=>{vi.clearAllMocks();vi.spyOn(window,"confirm").mockReturnValue(true)});

describe("B8B operation lists",()=>{
  it("renders bounded disputes",async()=>{dispute.mockResolvedValue({disputes:[{id:id("1"),status:"open",reason_code:"not_received",created_at:"2026-08-14T12:00:00Z",resolved_at:null,order_id:id("2"),order_number:"ORD-OPS",order_status:"shipped",buyer_name:"Buyer",seller_name:"Seller",store_id:id("3"),store_name:"Store",payment_status:"paid",allocation_status:"held",settled:false,reversed:false}],next_cursor:null,page_size:1});render(<MemoryRouter><MarketplaceDisputesPage/></MemoryRouter>);expect(await screen.findByText("ORD-OPS")).toBeInTheDocument();expect(dispute).toHaveBeenCalledWith(expect.objectContaining({limit:50}))});
  it("renders seller operational state",async()=>{sellers.mockResolvedValue({sellers:[{id:id("4"),status:"suspended",display_name:"Seller Ops",application_note:null,approved_at:null,suspended_at:"2026-08-14T12:00:00Z",suspension_reason:"risk",created_at:"2026-08-13T12:00:00Z",username:"seller",profile_display_name:"Seller",store_id:id("5"),store_name:"Store",store_status:"suspended",product_count:2,order_count:3,open_disputes:1}],next_cursor:null,page_size:1});render(<MemoryRouter><MarketplaceSellersPage/></MemoryRouter>);expect(await screen.findByText("Seller Ops")).toBeInTheDocument();expect(screen.getAllByText("suspended").length).toBeGreaterThan(1)});
  it("renders product moderation without edit controls",async()=>{products.mockResolvedValue({products:[{id:id("6"),title:"Product Ops",status:"draft",moderation_status:"rejected",moderation_reason:"policy",product_type:"physical",currency:"BDAG",price:"10.00000000",published_at:null,created_at:"2026-08-14T12:00:00Z",seller_id:id("4"),seller_name:"Seller",store_id:id("5"),store_name:"Store",store_status:"active",variant_count:1,available_units:5}],next_cursor:null,page_size:1});render(<MemoryRouter><MarketplaceProductsPage/></MemoryRouter>);expect(await screen.findByText("Product Ops")).toBeInTheDocument();expect(screen.queryByText(/editar precio/i)).not.toBeInTheDocument()});
});

describe("B8B validated authority UX",()=>{
  it("accepts the canonical dispute payment shape without inventing escrow",()=>{const parsed=validateDisputeDetail(structuredClone(remoteDisputeDetail));expect(parsed.payment).toMatchObject({gross_amount:"35.00000000",escrow_amount:null});expect((parsed.payment as Record<string,unknown>).escrow_amount).not.toBe(remoteDisputeDetail.order.total)});
  it("keeps required dispute money and identity fields fail closed",()=>{const badMoney=structuredClone(remoteDisputeDetail);badMoney.payment.gross_amount="NaN";expect(()=>validateDisputeDetail(badMoney)).toThrow("payment.gross_amount");const badId=structuredClone(remoteDisputeDetail);badId.dispute.id="bad";expect(()=>validateDisputeDetail(badId)).toThrow("dispute.id")});
  it("renders a validated real-shape dispute detail",async()=>{const api=await import("../lib/adminApi");vi.mocked(api.getDisputeDetail).mockResolvedValue(validateDisputeDetail(structuredClone(remoteDisputeDetail)));render(<MemoryRouter initialEntries={[`/marketplace/disputes/${id("1")}`]}><Routes><Route path="/marketplace/disputes/:id" element={<MarketplaceDisputeDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("ORD-QA")).toBeInTheDocument();expect(screen.getByText("Pago: paid")).toBeInTheDocument()});
  it("requires reason, app confirmation, and preserves the command key across transport retry",async()=>{const api=await import("../lib/adminApi");vi.mocked(api.getDisputeDetail).mockResolvedValue({dispute:{id:id("1"),status:"open",reason_code:"not_received",buyer_note:null,created_at:"2026-08-14T12:00:00Z",resolved_at:null},order:{id:id("2"),order_number:"ORD-OPS",status:"shipped",currency:"BDAG",total:"10.00000000",created_at:"2026-08-14T12:00:00Z"},buyer:{id:id("7"),username:"buyer",display_name:"Buyer"},seller:{id:id("4"),display_name:"Seller",status:"approved"},store:{id:id("5"),name:"Store",slug:"store",status:"active"},payment:null,allocation:null,shipment:null,settlement:null,settlement_legs:[],reversal:null,reversal_legs:[],creator_attributions:[],creator_allocations:[],review_actions:[],final_decision:null,timeline:[],admin_actions:[]});vi.mocked(resolveDispute).mockRejectedValueOnce(new Error("transport_uncertain")).mockResolvedValue({kind:"resolved"});render(<MemoryRouter initialEntries={[`/marketplace/disputes/${id("1")}`]}><Routes><Route path="/marketplace/disputes/:id" element={<MarketplaceDisputeDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("ORD-OPS")).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText("Acción"),"refund_buyer");await userEvent.click(screen.getByRole("button",{name:"Revisar operación"}));expect(screen.getByText("El motivo es obligatorio.")).toBeInTheDocument();expect(resolveDispute).not.toHaveBeenCalled();await userEvent.type(screen.getByLabelText("Motivo"),"support_refund");await userEvent.click(screen.getByRole("button",{name:"Revisar operación"}));expect(resolveDispute).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"Reembolsar al comprador"}));expect(await screen.findByText("transport_uncertain")).toBeInTheDocument();const first=vi.mocked(resolveDispute).mock.calls[0][0];await userEvent.click(screen.getByRole("button",{name:"Revisar operación"}));await userEvent.click(screen.getByRole("button",{name:"Reembolsar al comprador"}));await waitFor(()=>expect(resolveDispute).toHaveBeenCalledTimes(2));const second=vi.mocked(resolveDispute).mock.calls[1][0];expect(second.idempotencyKey).toBe(first.idempotencyKey);expect(second).toEqual(expect.objectContaining({id:id("1"),outcome:"refund_buyer",reason:"support_refund"}))});
  it("rejects malformed nested B8B payloads",()=>{expect(()=>validateDisputeDetail({dispute:{id:"bad"}})).toThrow("Respuesta inválida");expect(()=>validateSellerDetail({seller:{id:"bad"}})).toThrow("Respuesta inválida");expect(()=>validateProductDetail({product:{id:"bad"}})).toThrow("Respuesta inválida")});
  it("never submits financial authority fields",async()=>{vi.mocked(moderateProduct).mockResolvedValue({});const source=resolveDispute.toString()+moderateProduct.toString();expect(source).not.toMatch(/gross_amount|commission_bps|ledger_account|refund_amount/)});
});
