import React from'react';
import{Pressable,StyleSheet,Text,useWindowDimensions,View}from'react-native';
import{MaterialIcons}from'@expo/vector-icons';
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme';
import type{MarketplaceDailyAnalyticsRow}from'@/services/marketplaceAnalyticsService';
import{formatBDAG}from'@/services/marketplaceSellerCenterCore.mjs';

export function SellerRangeSelector({value,onChange}:{value:number;onChange:(days:number)=>void}){return <View style={s.range} accessibilityRole="tablist">{[7,30,90].map(days=><Pressable key={days} accessibilityRole="tab" accessibilityState={{selected:value===days}} accessibilityLabel={`${days} días`} onPress={()=>onChange(days)} style={[s.rangeItem,value===days&&s.rangeActive]}><Text style={[s.rangeText,value===days&&s.rangeTextActive]}>{days} días</Text></Pressable>)}</View>}
export function SellerMetricCard({label,value,helper,accent}:{label:string;value:string;helper?:string;accent?:boolean}){const{width}=useWindowDimensions();return <View style={[s.metric,width<=360&&s.metricCompact,accent&&s.metricAccent]} accessible accessibilityLabel={`${label}: ${value}`}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.68}>{value}</Text>{helper?<Text style={s.metricHelper}>{helper}</Text>:null}</View>}
export function SellerSectionHeader({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={s.sectionHeader}><Text style={s.sectionTitle}>{title}</Text>{action&&onPress?<Pressable accessibilityRole="button" accessibilityLabel={`${action}: ${title}`} onPress={onPress} hitSlop={8}><Text style={s.sectionAction}>{action}</Text></Pressable>:null}</View>}
export function SellerQuickAction({icon,label,onPress}:{icon:React.ComponentProps<typeof MaterialIcons>['name'];label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[s.quick,pressed&&s.pressed]}><View style={s.quickIcon}><MaterialIcons name={icon} size={22} color={Colors.primaryLight}/></View><Text style={s.quickLabel}>{label}</Text></Pressable>}
export function SellerEmptyState({title,body,action,onPress}:{title:string;body?:string;action?:string;onPress?:()=>void}){return <View style={s.empty}><MaterialIcons name="insights" size={28} color={Colors.textSubtle}/><Text style={s.emptyTitle}>{title}</Text>{body?<Text style={s.emptyBody}>{body}</Text>:null}{action&&onPress?<Pressable accessibilityRole="button" onPress={onPress} style={s.emptyButton}><Text style={s.emptyButtonText}>{action}</Text></Pressable>:null}</View>}
export function SellerSalesChart({rows}:{rows:MarketplaceDailyAnalyticsRow[]}){const max=Math.max(0,...rows.map(row=>Number(row.gmv_bdag)));const visible=rows.length>31?rows.filter((_,index)=>index%3===0||index===rows.length-1):rows;return <View accessible accessibilityRole="image" accessibilityLabel={`Gráfico de ventas brutas. Máximo ${formatBDAG(max)}.`} style={s.chart}><View style={s.chartPlot}>{visible.map(row=><View key={row.event_day} style={s.barSlot}><View style={[s.bar,{height:max>0?Math.max(2,72*Number(row.gmv_bdag)/max):2,backgroundColor:max>0?Colors.primary:Colors.border}]}/></View>)}</View><View style={s.chartLabels}><Text style={s.chartLabel}>{rows[0]?.event_day.slice(5)??''}</Text><Text style={s.chartMax}>{formatBDAG(max)} máx.</Text><Text style={s.chartLabel}>{rows.at(-1)?.event_day.slice(5)??''}</Text></View></View>}
export function SellerSkeleton({rows=4}:{rows?:number}){return <View accessibilityLabel="Cargando" style={s.skeleton}>{Array.from({length:rows},(_,index)=><View key={index} style={[s.skeletonRow,{opacity:1-index*.12}]}/>)}</View>}

const s=StyleSheet.create({range:{flexDirection:'row',backgroundColor:Colors.surfaceElevated,borderRadius:Radius.full,padding:4,gap:4},rangeItem:{minHeight:44,minWidth:70,paddingHorizontal:12,alignItems:'center',justifyContent:'center',borderRadius:Radius.full},rangeActive:{backgroundColor:Colors.primary},rangeText:{color:Colors.textSecondary,fontSize:FontSize.sm,fontWeight:FontWeight.semibold},rangeTextActive:{color:Colors.textOnBrand},metric:{width:'48.5%',minHeight:112,padding:Spacing.md,borderRadius:Radius.lg,backgroundColor:Colors.surfaceElevated,borderWidth:1,borderColor:Colors.borderSubtle},metricCompact:{width:'100%'},metricAccent:{borderColor:Colors.primaryGlow,backgroundColor:Colors.primaryDim},metricLabel:{color:Colors.textSecondary,fontSize:FontSize.sm},metricValue:{color:Colors.textPrimary,fontSize:FontSize.xxl,fontWeight:FontWeight.extrabold,marginTop:Spacing.sm,fontVariant:['tabular-nums']},metricHelper:{color:Colors.textSubtle,fontSize:FontSize.xs,marginTop:4,lineHeight:15},sectionHeader:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:Spacing.sm},sectionTitle:{flexShrink:1,color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold},sectionAction:{color:Colors.primaryLight,fontWeight:FontWeight.semibold},quick:{width:'23%',minHeight:88,alignItems:'center',justifyContent:'center',gap:8,borderRadius:Radius.lg,backgroundColor:Colors.surfaceElevated,borderWidth:1,borderColor:Colors.borderSubtle},quickCompact:{width:'48%'},pressed:{opacity:.72},quickIcon:{width:44,height:44,borderRadius:22,backgroundColor:Colors.primaryDim,alignItems:'center',justifyContent:'center'},quickLabel:{color:Colors.textPrimary,fontSize:FontSize.xs,fontWeight:FontWeight.semibold,textAlign:'center'},empty:{padding:Spacing.lg,alignItems:'center',gap:6,backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg},emptyTitle:{color:Colors.textPrimary,fontWeight:FontWeight.bold,textAlign:'center'},emptyBody:{color:Colors.textSecondary,textAlign:'center',lineHeight:19},emptyButton:{minHeight:44,justifyContent:'center',paddingHorizontal:Spacing.md},emptyButtonText:{color:Colors.primaryLight,fontWeight:FontWeight.bold},chart:{backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg,padding:Spacing.md},chartPlot:{height:82,flexDirection:'row',alignItems:'flex-end',gap:3,borderBottomWidth:1,borderBottomColor:Colors.border},barSlot:{flex:1,height:76,justifyContent:'flex-end'},bar:{width:'100%',borderTopLeftRadius:3,borderTopRightRadius:3},chartLabels:{flexDirection:'row',justifyContent:'space-between',marginTop:8},chartLabel:{color:Colors.textSubtle,fontSize:FontSize.xs},chartMax:{color:Colors.textSecondary,fontSize:FontSize.xs},skeleton:{gap:Spacing.sm},skeletonRow:{height:82,borderRadius:Radius.lg,backgroundColor:Colors.surfaceHighlight}});
