import {getSupabaseClient} from '@/template';
import {
  normalizeShippingAddress,
  parseMarketplaceCheckoutReservation,
  type CreateCheckoutReservationResult,
  type ShippingAddressInput,
} from './marketplaceOrderService';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const HTTPS=/^https:\/\/[^\s]+$/i;

export type LiveProductAvailability='available'|'out_of_stock'|'product_unavailable'|'live_ended';
export interface LiveSessionProduct{id:string;productId:string;storeId:string;storeName:string;sellerName:string;title:string;description:string;imageUrl:string|null;minPrice:number;maxPrice:number;compareAtPrice:number|null;activeVariantCount:number;availableQuantity:number;featuredVariantId:string|null;isFeatured:boolean;position:number;availability:LiveProductAvailability}
export interface LiveProductCandidate{productId:string;storeId:string;storeName:string;title:string;imageUrl:string|null;minPrice:number;maxPrice:number;activeVariantCount:number;availableQuantity:number;pinId:string|null;isPinned:boolean;isFeatured:boolean;updatedAt:string}
export interface LiveCandidateCursor{updatedAt:string;id:string}
export interface LiveCandidatePage{items:LiveProductCandidate[];nextCursor:LiveCandidateCursor|null}
export type LiveCommerceErrorCode='live_commerce_auth_required'|'live_commerce_host_not_eligible'|'live_commerce_product_unavailable'|'live_commerce_out_of_stock'|'live_commerce_invalid_variant'|'live_commerce_pin_limit'|'live_commerce_pin_not_found'|'live_commerce_live_ended'|'live_commerce_pin_unavailable'|'live_commerce_invalid_input'|'marketplace_active_checkout_exists'|'marketplace_idempotency_conflict'|'marketplace_own_product_forbidden'|'marketplace_insufficient_inventory'|'marketplace_invalid_shipping_address'|'live_commerce_transport'|'live_commerce_unknown';
const CODES:LiveCommerceErrorCode[]=['live_commerce_auth_required','live_commerce_host_not_eligible','live_commerce_product_unavailable','live_commerce_out_of_stock','live_commerce_invalid_variant','live_commerce_pin_limit','live_commerce_pin_not_found','live_commerce_live_ended','live_commerce_pin_unavailable','live_commerce_invalid_input','marketplace_active_checkout_exists','marketplace_idempotency_conflict','marketplace_own_product_forbidden','marketplace_insufficient_inventory','marketplace_invalid_shipping_address'];
export class LiveCommerceError extends Error{constructor(public code:LiveCommerceErrorCode){super(code);this.name='LiveCommerceError';}}

const db=()=>getSupabaseClient();
const finite=(value:unknown)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new LiveCommerceError('live_commerce_unknown');return n;};
const safeImage=(value:unknown)=>typeof value==='string'&&HTTPS.test(value)?value:null;
const uuid=(value:string)=>{if(!UUID.test(value))throw new LiveCommerceError('live_commerce_invalid_input');return value;};
const rpcError=(rpc:string,error:unknown):never=>{const e=error as {code?:unknown;message?:unknown};const message=typeof e?.message==='string'?e.message:'';const business=CODES.find(code=>message===code||message.includes(code));const transport=!e?.code&&/network request failed|failed to fetch|fetch failed|networkerror|timeout|connection/i.test(message);if(__DEV__)console.error('[LiveCommerce] request failed',{rpc,code:typeof e?.code==='string'?e.code.slice(0,40):null,kind:business?'business':transport?'transport':'unknown'});throw new LiveCommerceError(business??(transport?'live_commerce_transport':'live_commerce_unknown'));};
const product=(raw:unknown):LiveSessionProduct=>{const r=raw as Record<string,unknown>;const availability=String(r.availability)as LiveProductAvailability;if(!UUID.test(String(r.id))||!UUID.test(String(r.product_id))||!['available','out_of_stock','product_unavailable','live_ended'].includes(availability))throw new LiveCommerceError('live_commerce_unknown');return{id:String(r.id),productId:String(r.product_id),storeId:String(r.store_id),storeName:String(r.store_name),sellerName:String(r.seller_name),title:String(r.title),description:String(r.description??''),imageUrl:safeImage(r.image_url),minPrice:finite(r.min_price),maxPrice:finite(r.max_price),compareAtPrice:r.compare_at_price==null?null:finite(r.compare_at_price),activeVariantCount:finite(r.active_variant_count),availableQuantity:finite(r.available_quantity),featuredVariantId:r.featured_variant_id==null?null:String(r.featured_variant_id),isFeatured:r.is_featured===true,position:finite(r.position),availability};};

export async function fetchLiveSessionProducts(sessionId:string){const rpc='fetch_live_session_products';const{data,error}=await db().rpc(rpc,{p_session_id:uuid(sessionId)});if(error)rpcError(rpc,error);if(!Array.isArray(data))throw new LiveCommerceError('live_commerce_unknown');return data.map(product);}
export async function fetchMyLiveProductCandidates(sessionId:string,limit=20,cursor?:LiveCandidateCursor):Promise<LiveCandidatePage>{const effective=Math.min(Math.max(Math.trunc(limit),1),50);if(cursor&&(!UUID.test(cursor.id)||!Number.isFinite(Date.parse(cursor.updatedAt))))throw new LiveCommerceError('live_commerce_invalid_input');const rpc='fetch_my_live_product_candidates';const{data,error}=await db().rpc(rpc,{p_session_id:uuid(sessionId),p_limit:effective,p_before_updated_at:cursor?.updatedAt??null,p_before_id:cursor?.id??null});if(error)rpcError(rpc,error);if(!Array.isArray(data))throw new LiveCommerceError('live_commerce_unknown');const items=data.map(raw=>{const r=raw as Record<string,unknown>;return{productId:String(r.product_id),storeId:String(r.store_id),storeName:String(r.store_name),title:String(r.title),imageUrl:safeImage(r.image_url),minPrice:finite(r.min_price),maxPrice:finite(r.max_price),activeVariantCount:finite(r.active_variant_count),availableQuantity:finite(r.available_quantity),pinId:r.pin_id==null?null:String(r.pin_id),isPinned:r.is_pinned===true,isFeatured:r.is_featured===true,updatedAt:String(r.updated_at)};});const last=items.at(-1);return{items,nextCursor:items.length===effective&&last?{updatedAt:last.updatedAt,id:last.productId}:null};}
async function command(rpc:string,args:Record<string,unknown>){const{data,error}=await db().rpc(rpc,args);if(error)rpcError(rpc,error);return data;}
export const pinLiveProduct=(sessionId:string,productId:string,featuredVariantId:string|null,idempotencyKey:string)=>command('pin_live_session_product',{p_session_id:uuid(sessionId),p_product_id:uuid(productId),p_featured_variant_id:featuredVariantId?uuid(featuredVariantId):null,p_idempotency_key:uuid(idempotencyKey)});
export const unpinLiveProduct=(sessionId:string,pinId:string,idempotencyKey:string)=>command('unpin_live_session_product',{p_session_id:uuid(sessionId),p_live_session_product_id:uuid(pinId),p_idempotency_key:uuid(idempotencyKey)});
export const featureLiveProduct=(sessionId:string,pinId:string,idempotencyKey:string)=>command('feature_live_session_product',{p_session_id:uuid(sessionId),p_live_session_product_id:uuid(pinId),p_idempotency_key:uuid(idempotencyKey)});
export async function createLiveCheckoutReservation(sessionId:string,pinId:string,variantId:string,quantity:number,address:ShippingAddressInput,idempotencyKey:string):Promise<CreateCheckoutReservationResult>{if(!Number.isInteger(quantity)||quantity<1)throw new LiveCommerceError('live_commerce_invalid_input');const a=normalizeShippingAddress(address);const rpc='create_live_marketplace_checkout_reservation';const{data,error}=await db().rpc(rpc,{p_session_id:uuid(sessionId),p_live_session_product_id:uuid(pinId),p_variant_id:uuid(variantId),p_quantity:quantity,p_shipping_address:{recipient_name:a.recipientName,line1:a.line1,line2:a.line2??null,city:a.city,region:a.region,postal_code:a.postalCode,country:a.country,phone:a.phone??null},p_idempotency_key:uuid(idempotencyKey)});if(error)rpcError(rpc,error);return parseMarketplaceCheckoutReservation(data);}
