import {getSupabaseClient} from '@/template';

export type MarketplaceOrderStatus='confirmed'|'processing'|'shipped'|'delivered'|'cancelled'|'refunded'|'partially_refunded';
export interface MarketplaceOrderEvent{id:string;eventType:string;fromStatus:string|null;toStatus:string|null;actorRole:string;createdAt:string}
export interface MarketplaceShipment{id:string|null;status:string;carrierName:string;serviceLevel:string|null;trackingNumber:string;trackingUrl:string|null;sellerNote:string|null;shippedAt:string}
export interface MarketplaceHeldAllocation{grossAmount:number;platformFeeAmount:number;sellerNetAmount:number;status:'held'|'released'|'refunded'|'partially_refunded'}
export interface MarketplaceOrderListItem{id:string;orderNumber:string;checkoutId:string;checkoutReference:string;status:MarketplaceOrderStatus;storeId:string;storeName:string;total:number;currency:'BDAG';createdAt:string;confirmedAt:string|null;processingAt:string|null;shippedAt:string|null;firstItemTitle:string|null;firstItemImage:string|null;distinctLines:number;totalQuantity:number;carrierName:string|null;trackingNumber:string|null;recipientName?:string;city?:string;region?:string;country?:string;allocation?:MarketplaceHeldAllocation}
export interface MarketplaceOrderDetail{order:{id:string;orderNumber:string;checkoutId:string;checkoutReference:string;status:MarketplaceOrderStatus;currency:'BDAG';total:number;createdAt:string;confirmedAt:string|null;processingAt:string|null;shippedAt:string|null;fulfillmentVersion:number};store:{id:string;name:string;slug:string};payment:{status:string;paidAt:string};allocation:MarketplaceHeldAllocation|null;shippingAddress:{recipientName:string;line1:string;line2:string|null;city:string;region:string;postalCode:string;country:string;phone:string|null};items:{id:string;productTitle:string;variantTitle:string|null;sku:string;options:{name?:string;value:string}[];imageUrl:string|null;unitPrice:number;quantity:number;lineTotal:number}[];shipment:MarketplaceShipment|null;events:MarketplaceOrderEvent[];escrowProtected:boolean}
export interface MarketplaceOrderPage{items:MarketplaceOrderListItem[];nextCursor:{createdAt:string;id:string}|null}
export interface ShipmentInput{carrierName:string;serviceLevel?:string;trackingNumber:string;trackingUrl?:string;sellerNote?:string}
export type MarketplaceFulfillmentErrorCode='marketplace_invalid_cursor'|'marketplace_order_not_found'|'marketplace_order_not_owned'|'marketplace_seller_not_approved'|'marketplace_store_inactive'|'marketplace_order_not_paid'|'marketplace_order_not_fulfillable'|'marketplace_invalid_shipment'|'marketplace_fulfillment_idempotency_conflict'|'marketplace_fulfillment_transport'|'marketplace_fulfillment_unknown';
export class MarketplaceFulfillmentError extends Error{constructor(public code:MarketplaceFulfillmentErrorCode){super(code);}}
const db=()=>getSupabaseClient();const num=(v:unknown)=>{const n=Number(v);if(!Number.isFinite(n)||n<0)throw new MarketplaceFulfillmentError('marketplace_fulfillment_unknown');return n;};
export const isSafeTrackingUrl=(value:string|null|undefined)=>!value||/^https:\/\/[^\s]+$/i.test(value);
function fail(rpc:string,error:{code?:string;message?:string;details?:string;hint?:string}):never{const known=(error.message??'').match(/marketplace_[a-z_]+/)?.[0] as MarketplaceFulfillmentErrorCode|undefined;if(__DEV__)console.error('[MarketplaceFulfillment] RPC failed',{rpc,code:error.code,message:error.message?.slice(0,200),details:error.details?.slice(0,200),hint:error.hint?.slice(0,200)});throw new MarketplaceFulfillmentError(known??'marketplace_fulfillment_unknown');}
function shipment(v:unknown):MarketplaceShipment|null{if(!v)return null;const x=v as Record<string,unknown>;const url=x.tracking_url==null?null:String(x.tracking_url);if(!isSafeTrackingUrl(url))throw new MarketplaceFulfillmentError('marketplace_fulfillment_unknown');return{id:x.id==null?null:String(x.id),status:String(x.status),carrierName:String(x.carrier_name),serviceLevel:x.service_level==null?null:String(x.service_level),trackingNumber:String(x.tracking_number),trackingUrl:url,sellerNote:x.seller_note==null?null:String(x.seller_note),shippedAt:String(x.shipped_at)};}
function detail(v:unknown):MarketplaceOrderDetail{const x=v as Record<string,unknown>,o=x.order as Record<string,unknown>,s=x.store as Record<string,unknown>,p=x.payment as Record<string,unknown>,a=x.shipping_address as Record<string,unknown>;if(!o||!s||!p||!a||o.currency!=='BDAG'||!Array.isArray(x.items)||!Array.isArray(x.events))throw new MarketplaceFulfillmentError('marketplace_fulfillment_unknown');const raw=x.allocation as Record<string,unknown>|null;return{order:{id:String(o.id),orderNumber:String(o.order_number),checkoutId:String(o.checkout_id),checkoutReference:String(o.checkout_reference),status:String(o.status) as MarketplaceOrderStatus,currency:'BDAG',total:num(o.total),createdAt:String(o.created_at),confirmedAt:o.confirmed_at==null?null:String(o.confirmed_at),processingAt:o.processing_at==null?null:String(o.processing_at),shippedAt:o.shipped_at==null?null:String(o.shipped_at),fulfillmentVersion:num(o.fulfillment_version)},store:{id:String(s.id),name:String(s.name),slug:String(s.slug)},payment:{status:String(p.status),paidAt:String(p.paid_at)},allocation:raw?{grossAmount:num(raw.gross_amount),platformFeeAmount:num(raw.platform_fee_amount),sellerNetAmount:num(raw.seller_net_amount),status:String(raw.status) as MarketplaceHeldAllocation['status']}:null,shippingAddress:{recipientName:String(a.recipient_name),line1:String(a.line1),line2:a.line2==null?null:String(a.line2),city:String(a.city),region:String(a.region),postalCode:String(a.postal_code),country:String(a.country),phone:a.phone==null?null:String(a.phone)},items:(x.items as Record<string,unknown>[]).map(i=>({id:String(i.id),productTitle:String(i.product_title),variantTitle:i.variant_title==null?null:String(i.variant_title),sku:String(i.sku),options:Array.isArray(i.options)?i.options as {name?:string;value:string}[]:[],imageUrl:i.image_url==null?null:String(i.image_url),unitPrice:num(i.unit_price),quantity:num(i.quantity),lineTotal:num(i.line_total)})),shipment:shipment(x.shipment),events:(x.events as Record<string,unknown>[]).map(e=>({id:String(e.id),eventType:String(e.event_type),fromStatus:e.from_status==null?null:String(e.from_status),toStatus:e.to_status==null?null:String(e.to_status),actorRole:String(e.actor_role),createdAt:String(e.created_at)})),escrowProtected:x.escrow_protected===true};}
function list(v:unknown,effectiveLimit:number):MarketplaceOrderPage{if(!Array.isArray(v))throw new MarketplaceFulfillmentError('marketplace_fulfillment_unknown');const items=v.map((x:Record<string,unknown>)=>({id:String(x.id),orderNumber:String(x.order_number),checkoutId:String(x.checkout_id),checkoutReference:String(x.checkout_reference),status:String(x.status) as MarketplaceOrderStatus,storeId:String(x.store_id),storeName:String(x.store_name),total:num(x.total),currency:'BDAG' as const,createdAt:String(x.created_at),confirmedAt:x.confirmed_at==null?null:String(x.confirmed_at),processingAt:x.processing_at==null?null:String(x.processing_at),shippedAt:x.shipped_at==null?null:String(x.shipped_at),firstItemTitle:x.first_item_title==null?null:String(x.first_item_title),firstItemImage:x.first_item_image==null?null:String(x.first_item_image),distinctLines:num(x.distinct_lines),totalQuantity:num(x.total_quantity),carrierName:x.carrier_name==null?null:String(x.carrier_name),trackingNumber:x.tracking_number==null?null:String(x.tracking_number),recipientName:x.recipient_name==null?undefined:String(x.recipient_name),city:x.city==null?undefined:String(x.city),region:x.region==null?undefined:String(x.region),country:x.country==null?undefined:String(x.country),allocation:x.gross_amount==null?undefined:{grossAmount:num(x.gross_amount),platformFeeAmount:num(x.platform_fee_amount),sellerNetAmount:num(x.seller_net_amount),status:String(x.allocation_status) as MarketplaceHeldAllocation['status']}}));const last=items.at(-1);return{items,nextCursor:items.length===effectiveLimit&&last?{createdAt:last.createdAt,id:last.id}:null};}
async function rpc(name:string,args:Record<string,unknown>){const{data,error}=await db().rpc(name,args);if(error)fail(name,error);return data;}
const validCursor=(cursor?:{createdAt:string;id:string})=>{if(!cursor)return undefined;if(!Number.isFinite(Date.parse(cursor.createdAt))||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(cursor.id))throw new MarketplaceFulfillmentError('marketplace_invalid_cursor');return cursor;};
export async function fetchBuyerOrders(filters:{status?:MarketplaceOrderStatus|null;limit?:number;cursor?:{createdAt:string;id:string}}={}):Promise<MarketplaceOrderPage>{const limit=Math.min(50,Math.max(1,filters.limit??20)),cursor=validCursor(filters.cursor);return list(await rpc('fetch_my_marketplace_orders',{p_status:filters.status??null,p_limit:limit,p_before_created_at:cursor?.createdAt??null,p_before_id:cursor?.id??null}),limit);}
export async function fetchSellerOrders(filters:{status?:MarketplaceOrderStatus|null;limit?:number;cursor?:{createdAt:string;id:string}}={}):Promise<MarketplaceOrderPage>{const limit=Math.min(50,Math.max(1,filters.limit??20)),cursor=validCursor(filters.cursor);return list(await rpc('fetch_my_marketplace_sales',{p_status:filters.status??null,p_limit:limit,p_before_created_at:cursor?.createdAt??null,p_before_id:cursor?.id??null}),limit);}
export async function fetchBuyerOrder(id:string){return detail(await rpc('fetch_my_marketplace_order',{p_order_id:id}));}export async function fetchSellerOrder(id:string){return detail(await rpc('fetch_my_marketplace_sale',{p_order_id:id}));}
export async function startSellerOrderProcessing(id:string,key:string){return detail(await rpc('seller_start_marketplace_order_processing',{p_order_id:id,p_idempotency_key:key}));}
export async function shipSellerOrder(id:string,input:ShipmentInput,key:string){if(input.carrierName.trim().length<2||input.trackingNumber.trim().length<2||!isSafeTrackingUrl(input.trackingUrl))throw new MarketplaceFulfillmentError('marketplace_invalid_shipment');return detail(await rpc('seller_ship_marketplace_order',{p_order_id:id,p_carrier_name:input.carrierName,p_service_level:input.serviceLevel??null,p_tracking_number:input.trackingNumber,p_tracking_url:input.trackingUrl??null,p_seller_note:input.sellerNote??null,p_idempotency_key:key}));}
