import {getSupabaseClient} from '@/template';

export type MarketplaceSettlementErrorCode='marketplace_delivery_invalid_input'|'marketplace_order_not_found'|'marketplace_order_not_owned'|'marketplace_order_not_shipped'|'marketplace_shipment_not_shipped'|'marketplace_order_not_paid'|'marketplace_allocation_not_held'|'marketplace_settlement_integrity_error'|'marketplace_settlement_idempotency_conflict'|'marketplace_escrow_insufficient_balance'|'marketplace_settlement_rate_limited'|'marketplace_settlement_transport'|'marketplace_settlement_unknown';
export interface MarketplaceSettlementReceipt{settlement:{id:string;status:'completed';orderId:string;currency:'BDAG';grossAmount:number;confirmedAt:string;releasedAt:string};order:{id:string;status:'delivered';deliveredAt:string};shipment:{status:'delivered';deliveredAt:string};allocation:{status:'released';releasedAt:string}}
export class MarketplaceSettlementError extends Error{constructor(public code:MarketplaceSettlementErrorCode){super(code);this.name='MarketplaceSettlementError';}}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const known:MarketplaceSettlementErrorCode[]=['marketplace_delivery_invalid_input','marketplace_order_not_found','marketplace_order_not_owned','marketplace_order_not_shipped','marketplace_shipment_not_shipped','marketplace_order_not_paid','marketplace_allocation_not_held','marketplace_settlement_integrity_error','marketplace_settlement_idempotency_conflict','marketplace_escrow_insufficient_balance','marketplace_settlement_rate_limited'];
const amount=(value:unknown)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new MarketplaceSettlementError('marketplace_settlement_unknown');return n;};
function parse(value:unknown):MarketplaceSettlementReceipt{if(!value||typeof value!=='object')throw new MarketplaceSettlementError('marketplace_settlement_unknown');const x=value as Record<string,unknown>,s=x.settlement as Record<string,unknown>,o=x.order as Record<string,unknown>,sh=x.shipment as Record<string,unknown>,a=x.allocation as Record<string,unknown>;if(!s||!o||!sh||!a||s.status!=='completed'||s.currency!=='BDAG'||o.status!=='delivered'||sh.status!=='delivered'||a.status!=='released')throw new MarketplaceSettlementError('marketplace_settlement_unknown');return{settlement:{id:String(s.id),status:'completed',orderId:String(s.order_id),currency:'BDAG',grossAmount:amount(s.gross_amount),confirmedAt:String(s.confirmed_at),releasedAt:String(s.released_at)},order:{id:String(o.id),status:'delivered',deliveredAt:String(o.delivered_at)},shipment:{status:'delivered',deliveredAt:String(sh.delivered_at)},allocation:{status:'released',releasedAt:String(a.released_at)}};}
export async function confirmMarketplaceOrderDelivery(orderId:string,idempotencyKey:string):Promise<MarketplaceSettlementReceipt>{
 if(!UUID.test(orderId)||!UUID.test(idempotencyKey))throw new MarketplaceSettlementError('marketplace_delivery_invalid_input');
 try{const{data,error}=await getSupabaseClient().functions.invoke('bdag-ledger',{body:{action:'marketplace_order_confirm_delivery',order_id:orderId,idempotency_key:idempotencyKey}});if(error){const response=(error as{context?:unknown}).context;if(response instanceof Response){const payload=await response.clone().json().catch(()=>null);const code=known.includes(payload?.error)?payload.error as MarketplaceSettlementErrorCode:'marketplace_settlement_unknown';throw new MarketplaceSettlementError(code);}throw error;}if(!data?.success){const code=known.includes(data?.error)?data.error as MarketplaceSettlementErrorCode:'marketplace_settlement_unknown';throw new MarketplaceSettlementError(code);}return parse(data.data);}catch(error){if(error instanceof MarketplaceSettlementError)throw error;const message=error instanceof Error?error.message:'';const transport=/network|fetch|timeout|timed out|connection|socket|offline/i.test(message);if(__DEV__)console.error('[MarketplaceSettlement] gateway failed',{action:'marketplace_order_confirm_delivery',code:transport?'transport':'unknown',message:message.slice(0,200)});throw new MarketplaceSettlementError(transport?'marketplace_settlement_transport':'marketplace_settlement_unknown');}
}
