import {getSupabaseClient} from '@/template';

export type MarketplacePaymentErrorCode='marketplace_checkout_not_found'|'marketplace_checkout_not_payable'|'marketplace_checkout_cancelled'|'marketplace_checkout_expired'|'marketplace_checkout_integrity_error'|'marketplace_insufficient_bdag_balance'|'marketplace_payment_idempotency_conflict'|'marketplace_payment_already_processed'|'marketplace_payment_transport'|'marketplace_payment_unknown';
export interface MarketplacePaymentOrderAllocation{id:string;orderNumber:string;status:string;grossAmount:number;platformFeeAmount:number;sellerNetAmount:number;allocationStatus:'held'|'released'|'partially_refunded'|'refunded'}
export interface MarketplacePaymentReceipt{payment:{id:string;checkoutId:string;status:'paid';currency:'BDAG';grossAmount:number;escrowAmount:number;feeBps:number;financialTransactionId:string;paidAt:string};checkout:{id:string;reference:string;status:'paid';total:number;currency:'BDAG'};buyer:{newBdagBalance:number};orders:MarketplacePaymentOrderAllocation[];inventory:{consumedReservations:number;unitsConsumed:number}}
const codes:MarketplacePaymentErrorCode[]=['marketplace_checkout_not_found','marketplace_checkout_not_payable','marketplace_checkout_cancelled','marketplace_checkout_expired','marketplace_checkout_integrity_error','marketplace_insufficient_bdag_balance','marketplace_payment_idempotency_conflict','marketplace_payment_already_processed'];
export class MarketplacePaymentError extends Error{constructor(public code:MarketplacePaymentErrorCode,public required?:number,public available?:number){super(code);this.name='MarketplacePaymentError';}}
const finite=(value:unknown)=>{const number=Number(value);if(!Number.isFinite(number)||number<0)throw new MarketplacePaymentError('marketplace_payment_unknown');return number;};
const mapReceipt=(value:unknown):MarketplacePaymentReceipt=>{if(!value||typeof value!=='object')throw new MarketplacePaymentError('marketplace_payment_unknown');const root=value as Record<string,unknown>;const p=root.payment as Record<string,unknown>;const c=root.checkout as Record<string,unknown>;const b=root.buyer as Record<string,unknown>;if(!p||!c||!b||p.currency!=='BDAG'||c.currency!=='BDAG'||p.status!=='paid'||c.status!=='paid'||!Array.isArray(root.orders))throw new MarketplacePaymentError('marketplace_payment_unknown');return {payment:{id:String(p.id),checkoutId:String(p.checkout_id),status:'paid',currency:'BDAG',grossAmount:finite(p.gross_amount),escrowAmount:finite(p.escrow_amount),feeBps:finite(p.fee_bps),financialTransactionId:String(p.financial_transaction_id),paidAt:String(p.paid_at)},checkout:{id:String(c.id),reference:String(c.reference),status:'paid',total:finite(c.total),currency:'BDAG'},buyer:{newBdagBalance:finite(b.new_bdag_balance)},orders:root.orders.map(raw=>{const o=raw as Record<string,unknown>;return{id:String(o.id),orderNumber:String(o.order_number),status:String(o.status),grossAmount:finite(o.gross_amount),platformFeeAmount:finite(o.platform_fee_amount),sellerNetAmount:finite(o.seller_net_amount),allocationStatus:String(o.allocation_status) as MarketplacePaymentOrderAllocation['allocationStatus']};}),inventory:{consumedReservations:finite((root.inventory as Record<string,unknown>)?.consumed_reservations),unitsConsumed:finite((root.inventory as Record<string,unknown>)?.units_consumed)}};};

export async function payMarketplaceCheckout(checkoutId:string,idempotencyKey:string):Promise<MarketplacePaymentReceipt>{
 try{const {data,error}=await getSupabaseClient().functions.invoke('bdag-ledger',{body:{action:'marketplace_checkout_pay',checkout_id:checkoutId,idempotency_key:idempotencyKey}});if(error){const response=(error as {context?:unknown}).context;if(response instanceof Response){const payload=await response.clone().json().catch(()=>null);const code=codes.includes(payload?.error)?payload.error as MarketplacePaymentErrorCode:'marketplace_payment_unknown';throw new MarketplacePaymentError(code);}throw error;}if(!data?.success){const code=codes.includes(data?.error)?data.error as MarketplacePaymentErrorCode:'marketplace_payment_unknown';throw new MarketplacePaymentError(code);}return mapReceipt(data.data);}catch(error){if(error instanceof MarketplacePaymentError)throw error;const value=error as {message?:unknown};const message=typeof value?.message==='string'?value.message:'';const transport=/network request failed|failed to fetch|fetch failed|networkerror/i.test(message);if(__DEV__)console.error('[MarketplacePayment] gateway failed',{action:'marketplace_checkout_pay',code:transport?'transport':'unknown',message:message.slice(0,240)});throw new MarketplacePaymentError(transport?'marketplace_payment_transport':'marketplace_payment_unknown');}
}
export async function fetchAuthoritativeBdagBalance():Promise<number>{const {data,error}=await getSupabaseClient().rpc('get_bdag_wallet_balance');if(error)throw error;return finite(data??0);}
