import {getSupabaseClient} from '@/template';

export type MarketplaceSettlementErrorCode='marketplace_delivery_invalid_input'|'marketplace_order_not_found'|'marketplace_order_not_owned'|'marketplace_order_not_shipped'|'marketplace_shipment_not_shipped'|'marketplace_order_not_paid'|'marketplace_allocation_not_held'|'marketplace_settlement_integrity_error'|'marketplace_settlement_idempotency_conflict'|'marketplace_escrow_insufficient_balance'|'marketplace_settlement_rate_limited'|'marketplace_dispute_invalid_input'|'marketplace_dispute_order_state_conflict'|'marketplace_dispute_settlement_completed'|'marketplace_dispute_idempotency_conflict'|'marketplace_settlement_transport'|'marketplace_settlement_unknown';
export interface MarketplaceSettlementReceipt{settlement:{id:string;status:'completed';orderId:string;currency:'BDAG';grossAmount:number;confirmedAt:string;releasedAt:string};order:{id:string;status:'delivered';deliveredAt:string};shipment:{status:'delivered';deliveredAt:string};allocation:{status:'released';releasedAt:string}}
export class MarketplaceSettlementError extends Error{constructor(public code:MarketplaceSettlementErrorCode){super(code);this.name='MarketplaceSettlementError';}}
export type MarketplaceDisputeFinalOutcome='refund_buyer'|'release_seller'|'reject_claim';
export type MarketplaceDisputeResolutionOutcome=MarketplaceDisputeFinalOutcome|'manual_review';
export type MarketplaceDisputeReviewAction='manual_review_requested'|'escalated';
export type MarketplaceDisputeResolutionErrorCode='marketplace_dispute_not_found'|'marketplace_dispute_not_open'|'marketplace_dispute_already_resolved'|'marketplace_dispute_conflicting_decision'|'marketplace_refund_allocation_not_held'|'marketplace_refund_requires_manual_review'|'marketplace_partial_refund_unsupported'|'marketplace_refund_reconciliation_failed'|'marketplace_dispute_resolution_forbidden'|'marketplace_dispute_resolution_auth_required'|'marketplace_refund_payment_not_paid'|'marketplace_refund_order_state_invalid'|'marketplace_refund_already_completed'|'marketplace_dispute_resolution_invalid_input'|'marketplace_dispute_resolution_transport'|'marketplace_dispute_resolution_unknown';
export interface SupportMarketplaceDisputeDetail{dispute:{id:string;status:string;reasonCode:string;createdAt:string};order:{id:string;status:string};payment:{status:string;grossAmount:number};allocation:{status:string;grossAmount:number;sellerNetAmount:number;creatorCommissionAmount:number;platformFeeAmount:number}}
export interface MarketplaceDisputeFinalResolutionResult{kind:'final_resolution';finalDecision:{id:string;disputeId:string;orderId:string;outcome:MarketplaceDisputeFinalOutcome;reasonCode:string;financialResult:Record<string,unknown>;decidedAt:string};dispute:{status:string;resolvedAt:string};order:{status:string};payment:{status:string;grossAmount:number};allocation:{status:string;grossAmount:number;sellerNetAmount:number;creatorCommissionAmount:number;platformFeeAmount:number}}
export interface MarketplaceDisputeIntermediateReviewResult{kind:'intermediate_review';finalDecision:null;reviewAction:{id:string;disputeId:string;orderId:string;action:MarketplaceDisputeReviewAction;reasonCode:string;metadata:Record<string,unknown>;createdAt:string};dispute:{status:'under_review';resolvedAt:null};moneyMoved:false;requiresHumanFollowUp:true}
export type MarketplaceDisputeResolutionResult=MarketplaceDisputeFinalResolutionResult|MarketplaceDisputeIntermediateReviewResult;
export class MarketplaceDisputeResolutionError extends Error{constructor(public code:MarketplaceDisputeResolutionErrorCode,public postgresCode:string|null=null){super(code);this.name='MarketplaceDisputeResolutionError';}}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const known:MarketplaceSettlementErrorCode[]=['marketplace_delivery_invalid_input','marketplace_order_not_found','marketplace_order_not_owned','marketplace_order_not_shipped','marketplace_shipment_not_shipped','marketplace_order_not_paid','marketplace_allocation_not_held','marketplace_settlement_integrity_error','marketplace_settlement_idempotency_conflict','marketplace_escrow_insufficient_balance','marketplace_settlement_rate_limited'];
const disputeCodes:MarketplaceSettlementErrorCode[]=['marketplace_dispute_invalid_input','marketplace_order_not_found','marketplace_order_not_owned','marketplace_dispute_order_state_conflict','marketplace_dispute_settlement_completed','marketplace_dispute_idempotency_conflict'];
const resolutionCodes:MarketplaceDisputeResolutionErrorCode[]=['marketplace_dispute_not_found','marketplace_dispute_not_open','marketplace_dispute_already_resolved','marketplace_dispute_conflicting_decision','marketplace_refund_allocation_not_held','marketplace_refund_requires_manual_review','marketplace_partial_refund_unsupported','marketplace_refund_reconciliation_failed','marketplace_dispute_resolution_forbidden','marketplace_dispute_resolution_auth_required','marketplace_refund_payment_not_paid','marketplace_refund_order_state_invalid','marketplace_refund_already_completed','marketplace_dispute_resolution_invalid_input'];
const amount=(value:unknown)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new MarketplaceSettlementError('marketplace_settlement_unknown');return n;};
function parse(value:unknown):MarketplaceSettlementReceipt{if(!value||typeof value!=='object')throw new MarketplaceSettlementError('marketplace_settlement_unknown');const x=value as Record<string,unknown>,s=x.settlement as Record<string,unknown>,o=x.order as Record<string,unknown>,sh=x.shipment as Record<string,unknown>,a=x.allocation as Record<string,unknown>;if(!s||!o||!sh||!a||s.status!=='completed'||s.currency!=='BDAG'||o.status!=='delivered'||sh.status!=='delivered'||a.status!=='released')throw new MarketplaceSettlementError('marketplace_settlement_unknown');return{settlement:{id:String(s.id),status:'completed',orderId:String(s.order_id),currency:'BDAG',grossAmount:amount(s.gross_amount),confirmedAt:String(s.confirmed_at),releasedAt:String(s.released_at)},order:{id:String(o.id),status:'delivered',deliveredAt:String(o.delivered_at)},shipment:{status:'delivered',deliveredAt:String(sh.delivered_at)},allocation:{status:'released',releasedAt:String(a.released_at)}};}
export async function confirmMarketplaceOrderDelivery(orderId:string,idempotencyKey:string):Promise<MarketplaceSettlementReceipt>{
 if(!UUID.test(orderId)||!UUID.test(idempotencyKey))throw new MarketplaceSettlementError('marketplace_delivery_invalid_input');
 try{const{data,error}=await getSupabaseClient().functions.invoke('bdag-ledger',{body:{action:'marketplace_order_confirm_delivery',order_id:orderId,idempotency_key:idempotencyKey}});if(error){const response=(error as{context?:unknown}).context;if(response instanceof Response){const payload=await response.clone().json().catch(()=>null);const code=known.includes(payload?.error)?payload.error as MarketplaceSettlementErrorCode:'marketplace_settlement_unknown';throw new MarketplaceSettlementError(code);}throw error;}if(!data?.success){const code=known.includes(data?.error)?data.error as MarketplaceSettlementErrorCode:'marketplace_settlement_unknown';throw new MarketplaceSettlementError(code);}return parse(data.data);}catch(error){if(error instanceof MarketplaceSettlementError)throw error;const message=error instanceof Error?error.message:'';const transport=/network|fetch|timeout|timed out|connection|socket|offline/i.test(message);if(__DEV__)console.error('[MarketplaceSettlement] gateway failed',{action:'marketplace_order_confirm_delivery',code:transport?'transport':'unknown',message:message.slice(0,200)});throw new MarketplaceSettlementError(transport?'marketplace_settlement_transport':'marketplace_settlement_unknown');}
}

export async function reportMarketplaceOrderProblem(orderId:string,reasonCode:'not_received'|'damaged'|'incorrect_item'|'missing_items'|'other',buyerNote:string,idempotencyKey:string):Promise<{status:string;reasonCode:string;settlementBlocked:true;createdAt:string}>{
 if(!UUID.test(orderId)||!UUID.test(idempotencyKey))throw new MarketplaceSettlementError('marketplace_dispute_invalid_input');
 const{data,error}=await getSupabaseClient().rpc('report_marketplace_order_problem',{p_order_id:orderId,p_reason_code:reasonCode,p_buyer_note:buyerNote.trim()||null,p_idempotency_key:idempotencyKey});
 if(error){const code=(error.message??'').match(/marketplace_[a-z_]+/)?.[0] as MarketplaceSettlementErrorCode|undefined;throw new MarketplaceSettlementError(code&&disputeCodes.includes(code)?code:'marketplace_settlement_unknown');}
 if(!data||typeof data!=='object'||data.settlement_blocked!==true)throw new MarketplaceSettlementError('marketplace_settlement_unknown');
 return{status:String(data.status),reasonCode:String(data.reason_code),settlementBlocked:true,createdAt:String(data.created_at)};
}

function resolutionCode(error:unknown):MarketplaceDisputeResolutionErrorCode{
 const source=error&&typeof error==='object'?error as Record<string,unknown>:{};
 const context=source.context&&typeof source.context==='object'?source.context as Record<string,unknown>:{};
 const body=context.body&&typeof context.body==='object'?context.body as Record<string,unknown>:{};
 const text=[source.message,source.details,source.hint,context.message,body.error].filter(value=>typeof value==='string').join(' ');
 return resolutionCodes.find(code=>text.includes(code))??(/network|fetch|timeout|connection|socket|offline/i.test(text)?'marketplace_dispute_resolution_transport':'marketplace_dispute_resolution_unknown');
}
const resolutionAmount=(value:unknown)=>{const parsed=Number(value);if(!Number.isFinite(parsed)||parsed<0)throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');return parsed;};
function parseSupportDispute(value:unknown):SupportMarketplaceDisputeDetail{
 if(!value||typeof value!=='object')throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');
 const root=value as Record<string,unknown>,d=root.dispute as Record<string,unknown>,o=root.order as Record<string,unknown>,p=root.payment as Record<string,unknown>,a=root.allocation as Record<string,unknown>;
 if(!d||!o||!p||!a)throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');
 return{dispute:{id:String(d.id),status:String(d.status),reasonCode:String(d.reason_code),createdAt:String(d.created_at)},order:{id:String(o.id),status:String(o.status)},payment:{status:String(p.status),grossAmount:resolutionAmount(p.gross_amount)},allocation:{status:String(a.status),grossAmount:resolutionAmount(a.gross_amount),sellerNetAmount:resolutionAmount(a.seller_net_amount),creatorCommissionAmount:resolutionAmount(a.creator_commission_amount),platformFeeAmount:resolutionAmount(a.platform_fee_amount)}};
}
function parseResolution(value:unknown):MarketplaceDisputeResolutionResult{
 if(!value||typeof value!=='object')throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');
 const root=value as Record<string,unknown>,x=root.dispute as Record<string,unknown>;
 if(root.kind==='intermediate_review'){
  const action=root.reviewAction as Record<string,unknown>;
  if(!action||!x||!UUID.test(`${action.id??''}`)||!UUID.test(`${action.dispute_id??''}`)||!UUID.test(`${action.order_id??''}`)||!['manual_review_requested','escalated'].includes(`${action.action??''}`)||!Number.isFinite(Date.parse(`${action.created_at??''}`))||x.status!=='under_review'||x.resolved_at!=null||root.finalDecision!==null||root.moneyMoved!==false||root.requiresHumanFollowUp!==true)throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');
  return{kind:'intermediate_review',finalDecision:null,reviewAction:{id:`${action.id}`,disputeId:`${action.dispute_id}`,orderId:`${action.order_id}`,action:`${action.action}` as MarketplaceDisputeReviewAction,reasonCode:`${action.reason_code}`,metadata:action.metadata&&typeof action.metadata==='object'?action.metadata as Record<string,unknown>:{},createdAt:`${action.created_at}`},dispute:{status:'under_review',resolvedAt:null},moneyMoved:false,requiresHumanFollowUp:true};
 }
 const d=root.finalDecision as Record<string,unknown>,o=root.order as Record<string,unknown>,p=root.payment as Record<string,unknown>,a=root.allocation as Record<string,unknown>;
 if(root.kind!=='final_resolution'||!d||!x||!o||!p||!a||!UUID.test(`${d.id??''}`)||!UUID.test(`${d.dispute_id??''}`)||!UUID.test(`${d.order_id??''}`)||!['refund_buyer','release_seller','reject_claim'].includes(`${d.outcome??''}`)||!Number.isFinite(Date.parse(`${d.decided_at??''}`))||x.resolved_at==null||!Number.isFinite(Date.parse(`${x.resolved_at}`)))throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_unknown');
 return{kind:'final_resolution',finalDecision:{id:`${d.id}`,disputeId:`${d.dispute_id}`,orderId:`${d.order_id}`,outcome:`${d.outcome}` as MarketplaceDisputeFinalOutcome,reasonCode:`${d.reason_code}`,financialResult:d.financial_result&&typeof d.financial_result==='object'?d.financial_result as Record<string,unknown>:{},decidedAt:`${d.decided_at}`},dispute:{status:`${x.status}`,resolvedAt:`${x.resolved_at}`},order:{status:`${o.status}`},payment:{status:`${p.status}`,grossAmount:resolutionAmount(p.gross_amount)},allocation:{status:`${a.status}`,grossAmount:resolutionAmount(a.gross_amount),sellerNetAmount:resolutionAmount(a.seller_net_amount),creatorCommissionAmount:resolutionAmount(a.creator_commission_amount),platformFeeAmount:resolutionAmount(a.platform_fee_amount)}};
}
async function supportInvoke(action:'marketplace_dispute_fetch'|'marketplace_dispute_resolve',body:Record<string,unknown>){
 const{data,error}=await getSupabaseClient().functions.invoke('bdag-ledger',{body:{action,...body}});
 if(error){const code=resolutionCode(error);throw new MarketplaceDisputeResolutionError(code,typeof(error as{code?:unknown}).code==='string'?String((error as{code:string}).code):null);}
 if(!data?.success)throw new MarketplaceDisputeResolutionError(resolutionCode(data));
 return data.data;
}
export async function fetchSupportMarketplaceDispute(disputeId:string,idempotencyKey:string):Promise<SupportMarketplaceDisputeDetail>{
 if(!UUID.test(disputeId)||!UUID.test(idempotencyKey))throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_invalid_input');
 return parseSupportDispute(await supportInvoke('marketplace_dispute_fetch',{dispute_id:disputeId,idempotency_key:idempotencyKey}));
}
export async function resolveMarketplaceDispute(disputeId:string,outcome:MarketplaceDisputeResolutionOutcome,reasonCode:string,note:string|null,idempotencyKey:string):Promise<MarketplaceDisputeResolutionResult>{
 if(!UUID.test(disputeId)||!UUID.test(idempotencyKey)||!['refund_buyer','release_seller','reject_claim','manual_review'].includes(outcome)||reasonCode.trim().length<2)throw new MarketplaceDisputeResolutionError('marketplace_dispute_resolution_invalid_input');
 return parseResolution(await supportInvoke('marketplace_dispute_resolve',{dispute_id:disputeId,outcome,reason_code:reasonCode.trim(),note:note?.trim()||null,idempotency_key:idempotencyKey}));
}
