import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {MaterialIcons} from '@expo/vector-icons';
import {randomUUID} from 'expo-crypto';
import {StatusBar} from 'expo-status-bar';
import {useFocusEffect,useLocalSearchParams,useRouter} from 'expo-router';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Colors,FontSize,FontWeight,Radius,Spacing} from '@/constants/theme';
import {cancelCheckoutReservation,expireMarketplaceCheckoutReservations,fetchMyCheckout,type CreateCheckoutReservationResult} from '@/services/marketplaceOrderService';
import {fetchAuthoritativeBdagBalance,MarketplacePaymentError,payMarketplaceCheckout} from '@/services/marketplacePaymentService';

export default function ReservationDetailScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();
 const [data,setData]=useState<CreateCheckoutReservationResult|null>(null);const [loading,setLoading]=useState(true);const [remaining,setRemaining]=useState(0);const [balance,setBalance]=useState<number|null>(null);const [paying,setPaying]=useState(false);
 const expiryLock=useRef(false);const paymentLock=useRef(false);const paymentKey=useRef(randomUUID());
 const load=useCallback(async()=>{if(!id)return;setLoading(true);try{const [checkout,currentBalance]=await Promise.all([fetchMyCheckout(id),fetchAuthoritativeBdagBalance()]);setData(checkout);setBalance(currentBalance);}catch{Alert.alert('Reserva no disponible','No pudimos cargar esta reserva.');}finally{setLoading(false);}},[id]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 useEffect(()=>{const tick=()=>{const seconds=Math.max(0,Math.ceil((new Date(data?.checkout.expiresAt??0).getTime()-Date.now())/1000));setRemaining(seconds);if(seconds===0&&data?.checkout.status==='pending_payment'&&!expiryLock.current){expiryLock.current=true;void expireMarketplaceCheckoutReservations().then(load).finally(()=>{expiryLock.current=false;});}};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[data?.checkout.expiresAt,data?.checkout.status,load]);
 const cancel=()=>Alert.alert('Cancelar reserva','Los productos reservados volverán al inventario disponible.',[{text:'Mantener reserva',style:'cancel'},{text:'Cancelar reserva',style:'destructive',onPress:async()=>{if(!id)return;const result=await cancelCheckoutReservation(id);setData(result);Alert.alert('Reserva cancelada','El inventario reservado volvió a estar disponible.');}}]);
 const submitPayment=async()=>{if(!id||paymentLock.current)return;paymentLock.current=true;setPaying(true);try{const receipt=await payMarketplaceCheckout(id,paymentKey.current);await load();setBalance(receipt.buyer.newBdagBalance);Alert.alert('Pago confirmado','Pedido confirmado');}catch(error){const code=error instanceof MarketplacePaymentError?error.code:'marketplace_payment_unknown';if(code==='marketplace_checkout_expired')Alert.alert('La reserva expiró','Los productos regresaron al inventario. Agrégalos nuevamente al carrito para continuar.');else if(code==='marketplace_checkout_cancelled'||code==='marketplace_checkout_not_payable')Alert.alert('Reserva cancelada','Esta reserva ya no puede pagarse.');else if(code==='marketplace_insufficient_bdag_balance')Alert.alert('Saldo BDAG insuficiente',`Necesitas ${data?.checkout.total.toFixed(2)} BDAG y tienes ${(balance??0).toFixed(2)} BDAG disponibles.`,[{text:'Cerrar',style:'cancel'},{text:'Agregar saldo',onPress:()=>router.push('/(tabs)/wallet' as never)}]);else if(code==='marketplace_payment_transport'){Alert.alert('No pudimos confirmar el estado del pago','Verificaremos el pedido antes de intentar nuevamente.');await load();}else Alert.alert('No se pudo confirmar el pago','El pedido necesita ser revisado antes de cobrarlo. No se descontó BDAG.');}finally{paymentLock.current=false;setPaying(false);}};
 const confirmPayment=()=>Alert.alert('Confirmar pago',`Se descontarán ${data?.checkout.total.toFixed(2)} BDAG de tu saldo para confirmar este pedido.\n\nEl pago quedará protegido mientras se procesa la entrega.`,[{text:'Volver',style:'cancel'},{text:`Pagar ${data?.checkout.total.toFixed(2)} BDAG`,onPress:()=>void submitPayment()}]);
 if(loading||!data)return <View style={[styles.root,styles.center,{paddingTop:insets.top}]}><ActivityIndicator color={Colors.primary}/><Text style={styles.muted}>Cargando reserva…</Text></View>;
 const pending=data.checkout.status==='pending_payment';const paid=data.checkout.status==='paid';const expired=data.checkout.status==='expired';const cancelled=data.checkout.status==='cancelled';
 const countdown=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
 return <View style={[styles.root,{paddingTop:insets.top}]}><StatusBar style="light"/><View style={styles.header}><Pressable style={styles.icon} onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel="Volver"><MaterialIcons name="arrow-back-ios" size={20} color={Colors.textPrimary}/></Pressable><View style={{flex:1}}><Text style={styles.headerTitle}>{paid?'Pedido confirmado':'Reserva de compra'}</Text><Text style={styles.reference}>{data.checkout.reference}</Text></View><View style={[styles.badge,(expired||cancelled)&&styles.badgeTerminal]}><Text style={styles.badgeText}>{paid?'Pagado':pending?'Inventario reservado':expired?'Expirada':'Cancelada'}</Text></View></View>
 <ScrollView contentContainerStyle={styles.content}>{paid?<View style={styles.hero}><MaterialIcons name="verified" size={34} color={Colors.success}/><Text style={styles.heroTitle}>Pago confirmado</Text><Text style={styles.total}>{data.payment?.grossAmount.toFixed(2)} BDAG</Text><Text style={styles.muted}>{data.payment?.paidAt?new Date(data.payment.paidAt).toLocaleString():''}</Text></View>:pending?<View style={styles.hero}><MaterialIcons name="timer" size={30} color={Colors.accent}/><Text style={styles.heroTitle}>Inventario reservado</Text><Text style={styles.countdown}>{countdown}</Text><Text style={styles.muted}>Expira el {new Date(data.checkout.expiresAt).toLocaleString()}</Text></View>:<View style={styles.hero}><MaterialIcons name={expired?'schedule':'cancel'} size={30} color={Colors.secondary}/><Text style={styles.heroTitle}>{expired?'Reserva expirada':'Reserva cancelada'}</Text><Text style={styles.muted}>Los productos regresaron al inventario disponible.</Text></View>}
 <View style={styles.card}><Text style={styles.sectionTitle}>Entrega</Text><Text style={styles.text}>{data.shippingAddress.recipientName}</Text><Text style={styles.muted}>{data.shippingAddress.city}, {data.shippingAddress.region} · {data.shippingAddress.country}</Text></View>
 {data.orders.map(order=><View key={order.id} style={styles.card}><Text style={styles.sectionTitle}>Pedido {order.orderNumber}</Text>{order.items.map(item=><View key={item.id} style={styles.line}><View style={{flex:1}}><Text style={styles.text}>{item.productTitle}</Text><Text style={styles.options}>{item.options.map(option=>option.value).join(' · ')}</Text><Text style={styles.muted}>Cantidad {item.quantity} · {item.unitPrice.toFixed(2)} BDAG</Text></View><Text style={styles.price}>{item.lineTotal.toFixed(2)} BDAG</Text></View>)}<View style={styles.totalRow}><Text style={styles.text}>Subtotal</Text><Text style={styles.price}>{order.subtotal.toFixed(2)} BDAG</Text></View></View>)}
 <View style={styles.totalCard}><Text style={styles.sectionTitle}>{paid?'Total pagado':'Total reservado'}</Text><Text style={styles.total}>{data.checkout.total.toFixed(2)} BDAG</Text></View>
 {paid?data.orders.map(order=><Pressable key={order.id} style={styles.secondary} onPress={()=>router.push(`/orders/${order.id}` as never)} accessibilityRole="button" accessibilityLabel={`Ver pedido ${order.orderNumber}`}><Text style={styles.secondaryText}>Ver pedido · {order.orderNumber}</Text></Pressable>):null}
 {pending?<><Text style={styles.balance}>Saldo disponible: {balance?.toFixed(2)??'—'} BDAG</Text><Pressable style={[styles.primary,paying&&styles.disabled]} disabled={paying||remaining<=0} onPress={confirmPayment} accessibilityRole="button" accessibilityLabel="Pagar con BDAG" accessibilityState={{disabled:paying||remaining<=0}}>{paying?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Pagar con BDAG</Text>}</Pressable><Text style={styles.helper}>Tu pago quedará protegido hasta que el pedido avance en su proceso de entrega.</Text><Pressable style={styles.cancel} onPress={cancel} accessibilityRole="button" accessibilityLabel="Cancelar reserva"><Text style={styles.cancelText}>Cancelar reserva</Text></Pressable></>:<View style={styles.actions}><Pressable style={styles.secondary} onPress={()=>router.replace('/(tabs)/shop' as never)}><Text style={styles.secondaryText}>Volver al Marketplace</Text></Pressable>{!paid?<Pressable style={styles.secondary} onPress={()=>router.push('/cart' as never)}><Text style={styles.secondaryText}>Ver carrito</Text></Pressable>:null}</View>}
 </ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{alignItems:'center',justifyContent:'center',gap:Spacing.md},header:{minHeight:64,flexDirection:'row',alignItems:'center',gap:Spacing.sm,paddingHorizontal:Spacing.sm,borderBottomWidth:1,borderBottomColor:Colors.border},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerTitle:{color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold},reference:{color:Colors.textSubtle,fontSize:FontSize.xs},badge:{backgroundColor:Colors.accentDim,borderRadius:Radius.full,paddingHorizontal:10,paddingVertical:6},badgeTerminal:{backgroundColor:Colors.secondaryDim},badgeText:{color:Colors.textPrimary,fontSize:FontSize.xs,fontWeight:FontWeight.bold},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:Spacing.xl},hero:{alignItems:'center',gap:Spacing.sm,padding:Spacing.lg},heroTitle:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.bold},countdown:{color:Colors.accent,fontSize:36,fontWeight:FontWeight.extrabold},muted:{color:Colors.textSecondary,fontSize:FontSize.sm},card:{backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg,padding:Spacing.md,gap:Spacing.sm,borderWidth:1,borderColor:Colors.border},sectionTitle:{color:Colors.textPrimary,fontWeight:FontWeight.bold,fontSize:FontSize.md},text:{color:Colors.textPrimary,fontSize:FontSize.sm},options:{color:Colors.primaryLight,fontSize:FontSize.sm},line:{flexDirection:'row',gap:Spacing.sm,paddingVertical:Spacing.sm,borderBottomWidth:1,borderBottomColor:Colors.borderSubtle},price:{color:Colors.textPrimary,fontWeight:FontWeight.bold},totalRow:{flexDirection:'row',justifyContent:'space-between'},totalCard:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:Colors.primaryDim,borderRadius:Radius.lg,padding:Spacing.md},total:{color:Colors.primaryLight,fontSize:FontSize.xl,fontWeight:FontWeight.extrabold},balance:{color:Colors.textPrimary,textAlign:'center',fontWeight:FontWeight.bold},primary:{minHeight:52,borderRadius:Radius.md,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:FontWeight.bold},disabled:{opacity:.45},helper:{color:Colors.textSubtle,textAlign:'center'},cancel:{minHeight:48,alignItems:'center',justifyContent:'center'},cancelText:{color:Colors.secondary,fontWeight:FontWeight.bold},actions:{flexDirection:'row',gap:Spacing.sm},secondary:{flex:1,minHeight:48,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.primary,alignItems:'center',justifyContent:'center'},secondaryText:{color:Colors.primaryLight,fontWeight:FontWeight.bold,textAlign:'center'}});
