import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {MaterialIcons} from '@expo/vector-icons';import {StatusBar} from 'expo-status-bar';
import {useFocusEffect,useLocalSearchParams,useRouter} from 'expo-router';import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Colors,FontSize,FontWeight,Radius,Spacing} from '@/constants/theme';
import {cancelCheckoutReservation,expireMarketplaceCheckoutReservations,fetchMyCheckout,type CreateCheckoutReservationResult} from '@/services/marketplaceOrderService';

export default function ReservationDetailScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();
 const [data,setData]=useState<CreateCheckoutReservationResult|null>(null);const [loading,setLoading]=useState(true);const [remaining,setRemaining]=useState(0);const expiryLock=useRef(false);
 const load=useCallback(async()=>{if(!id)return;setLoading(true);try{setData(await fetchMyCheckout(id));}catch{Alert.alert('Reserva no disponible','No pudimos cargar esta reserva.');}finally{setLoading(false);}},[id]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 useEffect(()=>{const tick=()=>{const seconds=Math.max(0,Math.ceil((new Date(data?.checkout.expiresAt??0).getTime()-Date.now())/1000));setRemaining(seconds);if(seconds===0&&data?.checkout.status==='pending_payment'&&!expiryLock.current){expiryLock.current=true;void expireMarketplaceCheckoutReservations().then(load).finally(()=>{expiryLock.current=false;});}};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[data?.checkout.expiresAt,data?.checkout.status,load]);
 const cancel=()=>Alert.alert('Cancelar reserva','Los productos reservados volverán al inventario disponible.',[{text:'Mantener reserva',style:'cancel'},{text:'Cancelar reserva',style:'destructive',onPress:async()=>{if(!id)return;const result=await cancelCheckoutReservation(id);setData(result);Alert.alert('Reserva cancelada','El inventario reservado volvió a estar disponible.');}}]);
 if(loading||!data)return <View style={[styles.root,styles.center,{paddingTop:insets.top}]}><ActivityIndicator color={Colors.primary}/><Text style={styles.muted}>Cargando reserva…</Text></View>;
 const pending=data.checkout.status==='pending_payment';const expired=data.checkout.status==='expired';const cancelled=data.checkout.status==='cancelled';
 const countdown=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
 return <View style={[styles.root,{paddingTop:insets.top}]}><StatusBar style="light"/><View style={styles.header}><Pressable style={styles.icon} onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel="Volver"><MaterialIcons name="arrow-back-ios" size={20} color={Colors.textPrimary}/></Pressable><View style={{flex:1}}><Text style={styles.headerTitle}>Reserva de compra</Text><Text style={styles.reference}>{data.checkout.reference}</Text></View><View style={[styles.badge,(expired||cancelled)&&styles.badgeTerminal]}><Text style={styles.badgeText}>{pending?'Inventario reservado':expired?'Expirada':'Cancelada'}</Text></View></View>
 <ScrollView contentContainerStyle={styles.content}>{pending?<View style={styles.hero}><MaterialIcons name="timer" size={30} color={Colors.accent}/><Text style={styles.heroTitle}>Inventario reservado</Text><Text style={styles.countdown}>{countdown}</Text><Text style={styles.muted}>Expira el {new Date(data.checkout.expiresAt).toLocaleString()}</Text></View>:<View style={styles.hero}><MaterialIcons name={expired?'schedule':'cancel'} size={30} color={Colors.secondary}/><Text style={styles.heroTitle}>{expired?'Reserva expirada':'Reserva cancelada'}</Text><Text style={styles.muted}>Los productos regresaron al inventario disponible.</Text></View>}
 <View style={styles.card}><Text style={styles.sectionTitle}>Entrega</Text><Text style={styles.text}>{data.shippingAddress.recipientName}</Text><Text style={styles.muted}>{data.shippingAddress.city}, {data.shippingAddress.region} · {data.shippingAddress.country}</Text></View>
 {data.orders.map(order=><View key={order.id} style={styles.card}><Text style={styles.sectionTitle}>Pedido {order.orderNumber}</Text>{order.items.map(item=><View key={item.id} style={styles.line}><View style={{flex:1}}><Text style={styles.text}>{item.productTitle}</Text><Text style={styles.options}>{item.options.map(option=>option.value).join(' · ')}</Text><Text style={styles.muted}>Cantidad {item.quantity} · {item.unitPrice.toFixed(2)} BDAG</Text></View><Text style={styles.price}>{item.lineTotal.toFixed(2)} BDAG</Text></View>)}<View style={styles.totalRow}><Text style={styles.text}>Subtotal</Text><Text style={styles.price}>{order.subtotal.toFixed(2)} BDAG</Text></View></View>)}
 <View style={styles.totalCard}><Text style={styles.sectionTitle}>Total reservado</Text><Text style={styles.total}>{data.checkout.total.toFixed(2)} BDAG</Text></View>
 {pending?<><Pressable style={[styles.primary,styles.disabled]} disabled accessibilityRole="button" accessibilityLabel="Pagar con BDAG, disponible en la siguiente fase" accessibilityState={{disabled:true}}><Text style={styles.primaryText}>Pagar con BDAG</Text></Pressable><Text style={styles.helper}>Disponible en la siguiente fase.</Text><Pressable style={styles.cancel} onPress={cancel} accessibilityRole="button" accessibilityLabel="Cancelar reserva"><Text style={styles.cancelText}>Cancelar reserva</Text></Pressable></>:<View style={styles.actions}><Pressable style={styles.secondary} onPress={()=>router.replace('/(tabs)/shop' as never)}><Text style={styles.secondaryText}>Volver al Marketplace</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.push('/cart' as never)}><Text style={styles.secondaryText}>Ver carrito</Text></Pressable></View>}
 </ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{alignItems:'center',justifyContent:'center',gap:Spacing.md},header:{minHeight:64,flexDirection:'row',alignItems:'center',gap:Spacing.sm,paddingHorizontal:Spacing.sm,borderBottomWidth:1,borderBottomColor:Colors.border},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerTitle:{color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold},reference:{color:Colors.textSubtle,fontSize:FontSize.xs},badge:{backgroundColor:Colors.accentDim,borderRadius:Radius.full,paddingHorizontal:10,paddingVertical:6},badgeTerminal:{backgroundColor:Colors.secondaryDim},badgeText:{color:Colors.textPrimary,fontSize:FontSize.xs,fontWeight:FontWeight.bold},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:Spacing.xl},hero:{alignItems:'center',gap:Spacing.sm,padding:Spacing.lg},heroTitle:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.bold},countdown:{color:Colors.accent,fontSize:36,fontWeight:FontWeight.extrabold},muted:{color:Colors.textSecondary,fontSize:FontSize.sm},card:{backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg,padding:Spacing.md,gap:Spacing.sm,borderWidth:1,borderColor:Colors.border},sectionTitle:{color:Colors.textPrimary,fontWeight:FontWeight.bold,fontSize:FontSize.md},text:{color:Colors.textPrimary,fontSize:FontSize.sm},options:{color:Colors.primaryLight,fontSize:FontSize.sm},line:{flexDirection:'row',gap:Spacing.sm,paddingVertical:Spacing.sm,borderBottomWidth:1,borderBottomColor:Colors.borderSubtle},price:{color:Colors.textPrimary,fontWeight:FontWeight.bold},totalRow:{flexDirection:'row',justifyContent:'space-between'},totalCard:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:Colors.primaryDim,borderRadius:Radius.lg,padding:Spacing.md},total:{color:Colors.primaryLight,fontSize:FontSize.xl,fontWeight:FontWeight.extrabold},primary:{minHeight:52,borderRadius:Radius.md,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:FontWeight.bold},disabled:{opacity:.45},helper:{color:Colors.textSubtle,textAlign:'center'},cancel:{minHeight:48,alignItems:'center',justifyContent:'center'},cancelText:{color:Colors.secondary,fontWeight:FontWeight.bold},actions:{flexDirection:'row',gap:Spacing.sm},secondary:{flex:1,minHeight:48,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.primary,alignItems:'center',justifyContent:'center'},secondaryText:{color:Colors.primaryLight,fontWeight:FontWeight.bold,textAlign:'center'}});
