import React, { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Avatar } from '@/components/ui/Avatar';
import { Colors, FontSize, FontWeight, Spacing } from '@/constants/theme';
import { useMessages } from '@/hooks/useMessages';
import { addChatGroupMembers, fetchChatGroupMembers, leaveChatGroup, removeChatGroupMember, setChatGroupAdmin, transferChatGroupOwnership, updateChatGroupName } from '@/services/chatService';
import { getSupabaseClient } from '@/template';
import type { ChatGroupMemberRow } from '@/services/chatContract';

export default function GroupInfoScreen(){
 const {conversationId=''}=useLocalSearchParams<{conversationId:string}>();const router=useRouter();const insets=useSafeAreaInsets();const {conversations,refreshConversations}=useMessages();const conversation=conversations.find(c=>c.id===conversationId);const [members,setMembers]=useState<ChatGroupMemberRow[]>([]);const [name,setName]=useState(conversation?.groupName||'');const [search,setSearch]=useState('');const [candidates,setCandidates]=useState<{id:string;username:string}[]>([]);
 const load=useCallback(()=>fetchChatGroupMembers(conversationId).then(setMembers),[conversationId]);useEffect(()=>{void load();},[load]);const owner=conversation?.currentUserRole==='owner';const admin=owner||conversation?.currentUserRole==='admin';
 const action=async(fn:()=>Promise<unknown>)=>{try{await fn();await load();await refreshConversations();}catch(error){Alert.alert('No se pudo completar',error instanceof Error?error.message:'Error');}};
 useEffect(()=>{if(!admin||!search.trim()){setCandidates([]);return;}const timer=setTimeout(()=>{void getSupabaseClient().from('user_profiles').select('id,username').ilike('username',`%${search.trim()}%`).limit(10).then(({data})=>setCandidates((data||[]) as {id:string;username:string}[]));},300);return()=>clearTimeout(timer);},[admin,search]);
 return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable onPress={()=>router.back()}><MaterialIcons name="arrow-back" size={24} color={Colors.textPrimary}/></Pressable><Text style={styles.title}>Información del grupo</Text></View><View style={styles.rename}><TextInput style={styles.input} value={name} onChangeText={setName} maxLength={120} editable={admin}/>{admin?<Pressable onPress={()=>void action(()=>updateChatGroupName(conversationId,name.trim()))}><Text style={styles.action}>Guardar</Text></Pressable>:null}</View>{admin?<><TextInput style={[styles.input,{marginHorizontal:Spacing.md}]} value={search} onChangeText={setSearch} placeholder="Agregar miembro" placeholderTextColor={Colors.textSubtle}/>{candidates.map(candidate=><Pressable key={candidate.id} style={styles.row} onPress={()=>void action(()=>addChatGroupMembers(conversationId,[candidate.id]).then(()=>{setSearch('');setCandidates([]);} ))}><Text style={styles.member}>@{candidate.username}</Text><Text style={styles.action}>Agregar</Text></Pressable>)}</>:null}
 <FlatList data={members} keyExtractor={m=>m.user_id} renderItem={({item})=><View style={styles.row}><Avatar uri={item.avatar_url||''} username={item.username||'Usuario'} size={40}/><View style={{flex:1}}><Text style={styles.member}>@{item.username||'usuario'}</Text><Text style={styles.role}>{item.role}{!item.is_active?' · salió':''}</Text></View>{item.is_active&&owner&&item.role!=='owner'?<><Pressable onPress={()=>void action(()=>setChatGroupAdmin(conversationId,item.user_id,item.role!=='admin'))}><Text style={styles.small}>{item.role==='admin'?'Quitar admin':'Hacer admin'}</Text></Pressable><Pressable onPress={()=>void action(()=>transferChatGroupOwnership(conversationId,item.user_id))}><Text style={styles.small}>Transferir</Text></Pressable></>:null}{item.is_active&&admin&&item.role==='member'?<Pressable onPress={()=>void action(()=>removeChatGroupMember(conversationId,item.user_id))}><MaterialIcons name="person-remove" size={20} color={Colors.error}/></Pressable>:null}</View>}/>
 <Pressable style={styles.leave} onPress={()=>void leaveChatGroup(conversationId).then(async()=>{await refreshConversations();router.replace('/(tabs)/messages' as any);}).catch(error=>Alert.alert('No se pudo salir',error instanceof Error?error.message:'Error'))}><Text style={styles.leaveText}>Salir del grupo</Text></Pressable></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:58,flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:Spacing.md},title:{color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold},rename:{flexDirection:'row',alignItems:'center',gap:8,padding:Spacing.md},input:{flex:1,color:Colors.textPrimary,borderBottomWidth:1,borderColor:Colors.border,padding:8},action:{color:Colors.primary,fontWeight:FontWeight.bold},row:{flexDirection:'row',alignItems:'center',gap:10,padding:Spacing.md},member:{color:Colors.textPrimary},role:{color:Colors.textSubtle,fontSize:11},small:{color:Colors.primary,fontSize:10},leave:{padding:Spacing.lg,alignItems:'center'},leaveText:{color:Colors.error,fontWeight:FontWeight.bold}});
