import React,{useEffect,useRef,useState} from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useAlert} from '@/template';
import {fetchCategories,fetchProduct,updateProduct,type MarketplaceCategoryRecord} from '@/services/marketplaceService';
import {Colors,FontSize,FontWeight,Radius,Spacing} from '@/constants/theme';
export default function EditProduct(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();const {showAlert}=useAlert();const lock=useRef(false);
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [price,setPrice]=useState('');const [stock,setStock]=useState('0');const [categoryId,setCategoryId]=useState('');const [tags,setTags]=useState<string[]>([]);const [categories,setCategories]=useState<MarketplaceCategoryRecord[]>([]);
 useEffect(()=>{let active=true;void Promise.all([fetchProduct(id),fetchCategories()]).then(([product,values])=>{if(!active)return;if(!product){showAlert('Producto no disponible','No puedes editar este producto.');router.back();return;}setTitle(product.title);setDescription(product.description);setPrice(String(product.price));setStock(String(product.stock));setCategoryId(product.category_id);setTags(product.tags);setCategories(values);});return()=>{active=false;};},[id,router,showAlert]);
 const save=async()=>{if(lock.current)return;if(!/^\d{1,12}(?:\.\d{1,8})?$/.test(price)||Number(price)<=0){showAlert('Precio inválido','Usa hasta 8 decimales.');return;}lock.current=true;try{await updateProduct(id,{categoryId,title,description,price,stock:Math.max(0,Number.parseInt(stock,10)||0),tags});showAlert('Producto actualizado','Los cambios se guardaron.');router.replace('/seller/products' as never);}catch{showAlert('No se pudo guardar','Verifica los datos e inténtalo nuevamente.');}finally{lock.current=false;}};
 return <View style={[s.page,{paddingTop:insets.top+Spacing.lg}]}><Text style={s.title}>Editar producto</Text><TextInput style={s.input} value={title} onChangeText={setTitle} maxLength={120}/><TextInput style={[s.input,s.note]} value={description} onChangeText={setDescription} multiline maxLength={3000}/><TextInput style={s.input} value={price} onChangeText={setPrice} keyboardType="decimal-pad"/><TextInput style={s.input} value={stock} onChangeText={setStock} keyboardType="number-pad"/><View style={s.categories}>{categories.map(item=><Pressable key={item.id} style={[s.chip,categoryId===item.id&&s.active]} onPress={()=>setCategoryId(item.id)}><Text style={s.chipText}>{item.name}</Text></Pressable>)}</View><Pressable style={s.button} onPress={save}><Text style={s.buttonText}>Guardar cambios</Text></Pressable></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.bg,padding:Spacing.lg,gap:Spacing.md},title:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.bold},input:{backgroundColor:Colors.surfaceElevated,borderColor:Colors.border,borderWidth:1,borderRadius:Radius.md,padding:Spacing.md,color:Colors.textPrimary},note:{height:120,textAlignVertical:'top'},categories:{flexDirection:'row',flexWrap:'wrap',gap:Spacing.sm},chip:{padding:Spacing.sm,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.border},active:{backgroundColor:Colors.primary},chipText:{color:Colors.textPrimary},button:{backgroundColor:Colors.primary,padding:Spacing.md,borderRadius:Radius.md,alignItems:'center'},buttonText:{color:'#000',fontWeight:FontWeight.bold}});
