import type { LegalDocument } from './core.ts';

// The only document text source; provenance is intentionally outside adapter imports.
export const privacy: LegalDocument = {
  id: 'privacy', locale: 'en', version: 'draft-c2-unapproved', title: 'Privacy Policy — unapproved draft',
  sections: [
    { id: 'account-profile', title: 'Accounts and profiles', blocks: [{ type: 'paragraph', text: 'Account creation and sign-in use an email address and password. Profiles can contain a username, display name, image, biography, website, location and visibility or communication preferences. Account and profile identifiers connect activity to the account.' }] },
    { id: 'content-interactions', title: 'Content and interactions', blocks: [{ type: 'paragraph', text: 'The service stores content such as video and image posts, captions and comments. Likes, saves, follows, views and reports generate records or counters used to present content and operate community features.' }] },
    { id: 'stories-media', title: 'Stories and media', blocks: [{ type: 'paragraph', text: 'Stories and uploaded media have associated assets and viewing records. A Story visibility window does not by itself establish when every associated record or stored asset is removed.' }] },
    { id: 'content-safety', title: 'Content-safety processing', blocks: [{ type: 'paragraph', text: 'The code includes configuration-gated audio transcription and visual analysis of eligible video media for content-safety review, including processing through Cloudflare Workers AI and storing analysis results. Whether this processing is enabled in the deployed service, and its retention and review practices, require confirmation.' }] },
    { id: 'messages-calls', title: 'Messages and calls', blocks: [{ type: 'paragraph', text: 'Direct and group conversations can include text, images, video and voice notes. Message delivery and read receipts, one-view consumption state and call-device records support those features. This draft makes no end-to-end encryption or universal deletion claim.' }] },
    { id: 'live', title: 'LIVE participation', blocks: [{ type: 'paragraph', text: 'LIVE sessions record hosts and participation. Related systems support viewers, co-host roles, Battles, chat, reactions and gifts; audio and video transport uses an external real-time media service. Recording and retention practices require separate confirmation.' }] },
    { id: 'marketplace', title: 'Marketplace and orders', blocks: [{ type: 'paragraph', text: 'Marketplace activity can involve seller and store profiles, product media, checkout and order records, shipping recipient and address information, returns, disputes and refunds. Order and payment records may remain separate from removable public content.' }] },
    { id: 'business-ads', title: 'Business and advertising', blocks: [{ type: 'paragraph', text: 'Business owners and invited members use products, orders, media, campaigns, analytics, finance and team permissions. Invitations use email addresses. Ads systems record campaign configuration, placement, delivery and reporting events. This draft does not assert cross-site behavioral targeting.' }] },
    { id: 'payments-payouts', title: 'Payments and payouts', blocks: [{ type: 'paragraph', text: 'BDAG balances and transfers, Marketplace payments and refunds, and payout requests generate transaction and reconciliation records. A Stripe checkout adapter exists for a Business top-up flow in Test Mode; public availability and final legal characterization are not established by this code.' }] },
    { id: 'device-notifications', title: 'Device and notifications', blocks: [{ type: 'paragraph', text: 'Push notification and call-device registration can store device tokens, platform and app or device metadata. Technical request logs and any retention periods require deployment-level verification before a final policy is approved.' }] },
    { id: 'service-providers', title: 'Service providers', blocks: [{ type: 'paragraph', text: 'Supabase supports account and data services; Agora supports real-time media; Expo provides push delivery; Cloudflare supports selected media storage and delivery and has a configuration-gated Workers AI content-safety path. Stripe is integrated for a configuration-gated Business checkout. Actual production configuration and provider-specific disclosures require review.' }] },
    { id: 'retention-deletion', title: 'Retention and account controls', blocks: [{ type: 'paragraph', text: 'Settings offers profile and password changes. Both account-deletion information entry points explain that they do not delete an account or submit a request. A verified request channel and complete deletion procedure remain to be established. Financial, order and audit records have separate references and lifecycles; a complete retention schedule remains to be approved.' }] },
    { id: 'legal-choices-contact', title: 'Legal choices and contact', blocks: [{ type: 'paragraph', text: 'The legal entity, location, official contacts, age handling, applicable user rights, international handling and effective date remain unresolved. No contact address or jurisdiction is asserted by this draft.' }] },
  ],
};

export const terms: LegalDocument = {
  id: 'terms', locale: 'en', version: 'draft-c2-unapproved', title: 'Terms of Service — unapproved draft',
  sections: [
    { id: 'accounts-eligibility', title: 'Accounts and eligibility', blocks: [{ type: 'paragraph', text: 'The service supports account registration, sign-in, profile controls and password changes. Eligibility and parental-consent rules require an owner and legal decision; this draft sets no age threshold.' }] },
    { id: 'content-conduct', title: 'Content and conduct', blocks: [{ type: 'paragraph', text: 'Users can submit content and interact with other accounts. Reporting, blocking and moderation mechanisms exist. The scope of a user-content license, prohibited-conduct language and enforcement procedures require legal review; no broader license or response-time promise is set here.' }] },
    { id: 'messages-live', title: 'Messaging and LIVE', blocks: [{ type: 'paragraph', text: 'The product supports conversations and LIVE participation, including host, viewer, co-host and Battle flows. Gifts have a separate financial authority. This draft does not promise recording, uninterrupted availability or creator revenue.' }] },
    { id: 'marketplace', title: 'Marketplace', blocks: [{ type: 'paragraph', text: 'The Marketplace supports seller listings, checkout, orders, shipping, returns and disputes. Payment, held-funds settlement and some refunds use server-side transaction records. Buyer and seller obligations, timing and final remedies require review; no universal refund or payout promise is made.' }] },
    { id: 'business-ads', title: 'Nelyon Business and Ads', blocks: [{ type: 'paragraph', text: 'Business has owner and delegated-member permissions for store, products, orders, media, analytics, finance and team. Ads Manager supports campaigns, placements and reporting. Access remains subject to the existing authorization mechanisms; contractual advertising terms require separate approval.' }] },
    { id: 'bdag-payments', title: 'BDAG and payments', blocks: [{ type: 'paragraph', text: 'BDAG activity uses wallet and ledger authorities for transfers, purchases, gifts and withdrawals. Marketplace allocations and payout quotes depend on server-side rules. The legal nature, redemption rights, fees, exchange representation and finality of transactions are unresolved; this draft makes no investment or cash-redemption determination.' }] },
    { id: 'refunds-payouts', title: 'Refunds and payouts', blocks: [{ type: 'paragraph', text: 'The code has conditional refund and payout workflows, including held-payment dispute handling and stablecoin conversion checks. Their availability, eligibility, timing, network risks and legally binding commitments require review. No fixed minimum, percentage or settlement deadline is stated here.' }] },
    { id: 'moderation-termination', title: 'Moderation and termination', blocks: [{ type: 'paragraph', text: 'Moderation includes reports, warnings and account-suspension operations. The settings screen does not itself complete account deletion. Notice periods, appeals, effects on records and termination rights require owner and legal approval.' }] },
    { id: 'third-parties', title: 'Third-party services', blocks: [{ type: 'paragraph', text: 'External account, media, push, payment and storage integrations support portions of the service. Their contractual allocation of responsibility and any applicable third-party terms require legal review.' }] },
    { id: 'legal-terms', title: 'Legal terms awaiting decision', blocks: [{ type: 'paragraph', text: 'Entity identity, governing law, dispute forum, arbitration, liability language, changes to these terms, legal contacts, translations and an effective date are not established in this unapproved draft.' }] },
  ],
};

export const legalDocuments: readonly LegalDocument[] = [privacy, terms];
