import type { LegalDocument } from './core.ts';

// The only document text source; provenance is intentionally outside adapter imports.
export const privacy: LegalDocument = {
  id: 'privacy', locale: 'en', version: 'draft-c4-unapproved', title: 'Privacy Policy — unapproved draft',
  sections: [
    { id: 'account-profile', title: 'Accounts and profiles', blocks: [{ type: 'paragraph', text: 'Account creation and sign-in use an email address and password. Profiles can contain a username, display name, image, biography, website, location and visibility or communication preferences. Account and profile identifiers connect activity to the account.' }] },
    { id: 'content-interactions', title: 'Content and interactions', blocks: [{ type: 'paragraph', text: 'The service stores content such as video and image posts, captions and comments. Likes, saves, follows, views and reports generate records or counters used to present content and operate community features.' }] },
    { id: 'stories-media', title: 'Stories and media', blocks: [{ type: 'paragraph', text: 'Stories and uploaded media have associated assets and viewing records. A Story visibility window does not by itself establish when every associated record or stored asset is removed.' }] },
    { id: 'content-safety', title: 'Content-safety processing', blocks: [{ type: 'paragraph', text: 'The code includes configuration-gated audio transcription and visual analysis of eligible video media for content-safety review, including processing through Cloudflare Workers AI and storing analysis results. Whether this processing is enabled in the deployed service, and its retention and review practices, require confirmation.' }] },
    { id: 'messages-calls', title: 'Messages and calls', blocks: [{ type: 'paragraph', text: 'Direct and group conversations can include text, images, video and voice notes. Message delivery and read receipts, one-view consumption state and call-device records support those features. This draft makes no end-to-end encryption or universal deletion claim.' }] },
    { id: 'live', title: 'LIVE participation', blocks: [{ type: 'paragraph', text: 'LIVE sessions record hosts and participation. Related systems support viewers, co-host roles, Battles, chat, reactions and gifts; audio and video transport uses an external real-time media service. Recording and retention practices require separate confirmation.' }] },
    { id: 'marketplace', title: 'Marketplace and orders', blocks: [{ type: 'paragraph', text: 'Marketplace activity can involve seller and store profiles, product media, checkout and order records, shipping recipient and address information, returns, disputes and refunds. Order and payment records may remain separate from removable public content.' }] },
    { id: 'business-ads', title: 'Business and advertising', blocks: [{ type: 'paragraph', text: 'Business owners and invited members use products, orders, media, campaigns, analytics, finance and team permissions. Invitations use email addresses. Ads systems record campaign configuration, placement, delivery and reporting events. This draft does not assert cross-site behavioral targeting.' }] },
    { id: 'payments-payouts', title: 'Payments and payouts', blocks: [{ type: 'paragraph', text: 'BDAG balances and transfers, Marketplace payments and refunds, and payout requests generate transaction and reconciliation records. A Stripe checkout adapter exists for a Business top-up flow in Test Mode; public availability and final legal characterization are not established by this code.' }] },
    { id: 'device-notifications', title: 'Device and notifications', blocks: [{ type: 'paragraph', text: 'Push notification and call-device registration can store device tokens, platform and app or device metadata. Technical request logs and any retention periods require deployment-level verification before a final policy is approved.' }] },
    { id: 'service-providers', title: 'Service providers', blocks: [{ type: 'paragraph', text: 'Supabase supports account and data services; Agora supports real-time media; Expo provides push delivery; Cloudflare supports selected media storage and delivery and has a configuration-gated Workers AI content-safety path. Stripe is integrated for a configuration-gated Business checkout. Actual production configuration and provider-specific disclosures require review.' }] },
    { id: 'retention-deletion', title: 'Retention and account controls', blocks: [{ type: 'paragraph', text: 'The proposed retention policy varies by data category and allows retention for as long as reasonably necessary to provide the service, protect people and the platform, meet legal obligations, preserve financial and transaction records, prevent fraud, resolve disputes and enforce agreements. No universal period is established. Settings offers profile and password changes; its account-deletion information entry points do not delete an account or submit a request. An official request channel remains to be established. Certain financial, transaction, security, dispute, audit or compliance records may remain when necessary or permitted. This is an owner policy draft awaiting legal and operational review, not a claim that all information is deleted.' }] },
    { id: 'legal-choices-contact', title: 'Legal choices and contact', blocks: [{ type: 'paragraph', text: 'Nelyon is the owner-selected brand and Nelyon, Inc. is the planned legal entity, not a verified registered corporation. The owner provided a Miami address and selected an 18-and-over eligibility rule without parental-consent exceptions. Registration does not currently establish age eligibility. Official contacts, applicable user rights, international handling, incorporation verification, operational age enforcement and effective date remain open before activation.' }] },
  ],
};

export const terms: LegalDocument = {
  id: 'terms', locale: 'en', version: 'draft-c4-unapproved', title: 'Terms of Service — unapproved draft',
  sections: [
    { id: 'accounts-eligibility', title: 'Accounts and eligibility', blocks: [{ type: 'paragraph', text: 'The owner has set the minimum eligibility age at 18, without a guardian-consent exception for younger accounts. The current registration path does not verify age, so this unapproved rule cannot be activated as an enforced product condition until that gap is resolved. The service supports registration, sign-in, profile controls and password changes.' }] },
    { id: 'content-conduct', title: 'Content and conduct', blocks: [{ type: 'paragraph', text: 'Users retain ownership of their content, subject to third-party rights. The proposed limited license to Nelyon is non-exclusive, worldwide and royalty-free, with sublicensing only insofar as needed for providers operating the service. It covers hosting, storing, processing, reproducing, transcoding, technical adaptation, distributing, displaying, performing, delivering and recommending content, and operating, protecting, improving and promoting Nelyon and content within the service. It does not transfer ownership or grant an unlimited unrelated commercial license. After removal, active uses of the license may end reasonably, subject to necessary legal, fraud, security, transaction, dispute, audit and backup records and content already lawfully shared. Reporting, blocking and moderation exist. Nelyon may restrict, hide or remove content and restrict, suspend or terminate accounts when reasonably necessary for policy violations, abuse, fraud, safety, others rights, legal duties or platform integrity; no universal advance-notice promise is made. All license and moderation language remains subject to legal review.' }] },
    { id: 'messages-live', title: 'Messaging and LIVE', blocks: [{ type: 'paragraph', text: 'The product supports conversations and LIVE participation, including host, viewer, co-host and Battle flows. Gifts have a separate financial authority. This draft does not promise recording, uninterrupted availability or creator revenue.' }] },
    { id: 'marketplace', title: 'Marketplace', blocks: [{ type: 'paragraph', text: 'The Marketplace supports seller listings, checkout, orders, shipping, returns and disputes. Payment, held-funds settlement and some refunds use server-side transaction records. Buyer and seller obligations, timing and final remedies require review; no universal refund or payout promise is made.' }] },
    { id: 'business-ads', title: 'Nelyon Business and Ads', blocks: [{ type: 'paragraph', text: 'Business has owner and delegated-member permissions for store, products, orders, media, analytics, finance and team. Ads Manager supports campaigns, placements and reporting. Access remains subject to the existing authorization mechanisms; contractual advertising terms require separate approval.' }] },
    { id: 'bdag-payments', title: 'BDAG and payments', blocks: [{ type: 'paragraph', text: 'BDAG is a unit within the Nelyon ecosystem used by certain features to record platform balances and transactions. Purchase, earning, receipt, use, transfer, withdrawal, payout and conversion may depend on the feature, eligibility, jurisdiction, provider, disclosed fee, limit and terms presented for the operation. No investment return is promised. No universal fixed conversion value is promised; operation-specific conversion conditions, if any, require disclosure and legal review. This description is not a final legal classification as currency, security, investment, deposit, bank account or cryptocurrency. Wallet and ledger authorities support transaction flows; legal characterization requires specialist review. The owner proposes that any applicable fee be disclosed and authorized in the specific operation, rather than asserting a universal rate. Per-flow verification remains necessary before activation.' }] },
    { id: 'refunds-payouts', title: 'Refunds and payouts', blocks: [{ type: 'paragraph', text: 'The code has conditional refund and payout workflows, including held-payment dispute handling and stablecoin conversion checks. Refunds depend on the operation, its state and applicable policies, not a universal guarantee. Payouts depend on eligibility, validation, provider and transaction terms, without a universal minimum or fixed processing time. Availability, network risks and legally binding commitments require review.' }] },
    { id: 'moderation-termination', title: 'Moderation and termination', blocks: [{ type: 'paragraph', text: 'Moderation includes reports, warnings and account-suspension operations. The settings screen does not itself complete account deletion. Notice periods, appeals, effects on records and termination rights require owner and legal approval.' }] },
    { id: 'third-parties', title: 'Third-party services', blocks: [{ type: 'paragraph', text: 'External account, media, push, payment and storage integrations support portions of the service. Their contractual allocation of responsibility and any applicable third-party terms require legal review.' }] },
    { id: 'legal-terms', title: 'Proposed law and dispute process', blocks: [{ type: 'paragraph', text: 'The owner proposes Florida law and applicable United States federal law, without limiting non-waivable rights. The proposed dispute process starts with an attempt at informal resolution for 30 days after valid notice. If unresolved, the proposed forum is a competent state or federal court in Miami-Dade County, Florida, subject to any legally mandatory forum. The owner proposes no mandatory arbitration, no class-action waiver and no jury-trial waiver. This is a policy draft pending legal review, not an operative forum clause. Registration of the planned entity, liability terms, changes to these terms, official contacts, reviewed translations and an effective date remain open.' }] },
  ],
};

export const legalDocuments: readonly LegalDocument[] = [privacy, terms];
