import React,{useCallback,useEffect,useState}from'react';
import{Pressable,RefreshControl,ScrollView,StyleSheet,Text,View}from'react-native';
import{MaterialIcons}from'@expo/vector-icons';
import{useRouter}from'expo-router';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme';
import{fetchMyMarketplaceCommerceAnalytics,fetchMyMarketplaceVariantAnalytics,type MarketplaceSellerAnalytics,type MarketplaceVariantAnalyticsRow}from'@/services/marketplaceAnalyticsService';
import{analyticsUtcRange,formatBDAG,formatEventRate,formatMetricCount,marketplaceSourceLabel,normalizeDailyAnalytics}from'@/services/marketplaceSellerCenterCore.mjs';
import{SellerEmptyState,SellerMetricCard,SellerRangeSelector,SellerSalesChart,SellerSectionHeader,SellerSkeleton}from'@/components/marketplace/SellerCenterUI';
import{SellerScreenHeader}from'@/components/marketplace/SellerScreenHeader';

export default function SellerAnalytics(){const router=useRouter(),insets=useSafeAreaInsets();const[range,setRange]=useState(30),[analytics,setAnalytics]=useState<MarketplaceSellerAnalytics|null>(null),[variants,setVariants]=useState<MarketplaceVariantAnalyticsRow[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(false);
 const load=useCallback(async(days=range,refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);const{dateFrom,dateTo}=analyticsUtcRange(days);try{const[value,variantRows]=await Promise.all([fetchMyMarketplaceCommerceAnalytics(dateFrom,dateTo),fetchMyMarketplaceVariantAnalytics(dateFrom,dateTo)]);setAnalytics(value);setVariants(variantRows);setError(false)}catch{setError(true)}finally{setLoading(false);setRefreshing(false)}},[range]);
 useEffect(()=>{void load()},[load]);const changeRange=(days:number)=>{setRange(days)};const summary=analytics?.summary,chartRows=analytics?normalizeDailyAnalytics(analytics.daily,range,analytics.date_to):[];const noData=summary?summary.product_views===0&&summary.orders===0&&summary.add_to_cart_events===0:false;
 return <View style={[s.page,{paddingTop:insets.top}]}><SellerScreenHeader title="Seller Analytics" fallbackRoute="/seller"/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(range,true)} tintColor={Colors.primary}/>} contentContainerStyle={s.content}>
  <View style={s.rangeRow}><View><Text style={s.title}>Rendimiento</Text><Text style={s.subtitle}>Métricas en UTC</Text></View><SellerRangeSelector value={range} onChange={changeRange}/></View>
  {loading?<SellerSkeleton rows={5}/>:error?<View style={s.error}><MaterialIcons name="error-outline" size={28} color={Colors.error}/><Text style={s.errorTitle}>No pudimos cargar las estadísticas</Text><Pressable accessibilityRole="button" style={s.retry} onPress={()=>void load()}><Text style={s.retryText}>Reintentar</Text></Pressable></View>:analytics&&summary?<>{noData?<SellerEmptyState title="Todavía no hay datos para este período" body="Los datos están disponibles desde la activación de métricas."/>:<>
   <SellerSectionHeader title="Resumen"/><View style={s.metrics}><SellerMetricCard accent label="Ventas brutas" value={formatBDAG(summary.gross_merchandise_bdag)}/><SellerMetricCard label="Pedidos" value={formatMetricCount(summary.orders)}/><SellerMetricCard label="Líneas compradas" value={formatMetricCount(summary.purchase_items)}/><SellerMetricCard label="Unidades" value={formatMetricCount(summary.units_sold)}/><SellerMetricCard label="Vistas" value={formatMetricCount(summary.product_views)}/><SellerMetricCard label="Sesiones únicas" value={formatMetricCount(summary.unique_viewer_sessions)}/><SellerMetricCard label="Carritos" value={formatMetricCount(summary.add_to_cart_events)}/><SellerMetricCard label="Checkouts iniciados" value={formatMetricCount(summary.checkout_started)}/></View>
   <SellerSectionHeader title="Ventas brutas"/><SellerSalesChart rows={chartRows}/>
   <SellerSectionHeader title="Actividad"/><View style={s.rates}><Rate label="Actividad vista → carrito" value={summary.view_to_cart_event_rate}/><Rate label="Actividad vista → compra" value={summary.view_to_purchase_event_rate}/><Text style={s.rateNote}>Esta relación compara eventos registrados y puede superar 100%. No representa una conversión de usuarios únicos.</Text></View>
   <SellerSectionHeader title="Productos principales"/>{analytics.products.length?<View style={s.stack}>{analytics.products.slice(0,10).map(row=><Pressable accessibilityRole="button" accessibilityLabel={`Editar ${row.title??'producto'}`} key={row.product_id} style={s.row} onPress={()=>router.push(`/seller/product-editor/${row.product_id}` as never)}><View style={s.flex}><Text style={s.rowTitle} numberOfLines={1}>{row.title??'Producto'}</Text><Text style={s.rowMeta}>{formatMetricCount(row.units_sold)} unidades · {formatMetricCount(row.purchase_orders)} pedidos</Text><Text style={s.rowMeta}>{formatMetricCount(row.views)} vistas · {formatMetricCount(row.add_to_cart)} carritos</Text></View><Text style={s.money}>{formatBDAG(row.gmv_bdag)}</Text></Pressable>)}</View>:<SellerEmptyState title="Sin actividad de productos"/>}
   <SellerSectionHeader title="Variantes principales"/>{variants.length?<View style={s.stack}>{variants.slice(0,8).map(row=><View key={row.variant_id} style={s.row}><View style={s.flex}><Text style={s.rowTitle} numberOfLines={1}>{row.product_title??'Producto'}</Text><Text style={s.rowMeta}>{row.sku??'Variante'} · {formatMetricCount(row.purchase_orders)} pedidos</Text></View><View style={s.right}><Text style={s.money}>{formatBDAG(row.gmv_bdag)}</Text><Text style={s.rowMeta}>{formatMetricCount(row.units_sold)} unidades</Text></View></View>)}</View>:<SellerEmptyState title="Sin actividad de variantes"/>}
   <SellerSectionHeader title="Fuentes de tráfico"/>{analytics.sources.filter(row=>row.views||row.add_to_cart||row.orders||row.gmv_bdag).length?<View style={s.stack}>{analytics.sources.filter(row=>row.views||row.add_to_cart||row.orders||row.gmv_bdag).map(row=><View key={row.source_type} style={s.source}><View style={s.flex}><Text style={s.rowTitle}>{marketplaceSourceLabel(row.source_type)}</Text><Text style={s.rowMeta}>{formatMetricCount(row.views)} vistas · {formatMetricCount(row.add_to_cart)} carritos · {formatMetricCount(row.orders)} pedidos</Text></View><Text style={s.money}>{formatBDAG(row.gmv_bdag)}</Text></View>)}</View>:<SellerEmptyState title="Sin fuentes con actividad"/>}
  </>}</>:null}
 </ScrollView></View>}
function Rate({label,value}:{label:string;value:number}){return <View accessible accessibilityLabel={`${label}: ${formatEventRate(value)}`} style={s.rate}><Text style={s.rateLabel}>{label}</Text><Text style={s.rateValue}>{formatEventRate(value)}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.bg},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:Spacing.xxl},rangeRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.extrabold},subtitle:{color:Colors.textSecondary,fontSize:FontSize.xs,marginTop:2},metrics:{flexDirection:'row',flexWrap:'wrap',gap:Spacing.sm},rates:{padding:Spacing.md,gap:Spacing.sm,backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg},rate:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rateLabel:{color:Colors.textSecondary,flex:1},rateValue:{color:Colors.textPrimary,fontWeight:FontWeight.extrabold,fontSize:FontSize.lg},rateNote:{color:Colors.textSubtle,fontSize:FontSize.xs,lineHeight:17,borderTopWidth:1,borderTopColor:Colors.borderSubtle,paddingTop:Spacing.sm},stack:{gap:Spacing.sm},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:Spacing.sm,padding:Spacing.md,backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg},source:{minHeight:68,flexDirection:'row',alignItems:'center',gap:Spacing.sm,padding:Spacing.md,backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg},flex:{flex:1},right:{alignItems:'flex-end'},rowTitle:{color:Colors.textPrimary,fontWeight:FontWeight.bold},rowMeta:{color:Colors.textSecondary,fontSize:FontSize.xs,marginTop:4},money:{color:Colors.accent,fontWeight:FontWeight.bold},error:{padding:Spacing.xl,alignItems:'center',gap:Spacing.md,backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg},errorTitle:{color:Colors.textPrimary,fontWeight:FontWeight.bold},retry:{minHeight:44,justifyContent:'center',paddingHorizontal:Spacing.lg,borderRadius:Radius.md,backgroundColor:Colors.primary},retryText:{color:Colors.textOnBrand,fontWeight:FontWeight.bold}});
