import React,{useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,StyleSheet,Text,View} from 'react-native';
import {useFocusEffect,useRouter} from 'expo-router';import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useShop} from '@/hooks/useShop';import {Colors,FontSize,FontWeight,Radius,Spacing} from '@/constants/theme';
export default function SellerProducts(){
 const router=useRouter();const insets=useSafeAreaInsets();const {myProducts,isLoading,fetchMyProducts,setPublished,deleteProduct}=useShop();
 useFocusEffect(useCallback(()=>{void fetchMyProducts();},[fetchMyProducts]));
 return <View style={[s.page,{paddingTop:insets.top}]}><View style={s.header}><Text style={s.title}>Mis productos</Text><Pressable style={s.add} onPress={()=>router.push('/create-product')}><Text style={s.addText}>Crear</Text></Pressable></View>
 {isLoading?<ActivityIndicator color={Colors.primary}/>:<FlatList data={myProducts} keyExtractor={item=>item.id} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>Todavía no tienes productos.</Text>} renderItem={({item})=><View style={s.card}><View style={s.grow}><Text style={s.name}>{item.title}</Text><Text style={s.meta}>{item.price.toFixed(8).replace(/0+$/,'').replace(/\.$/,'')} BDAG · {item.status} · {item.moderation_status}</Text></View><Pressable onPress={()=>router.push(`/seller/product/${item.id}/edit` as never)}><Text style={s.link}>Editar</Text></Pressable><Pressable onPress={()=>void setPublished(item.id,item.status!=='active')}><Text style={s.link}>{item.status==='active'?'Pausar':'Publicar'}</Text></Pressable><Pressable onPress={()=>void deleteProduct(item.id)}><Text style={[s.link,{color:Colors.secondary}]}>Eliminar</Text></Pressable></View>}/>}</View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.bg},header:{padding:Spacing.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.bold},add:{backgroundColor:Colors.primary,paddingHorizontal:Spacing.md,paddingVertical:Spacing.sm,borderRadius:Radius.md},addText:{color:'#000',fontWeight:FontWeight.bold},list:{padding:Spacing.lg,gap:Spacing.sm},empty:{color:Colors.textSecondary,textAlign:'center'},card:{backgroundColor:Colors.surfaceElevated,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:Spacing.md,flexDirection:'row',alignItems:'center',gap:Spacing.sm},grow:{flex:1},name:{color:Colors.textPrimary,fontWeight:FontWeight.semibold},meta:{color:Colors.textSubtle,fontSize:FontSize.xs,marginTop:4},link:{color:Colors.primary,fontSize:FontSize.xs}});
