import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ActivityIndicator,Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{useLocalSearchParams,useRouter}from'expo-router';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{Colors,Radius,Spacing}from'@/constants/theme';
import{fetchMyMarketplaceShippingProfiles,upsertMyMarketplaceShippingProfile,type MarketplaceShippingRegion}from'@/services/marketplaceShippingService';

type DraftRule=Omit<MarketplaceShippingRegion,'status'|'freeShippingThreshold'>&{freeShippingThreshold:string|null};
const blankRule:DraftRule={countryCode:'US',regionCode:null,shippingPrice:0,freeShippingThreshold:null,transitDaysMin:3,transitDaysMax:7};
export default function SellerShippingProfileScreen(){
 const router=useRouter(),insets=useSafeAreaInsets(),params=useLocalSearchParams<{storeId:string;profileId:string}>(),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[name,setName]=useState('Envío principal'),[shipsFrom,setShipsFrom]=useState('US'),[processingMin,setProcessingMin]=useState('1'),[processingMax,setProcessingMax]=useState('3'),[returns,setReturns]=useState('Devoluciones dentro de 14 días.'),[productsUsing,setProductsUsing]=useState(0),[rules,setRules]=useState<DraftRule[]>([blankRule]);
 const load=useCallback(async()=>{if(!params.storeId)return;setLoading(true);try{const profiles=await fetchMyMarketplaceShippingProfiles(params.storeId),profile=profiles.find(item=>item.id===params.profileId);if(profile){setName(profile.name);setShipsFrom(profile.shipsFromCountry);setProcessingMin(String(profile.processingDaysMin));setProcessingMax(String(profile.processingDaysMax));setReturns(profile.returnPolicySummary);setProductsUsing(profile.productsUsing);setRules(profile.regions.length?profile.regions.map(({status:_,...r})=>({...r,freeShippingThreshold:r.freeShippingThreshold==null?null:String(r.freeShippingThreshold)})):[blankRule]);}}catch{Alert.alert('No pudimos cargar el perfil','Reintenta desde Mis productos.');}finally{setLoading(false);}},[params.profileId,params.storeId]);
 useEffect(()=>{void load();},[load]);
 const valid=useMemo(()=>{const pMin=Number(processingMin),pMax=Number(processingMax);return name.trim().length>1&&/^[A-Za-z]{2}$/.test(shipsFrom.trim())&&Number.isInteger(pMin)&&pMin>=0&&pMin<=pMax&&returns.trim().length>=10&&rules.length>0&&rules.every(r=>/^[A-Za-z]{2}$/.test(r.countryCode.trim())&&Number.isFinite(Number(r.shippingPrice))&&Number(r.shippingPrice)>=0&&Number.isInteger(Number(r.transitDaysMin))&&Number(r.transitDaysMin)>=0&&Number(r.transitDaysMin)<=Number(r.transitDaysMax));},[name,processingMax,processingMin,returns,rules,shipsFrom]);
 const save=async()=>{if(!valid||!params.storeId)return;const keys=new Set<string>();for(const r of rules){const key=`${r.countryCode.trim().toUpperCase()}:${r.regionCode?.trim().toUpperCase()??'*'}`;if(keys.has(key)){Alert.alert('Destino duplicado','Cada país o región solo puede aparecer una vez.');return;}keys.add(key);}setSaving(true);try{await upsertMyMarketplaceShippingProfile({profileId:params.profileId||null,storeId:params.storeId,name:name.trim(),processingDaysMin:Number(processingMin),processingDaysMax:Number(processingMax),shipsFromCountry:shipsFrom.trim(),returnPolicySummary:returns.trim(),regions:rules.map(r=>({countryCode:r.countryCode,regionCode:r.regionCode?.trim()||null,shippingPrice:Number(r.shippingPrice),freeShippingThreshold:r.freeShippingThreshold?Number(r.freeShippingThreshold):null,transitDaysMin:Number(r.transitDaysMin),transitDaysMax:Number(r.transitDaysMax)}))});Alert.alert('Perfil actualizado','Los destinos ya están configurados y los productos vinculados pueden volver a aceptar compras.',[{text:'Listo',onPress:()=>router.back()}]);}catch{Alert.alert('No pudimos guardar','Revisa destinos, precios y rangos e inténtalo nuevamente.');}finally{setSaving(false);}};
 if(loading)return <View style={[styles.root,styles.center]}><ActivityIndicator color={Colors.primary}/></View>;
 return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={{paddingTop:insets.top+Spacing.md,padding:Spacing.md,gap:Spacing.md}} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Configurar destinos</Text><View style={styles.warning}><Text style={styles.warningTitle}>Configuración requerida</Text><Text style={styles.text}>{productsUsing} productos vinculados no pueden aceptar compras hasta completar este perfil.</Text></View>
  <Field label="Nombre" value={name} onChange={setName}/><Field label="País de origen (ISO)" value={shipsFrom} onChange={setShipsFrom}/><View style={styles.row}><Field label="Preparación mín." value={processingMin} onChange={setProcessingMin}/><Field label="Preparación máx." value={processingMax} onChange={setProcessingMax}/></View><Field label="Política de devolución" value={returns} onChange={setReturns}/>
  <Text style={styles.heading}>Destinos explícitos</Text>{rules.map((rule,index)=><View key={index} style={styles.card}><View style={styles.row}><Field label="País" value={rule.countryCode} onChange={v=>setRules(x=>x.map((r,i)=>i===index?{...r,countryCode:v}:r))}/><Field label="Región (opcional)" value={rule.regionCode??''} onChange={v=>setRules(x=>x.map((r,i)=>i===index?{...r,regionCode:v||null}:r))}/></View><Field label="Precio BDAG" value={String(rule.shippingPrice)} onChange={v=>setRules(x=>x.map((r,i)=>i===index?{...r,shippingPrice:Number(v)}:r))}/><View style={styles.row}><Field label="Tránsito mín." value={String(rule.transitDaysMin)} onChange={v=>setRules(x=>x.map((r,i)=>i===index?{...r,transitDaysMin:Number(v)}:r))}/><Field label="Tránsito máx." value={String(rule.transitDaysMax)} onChange={v=>setRules(x=>x.map((r,i)=>i===index?{...r,transitDaysMax:Number(v)}:r))}/></View>{rules.length>1?<Pressable onPress={()=>setRules(x=>x.filter((_,i)=>i!==index))}><Text style={styles.remove}>Eliminar destino</Text></Pressable>:null}</View>)}
  <Pressable style={styles.secondary} onPress={()=>setRules(x=>[...x,{...blankRule}])}><Text style={styles.link}>Agregar destino</Text></Pressable><Pressable disabled={!valid||saving} style={[styles.primary,(!valid||saving)&&styles.disabled]} onPress={()=>void save()}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Guardar configuración</Text>}</Pressable></ScrollView></KeyboardAvoidingView>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} style={styles.input} autoCapitalize="characters"/></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{alignItems:'center',justifyContent:'center'},title:{fontSize:24,fontWeight:'800',color:Colors.textPrimary},heading:{fontSize:18,fontWeight:'700',color:Colors.textPrimary},warning:{padding:Spacing.md,borderRadius:Radius.md,backgroundColor:Colors.warningDim,gap:6},warningTitle:{color:Colors.warning,fontWeight:'700'},text:{color:Colors.textSecondary},row:{flexDirection:'row',gap:Spacing.sm},field:{flex:1,gap:5},label:{color:Colors.textSecondary,fontSize:12},input:{minHeight:46,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,color:Colors.textPrimary,paddingHorizontal:Spacing.sm,backgroundColor:Colors.surface},card:{padding:Spacing.md,gap:Spacing.sm,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md},remove:{color:Colors.error},secondary:{padding:14,alignItems:'center'},link:{color:Colors.primaryLight,fontWeight:'700'},primary:{minHeight:52,backgroundColor:Colors.primary,borderRadius:Radius.md,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'700'},disabled:{opacity:.45}});
