import {useEffect,useState} from "react";
import {AdminEntityLink,AdminFact,AdminFactGrid,AdminIdentity,AdminMediaPreview,asRecord,humanValue,shortId} from "./AdminPresentation";
import {formatDate,getAdminMediaUrl} from "../lib/adminApi";

export function AdminReportSubject({subject,reportId}:{subject:Record<string,unknown>|null;reportId:string}){
  const [signedUrl,setSignedUrl]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[nonce,setNonce]=useState(0);
  const type=String(subject?.type??""),assetId=typeof subject?.media_asset_id==="string"?subject.media_asset_id:null,publicUrl=typeof subject?.preview_url==="string"?subject.preview_url:typeof subject?.thumbnail_url==="string"?subject.thumbnail_url:null;
  useEffect(()=>{if(!assetId||publicUrl||!subject){setSignedUrl(publicUrl);setError(null);return}const surface=type==="story"?"story":type==="message"?"reported_message":null;if(!surface){setSignedUrl(null);return}let active=true;setLoading(true);setError(null);void getAdminMediaUrl(assetId,{surface,entityId:surface==="story"?String(subject.id):reportId}).then((url)=>{if(active)setSignedUrl(url)}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"No se pudo cargar la media")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[assetId,publicUrl,type,subject,reportId,nonce]);
  if(!subject)return <div className="admin-status-panel warning"><i/><div><strong>Contenido no disponible</strong><span>El recurso reportado ya no está disponible o no es visible con tus capabilities.</span></div></div>;
  const owner=asRecord(subject.owner??subject.sender),kind=String(subject.media_type??subject.message_type??"image");
  if(type==="user")return <div className="presentation-stack"><AdminIdentity value={subject}/><AdminFactGrid><AdminFact label="Usuario" value={humanValue(subject.username)}/><AdminFact label="ID" value={shortId(subject.id)} mono/></AdminFactGrid></div>;
  return <div className="presentation-stack">{Boolean(publicUrl||assetId)&&<div className="admin-media-frame"><AdminMediaPreview url={signedUrl} kind={kind==="voice"?"audio":kind} alt={`Vista previa del ${type} reportado`} loading={loading} error={error} onRetry={()=>setNonce((x)=>x+1)} restricted={!publicUrl}/></div>} {Object.keys(owner).length>0&&<AdminIdentity value={owner}/>} {type==="video"&&<p>{humanValue(subject.caption,"Sin caption")}</p>}{type==="comment"&&<p>{humanValue(subject.text,"Sin texto")}</p>}{type==="message"&&<p>{humanValue(subject.text_excerpt,subject.has_media===true?"Mensaje multimedia":"Sin texto visible")}</p>}<AdminFactGrid><AdminFact label="Tipo" value={type}/><AdminFact label="Creado" value={formatDate(subject.created_at)}/><AdminFact label="Estado" value={subject.hidden===true?"Oculto":humanValue(subject.visibility,"Visible")}/><AdminFact label="ID" value={shortId(subject.id)} mono/>{Boolean(subject.video_id)&&<AdminFact label="Video relacionado" value={<AdminEntityLink to={`/content/video/${String(subject.video_id)}`} id={subject.video_id}/>}/>} {Boolean(subject.expires_at)&&<AdminFact label="Expira" value={formatDate(subject.expires_at)}/>} {Boolean(subject.story_kind)&&<AdminFact label="Story" value={humanValue(subject.story_kind)}/>}</AdminFactGrid></div>
}
