import React,{useEffect,useMemo,useRef,useState}from'react';
import{ActivityIndicator,Alert,FlatList,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{randomUUID}from'expo-crypto';
import{useRouter}from'expo-router';
import{Image}from'@/components/ui/SafeImage';
import{fetchMarketplaceProductDetail,type MarketplaceProductDetail}from'@/services/marketplaceService';
import{isOptionValueSelectable,reconcileVariantSelection,resolveExactVariant,selectionForPreferredVariant,type MarketplaceVariantSelection}from'@/services/marketplaceVariantSelection';
import{createLiveCheckoutReservation,fetchLiveSessionProducts,fetchMyActiveLiveCheckout,LiveCommerceError,type LiveSessionProduct}from'@/services/liveCommerceService';
import{liveReservationSignature,reservationCommandFor,stageAfterVisibilityChange,type PendingReservationCommand}from'@/services/liveCommerceState';
import{fetchAuthoritativeBdagBalance,MarketplacePaymentError,payMarketplaceCheckout}from'@/services/marketplacePaymentService';
import{cancelCheckoutReservation,fetchMyActiveCheckout,fetchMyCheckout,normalizeShippingAddress,validateShippingAddress,type ShippingAddressInput}from'@/services/marketplaceOrderService';

type Stage='shelf'|'product'|'shipping'|'reservation'|'active_other'|'success';
type Reservation={id:string;reference:string;status:string;expiresAt:string;total:number;orderId:string|null};
const EMPTY:ShippingAddressInput={recipientName:'',line1:'',city:'',region:'',postalCode:'',country:'',phone:''};

export function LiveViewerCommerce({visible,sessionId,products,onClose,onRefresh}:{visible:boolean;sessionId:string;products:LiveSessionProduct[];onClose:()=>void;onRefresh:()=>Promise<void>}){
 const router=useRouter();
 const[stage,setStage]=useState<Stage>('shelf');
 const[pin,setPin]=useState<LiveSessionProduct|null>(null);
 const[detail,setDetail]=useState<MarketplaceProductDetail|null>(null);
 const[selection,setSelection]=useState<MarketplaceVariantSelection>({});
 const[quantity,setQuantity]=useState(1);
 const[address,setAddress]=useState<ShippingAddressInput>(EMPTY);
 const[reservation,setReservation]=useState<Reservation|null>(null);
 const[otherCheckoutId,setOtherCheckoutId]=useState<string|null>(null);
 const[balance,setBalance]=useState<number|null>(null);
 const[successOrderId,setSuccessOrderId]=useState<string|null>(null);
 const[busy,setBusy]=useState(false);
 const[remaining,setRemaining]=useState(0);
 const[terminal,setTerminal]=useState<string|null>(null);
 const pendingCommand=useRef<PendingReservationCommand|null>(null),paymentKey=useRef<string|null>(null),lock=useRef(false),previousVisible=useRef(false);

 useEffect(()=>{const wasVisible=previousVisible.current;previousVisible.current=visible;if(!wasVisible&&visible)setStage(current=>stageAfterVisibilityChange(wasVisible,visible,current,!!reservation,current==='success','shelf'))},[visible,reservation]);
 useEffect(()=>{if(!reservation||reservation.status!=='pending_payment')return;const tick=()=>setRemaining(Math.max(0,Math.floor((Date.parse(reservation.expiresAt)-Date.now())/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[reservation]);
 const variant=useMemo(()=>detail?resolveExactVariant(detail.options,detail.variants,selection):undefined,[detail,selection]);
 const canBuy=!!variant&&variant.available_quantity>0;
 const refreshBalance=async()=>{try{setBalance(await fetchAuthoritativeBdagBalance())}catch{/* payment remains authoritative */}};

 const open=async(item:LiveSessionProduct)=>{if(item.availability!=='available')return;setBusy(true);setTerminal(null);try{await onRefresh();const current=(await fetchLiveSessionProducts(sessionId)).find(value=>value.id===item.id);if(!current||current.availability!=='available')throw new Error('unavailable');const next=await fetchMarketplaceProductDetail(item.productId);if(!next)throw new Error('unavailable');setPin(current);setDetail(next);setSelection(selectionForPreferredVariant(next.options,next.variants));setQuantity(1);pendingCommand.current=null;setStage('product')}catch{Alert.alert('Producto no disponible','Este producto ya no puede comprarse desde este LIVE.')}finally{setBusy(false)}};
 const choose=(optionId:string,valueId:string)=>{if(!detail)return;setSelection(current=>reconcileVariantSelection(detail.options,detail.variants,current,optionId,valueId));setQuantity(1);pendingCommand.current=null};

 const recoverActive=async()=>{if(!pin)return;const active=await fetchMyActiveLiveCheckout(sessionId).catch(()=>null);if(active&&active.pinId===pin.id){setReservation({id:active.checkoutId,reference:active.reference,status:active.status,expiresAt:active.expiresAt,total:active.total,orderId:active.orderId});paymentKey.current=randomUUID();await refreshBalance();setStage('reservation');return}const other=await fetchMyActiveCheckout().catch(()=>null);setOtherCheckoutId(other?.checkout.id??null);setStage('active_other')};
 const reserve=async()=>{if(lock.current||!pin||!variant||variant.available_quantity<1)return;const errors=validateShippingAddress(address);if(Object.keys(errors).length){Alert.alert('Revisa la dirección',Object.values(errors)[0]);return}lock.current=true;setBusy(true);setTerminal(null);try{const fresh=await fetchMarketplaceProductDetail(pin.productId),freshVariant=fresh?.variants.find(value=>value.id===variant.id&&value.status==='active'&&value.available_quantity>=quantity);if(!fresh||!freshVariant)throw new LiveCommerceError('live_commerce_product_unavailable');const normalized=normalizeShippingAddress(address),signature=liveReservationSignature(sessionId,pin.id,freshVariant.id,quantity,normalized),command=reservationCommandFor(signature,pendingCommand.current,randomUUID);pendingCommand.current=command;const result=await createLiveCheckoutReservation(sessionId,pin.id,freshVariant.id,quantity,normalized,command.idempotencyKey);pendingCommand.current=null;paymentKey.current=randomUUID();setReservation({id:result.checkout.id,reference:result.checkout.reference,status:result.checkout.status,expiresAt:result.checkout.expiresAt,total:result.checkout.total,orderId:result.orders[0]?.id??null});await refreshBalance();setStage('reservation')}catch(error){const code=error instanceof LiveCommerceError?error.code:'live_commerce_unknown';if(code==='marketplace_active_checkout_exists'){pendingCommand.current=null;await recoverActive()}else{if(code!=='live_commerce_transport')pendingCommand.current=null;Alert.alert(code==='live_commerce_live_ended'?'Este LIVE terminó':'No pudimos reservar',code==='live_commerce_live_ended'?'El producto ya no puede comprarse desde esta transmisión.':'No se realizó ningún cargo. Inténtalo nuevamente.')}}finally{lock.current=false;setBusy(false)}};

 const reconcilePayment=async()=>{if(!reservation)return false;const current=await fetchMyCheckout(reservation.id).catch(()=>null);if(current?.checkout.status==='paid'){setSuccessOrderId(current.orders[0]?.id??reservation.orderId);setReservation({...reservation,status:'paid'});setStage('success');return true}if(current?.checkout.status==='cancelled'||current?.checkout.status==='expired'){setTerminal(current.checkout.status==='expired'?'La reserva expiró.':'La reserva fue cancelada.');setReservation({...reservation,status:current.checkout.status})}return false};
 const pay=async()=>{if(lock.current||!reservation)return;lock.current=true;setBusy(true);setTerminal(null);try{await refreshBalance();const paid=await payMarketplaceCheckout(reservation.id,paymentKey.current??(paymentKey.current=randomUUID()));setSuccessOrderId(paid.orders[0]?.id??reservation.orderId);setReservation({...reservation,status:'paid'});setStage('success');await refreshBalance()}catch(error){const code=error instanceof MarketplacePaymentError?error.code:'marketplace_payment_unknown';if(code==='marketplace_payment_transport'||code==='marketplace_payment_already_processed'){const completed=await reconcilePayment();if(!completed&&code==='marketplace_payment_transport')Alert.alert('Pago por confirmar','Revisamos el estado. Puedes reintentar con seguridad.')}else if(code==='marketplace_insufficient_bdag_balance')Alert.alert('Saldo insuficiente','No tienes suficiente BDAG disponible para completar esta compra.');else if(code==='marketplace_checkout_expired'||code==='marketplace_checkout_cancelled'||code==='marketplace_checkout_not_payable'){await reconcilePayment();setTerminal('Esta reserva ya no puede pagarse.')}else Alert.alert('No pudimos completar el pago','No se realizó un segundo cobro. Inténtalo nuevamente.');await refreshBalance()}finally{lock.current=false;setBusy(false)}};
 const cancel=()=>{if(!reservation||lock.current)return;Alert.alert('Cancelar reserva','Los productos reservados volverán al inventario disponible.',[{text:'Volver',style:'cancel'},{text:'Cancelar reserva',style:'destructive',onPress:async()=>{lock.current=true;setBusy(true);try{await cancelCheckoutReservation(reservation.id);setReservation(null);setTerminal(null);paymentKey.current=null;pendingCommand.current=null;setStage('shelf');await onRefresh()}catch{Alert.alert('No pudimos cancelar','La reserva no cambió. Inténtalo nuevamente.')}finally{lock.current=false;setBusy(false)}}}])};

 const selectedImage=variant?.image_url??detail?.product.images[0]??pin?.imageUrl;
 const statusText=!variant?(detail?.options.every(option=>selection[option.id])?'Esta combinación no está disponible':'Completa tus opciones'):variant.available_quantity<1?'Agotado':null;
 const shelf=<FlatList data={[...products].sort((a,b)=>Number(b.isFeatured)-Number(a.isFeatured)||a.position-b.position)} keyExtractor={item=>item.id} ListEmptyComponent={<Text style={s.muted}>Este LIVE terminó o no tiene productos disponibles.</Text>} renderItem={({item})=><Pressable style={[s.row,item.availability!=='available'&&s.disabled]} onPress={()=>void open(item)} disabled={item.availability!=='available'} accessibilityRole="button" accessibilityLabel={`Ver producto ${item.title}`} accessibilityState={{disabled:item.availability!=='available'}}>{item.imageUrl?<Image source={{uri:item.imageUrl}} style={s.image}/>:<View style={s.image}/>}<View style={s.grow}><Text style={s.name}>{item.title}</Text><Text style={s.muted}>{item.storeName} · {item.minPrice.toFixed(2)} BDAG</Text><Text style={item.availability==='available'?s.available:s.unavailable}>{item.availability==='available'?'Ver producto':item.availability==='out_of_stock'?'Agotado':'No disponible'}</Text></View></Pressable>}/>;
 const product=detail&&pin?<ScrollView keyboardShouldPersistTaps="handled">{selectedImage?<Image source={{uri:selectedImage}} style={s.hero}/>:null}<Text style={s.title}>{detail.product.title}</Text><Text style={s.muted}>{detail.product.description}</Text>{detail.options.map(option=><View key={option.id}><Text style={s.label}>{option.name}</Text><View style={s.wrap}>{option.values.map(value=>{const disabled=!isOptionValueSelectable(detail.variants,value.id,selection,option.id),selected=selection[option.id]===value.id;return <Pressable key={value.id} style={[s.choice,selected&&s.choiceOn,disabled&&s.disabled]} disabled={disabled} onPress={()=>choose(option.id,value.id)} accessibilityRole="radio" accessibilityState={{selected,disabled}}><Text style={s.white}>{value.value}</Text></Pressable>})}</View></View>)}<Text style={s.price}>{variant?variant.price.toFixed(2):'—'} BDAG</Text>{statusText?<Text style={s.unavailable}>{statusText}</Text>:null}<View style={s.wrap}><Pressable style={s.choice} onPress={()=>setQuantity(value=>Math.max(1,value-1))}><Text style={s.white}>−</Text></Pressable><Text style={s.qty}>{quantity}</Text><Pressable style={[s.choice,!canBuy&&s.disabled]} disabled={!canBuy} onPress={()=>setQuantity(value=>Math.min(variant?.available_quantity??1,value+1))}><Text style={s.white}>+</Text></Pressable></View><Pressable style={[s.primary,!canBuy&&s.disabled]} disabled={!canBuy} onPress={()=>setStage('shipping')}><Text style={s.primaryText}>Comprar ahora</Text></Pressable></ScrollView>:null;
 const shipping=<ScrollView keyboardShouldPersistTaps="handled"><Text style={s.muted}>La compra se completa aquí; el video y Agora permanecen conectados.</Text>{([['recipientName','Nombre de quien recibe'],['line1','Dirección'],['city','Ciudad'],['region','Estado o provincia'],['postalCode','Código postal'],['country','País'],['phone','Teléfono (opcional)']]as const).map(([key,label])=><TextInput key={key} style={s.input} value={address[key]??''} onChangeText={value=>{setAddress(current=>({...current,[key]:value}));pendingCommand.current=null}} placeholder={label} placeholderTextColor="#777" accessibilityLabel={label}/>)}<Pressable style={s.primary} disabled={busy} onPress={()=>void reserve()}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Crear reserva de 15 minutos</Text>}</Pressable></ScrollView>;
 const reservationView=reservation?<ScrollView><Text style={s.title}>{reservation.reference}</Text><Text style={s.price}>{reservation.total.toFixed(2)} BDAG</Text><Text style={s.muted}>Saldo disponible: {balance==null?'—':balance.toFixed(2)} BDAG</Text><Text style={s.muted}>Reserva válida por {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</Text>{terminal?<Text style={s.unavailable}>{terminal}</Text>:null}<Pressable style={[s.primary,(busy||remaining===0||reservation.status!=='pending_payment')&&s.disabled]} disabled={busy||remaining===0||reservation.status!=='pending_payment'} onPress={()=>{void refreshBalance();Alert.alert('Pagar con BDAG','Tu pago quedará protegido en el escrow del Marketplace.',[{text:'Volver',style:'cancel'},{text:'Confirmar pago',onPress:()=>void pay()}])}}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Pagar con BDAG</Text>}</Pressable><Pressable style={s.secondary} onPress={cancel} disabled={busy||reservation.status!=='pending_payment'}><Text style={s.primaryText}>Cancelar reserva</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push(`/checkout/reservation/${reservation.id}` as never)}><Text style={s.primaryText}>Ver reserva</Text></Pressable></ScrollView>:null;
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><View style={s.header}><Text style={s.heading}>{stage==='shelf'?'Productos del LIVE':stage==='success'?'Compra confirmada':'Comprar dentro del LIVE'}</Text><Pressable style={s.close} onPress={onClose} accessibilityRole="button" accessibilityLabel="Cerrar productos"><Text style={s.closeText}>×</Text></Pressable></View>{busy&&stage==='shelf'?<ActivityIndicator color="#7C5CFF"/>:stage==='shelf'?shelf:stage==='product'?product:stage==='shipping'?shipping:stage==='reservation'?reservationView:stage==='active_other'?<View style={s.center}><Text style={s.title}>Ya tienes una reserva activa</Text><Pressable style={s.primary} onPress={onClose}><Text style={s.primaryText}>Continuar viendo el LIVE</Text></Pressable>{otherCheckoutId?<Pressable style={s.secondary} onPress={()=>router.push(`/checkout/reservation/${otherCheckoutId}` as never)}><Text style={s.primaryText}>Ver reserva</Text></Pressable>:null}</View>:<View style={s.center}><Text style={s.title}>Compra confirmada</Text><Text style={s.muted}>Tu pago quedó protegido y el vendedor preparará el pedido.</Text><Pressable style={s.primary} onPress={onClose}><Text style={s.primaryText}>Continuar viendo el LIVE</Text></Pressable>{successOrderId?<Pressable style={s.secondary} onPress={()=>router.push(`/orders/${successOrderId}` as never)}><Text style={s.primaryText}>Ver pedido</Text></Pressable>:null}</View>}</View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.55)'},sheet:{height:'86%',backgroundColor:'#121219',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},heading:{color:'#fff',fontSize:20,fontWeight:'700'},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeText:{fontSize:30,color:'#fff'},row:{flexDirection:'row',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.1)'},image:{width:72,height:72,borderRadius:12,backgroundColor:'#292934'},hero:{height:230,borderRadius:18,backgroundColor:'#292934',marginBottom:14},grow:{flex:1,gap:5},name:{color:'#fff',fontWeight:'700',fontSize:16},title:{color:'#fff',fontSize:22,fontWeight:'700',marginVertical:8},muted:{color:'#aaa',lineHeight:20},available:{color:'#B8A8FF',fontWeight:'700'},unavailable:{color:'#ff8b9f',marginVertical:6},disabled:{opacity:.45},label:{color:'#fff',fontWeight:'700',marginTop:16,marginBottom:8},wrap:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:8},choice:{minWidth:44,minHeight:44,padding:10,borderRadius:12,backgroundColor:'#292934',alignItems:'center',justifyContent:'center'},choiceOn:{backgroundColor:'#7C5CFF'},white:{color:'#fff'},price:{color:'#fff',fontSize:22,fontWeight:'700',marginVertical:18},qty:{color:'#fff',minWidth:30,textAlign:'center'},primary:{minHeight:50,borderRadius:15,backgroundColor:'#7C5CFF',alignItems:'center',justifyContent:'center',marginTop:18,padding:12},secondary:{minHeight:50,borderRadius:15,backgroundColor:'#292934',alignItems:'center',justifyContent:'center',marginTop:10,padding:12},primaryText:{color:'#fff',fontWeight:'700'},input:{minHeight:50,borderWidth:1,borderColor:'#343442',borderRadius:12,color:'#fff',paddingHorizontal:14,marginTop:10},center:{alignItems:'center',gap:12,paddingTop:30}});
