import React,{useCallback,useEffect,useRef,useState}from'react';
import{ActivityIndicator,FlatList,Modal,Pressable,RefreshControl,StyleSheet,Text,View}from'react-native';
import{randomUUID}from'expo-crypto';
import{Image}from'@/components/ui/SafeImage';
import{fetchMyLiveProductCandidates,featureLiveProduct,LiveCommerceError,pinLiveProduct,unpinLiveProduct,type LiveCandidateCursor,type LiveProductCandidate}from'@/services/liveCommerceService';
const PAGE_SIZE=20;
const message=(error:unknown)=>{const code=error instanceof LiveCommerceError?error.code:'live_commerce_unknown';if(code==='live_commerce_host_not_eligible')return'Tu cuenta de vendedor o tienda no está habilitada.';if(code==='live_commerce_pin_limit')return'Puedes fijar hasta 20 productos.';if(code==='live_commerce_product_unavailable'||code==='live_commerce_out_of_stock')return'Este producto ya no está disponible.';if(code==='live_commerce_transport')return'No pudimos conectar. Revisa tu conexión.';return'No pudimos completar la acción.'};
export function LiveHostProductManager({visible,sessionId,onClose,onChanged}:{visible:boolean;sessionId:string;onClose:()=>void;onChanged:()=>void}){
 const[items,setItems]=useState<LiveProductCandidate[]>([]),[cursor,setCursor]=useState<LiveCandidateCursor|null>(null),[initial,setInitial]=useState(false),[more,setMore]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[busyIds,setBusyIds]=useState<Set<string>>(new Set());const request=useRef(false);
 const apply=useCallback((incoming:LiveProductCandidate[],replace:boolean)=>setItems(current=>{const map=new Map((replace?[]:current).map(item=>[item.productId,item]));incoming.forEach(item=>map.set(item.productId,item));return[...map.values()]}),[]);
 const load=useCallback(async(mode:'initial'|'more'|'refresh')=>{if(request.current)return;if(mode==='more'&&!cursor)return;request.current=true;if(mode==='initial')setInitial(true);else if(mode==='more')setMore(true);else setRefreshing(true);setError(null);try{const page=await fetchMyLiveProductCandidates(sessionId,PAGE_SIZE,mode==='more'?cursor??undefined:undefined);apply(page.items,mode!=='more');setCursor(page.nextCursor)}catch(e){setError(message(e))}finally{request.current=false;setInitial(false);setMore(false);setRefreshing(false)}},[apply,cursor,sessionId]);
 // Reload only when the modal/session identity changes; cursor changes are page navigation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(visible){setItems([]);setCursor(null);void load('initial')}},[visible,sessionId]);
 const mutate=async(item:LiveProductCandidate,kind:'pin'|'unpin'|'feature')=>{if(busyIds.has(item.productId))return;setBusyIds(current=>new Set(current).add(item.productId));setError(null);try{if(kind==='pin')await pinLiveProduct(sessionId,item.productId,null,randomUUID());else if(kind==='unpin'&&item.pinId)await unpinLiveProduct(sessionId,item.pinId,randomUUID());else if(item.pinId)await featureLiveProduct(sessionId,item.pinId,randomUUID());await load('refresh');onChanged()}catch(e){setError(message(e))}finally{setBusyIds(current=>{const next=new Set(current);next.delete(item.productId);return next})}};
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><View style={s.header}><Text style={s.title}>Productos del LIVE</Text><Pressable style={s.close} onPress={onClose} accessibilityRole="button" accessibilityLabel="Cerrar productos"><Text style={s.closeText}>×</Text></Pressable></View>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text><Pressable onPress={()=>void load('refresh')}><Text style={s.retry}>Reintentar</Text></Pressable></View>:null}{initial?<ActivityIndicator color="#7C5CFF"/>:<FlatList data={items} keyExtractor={i=>i.productId} onEndReached={()=>{if(cursor&&!more)void load('more')}} onEndReachedThreshold={0.4} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load('refresh')} tintColor="#7C5CFF"/>} ListEmptyComponent={<Text style={s.muted}>No hay productos elegibles. Revisa tu Centro de vendedor.</Text>} ListFooterComponent={more?<ActivityIndicator color="#7C5CFF"/>:cursor?null:<Text style={s.end}>No hay más productos</Text>} renderItem={({item})=>{const busy=busyIds.has(item.productId);return <View style={s.row}>{item.imageUrl?<Image source={{uri:item.imageUrl}} style={s.image}/>:<View style={s.image}/>}<View style={s.info}><Text style={s.name}>{item.title}</Text><Text style={s.muted}>{item.minPrice.toFixed(2)} BDAG · {item.availableQuantity} disponibles</Text><View style={s.actions}><Pressable style={[s.small,busy&&s.disabled]} disabled={busy} onPress={()=>void mutate(item,item.isPinned?'unpin':'pin')} accessibilityRole="button" accessibilityState={{disabled:busy}}><Text style={s.smallText}>{item.isPinned?'Quitar':'Fijar'}</Text></Pressable>{item.isPinned&&!item.isFeatured?<Pressable style={[s.small,busy&&s.disabled]} disabled={busy} onPress={()=>void mutate(item,'feature')} accessibilityRole="button" accessibilityState={{disabled:busy}}><Text style={s.smallText}>Destacar</Text></Pressable>:null}{busy?<ActivityIndicator size="small" color="#B8A8FF"/>:item.isFeatured?<Text style={s.featured}>Destacado</Text>:null}</View></View></View>}}/>}</View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.55)'},sheet:{maxHeight:'82%',minHeight:'55%',backgroundColor:'#121219',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:16},title:{color:'#fff',fontSize:20,fontWeight:'700'},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeText:{color:'#fff',fontSize:30},row:{flexDirection:'row',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.1)'},image:{width:68,height:68,borderRadius:12,backgroundColor:'#292934'},info:{flex:1,gap:5},name:{color:'#fff',fontWeight:'700'},muted:{color:'#aaa'},actions:{flexDirection:'row',gap:8,alignItems:'center'},small:{paddingVertical:8,paddingHorizontal:12,borderRadius:14,backgroundColor:'#373249'},smallText:{color:'#fff',fontWeight:'600'},featured:{color:'#B8A8FF',fontWeight:'700'},disabled:{opacity:.45},error:{padding:10,borderRadius:12,backgroundColor:'rgba(255,45,85,.15)',marginBottom:8},errorText:{color:'#ffb1bf'},retry:{color:'#fff',fontWeight:'700',marginTop:6},end:{color:'#777',textAlign:'center',padding:12}});
