import React,{useCallback,useRef,useState}from'react';
import{ActivityIndicator,Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{randomUUID}from'expo-crypto';
import{useFocusEffect,useLocalSearchParams,useRouter}from'expo-router';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme';
import{fetchSellerOrder,isSafeTrackingUrl,MarketplaceFulfillmentError,shipSellerOrder,startSellerOrderProcessing,type MarketplaceOrderDetail}from'@/services/marketplaceFulfillmentService';
import{formatBDAG,sellerOrderItemsSubtotal}from'@/services/marketplaceSellerCenterCore.mjs';
import{OrderTimeline,StatusBadge}from'@/components/marketplace/OrderStatus';
import{SellerScreenHeader}from'@/components/marketplace/SellerScreenHeader';
import{MarketplaceSellerDisputePanel}from'@/components/marketplace/MarketplaceSellerDisputePanel';
import{MarketplaceReturnPanel}from'@/components/marketplace/MarketplaceReturnPanel';
const messageFor=(error:unknown):[string,string]=>{const code=error instanceof MarketplaceFulfillmentError?error.code:'marketplace_fulfillment_unknown';return({marketplace_seller_not_approved:['Acceso no disponible','Tu cuenta no está habilitada para administrar este pedido.'],marketplace_store_inactive:['Tienda no disponible','Activa tu tienda para administrar pedidos.'],marketplace_order_not_fulfillable:['Pedido no procesable','Este pedido no puede avanzar desde su estado actual.'],marketplace_invalid_shipment:['Revisa el envío','Verifica el transportista y el seguimiento.'],marketplace_fulfillment_transport:['No pudimos conectar','Revisa tu conexión e inténtalo nuevamente.'],marketplace_fulfillment_outcome_unknown:['Estado por confirmar','No pudimos confirmar el estado del pedido. Puedes volver a intentarlo con seguridad.']}as Record<string,[string,string]>)[code]??['Pedido no disponible','No pudimos cargar este pedido.']};
export default function SellerOrder(){const{id}=useLocalSearchParams<{id:string}>(),router=useRouter(),insets=useSafeAreaInsets();const[data,setData]=useState<MarketplaceOrderDetail|null>(null),[busy,setBusy]=useState(false),[state,setState]=useState<'loading'|'loaded'|'error'>('loading'),[error,setError]=useState<[string,string]>(['Pedido no disponible','No pudimos cargar este pedido.']);const lock=useRef(false),processKey=useRef(randomUUID()),shipKey=useRef(randomUUID());const[carrier,setCarrier]=useState(''),[service,setService]=useState(''),[tracking,setTracking]=useState(''),[url,setUrl]=useState(''),[note,setNote]=useState('');const load=useCallback(async()=>{if(!id){setState('error');return}setState('loading');try{setData(await fetchSellerOrder(id));setState('loaded')}catch(reason){setData(null);setError(messageFor(reason));setState('error')}},[id]);useFocusEffect(useCallback(()=>{void load()},[load]));const run=async(action:()=>Promise<MarketplaceOrderDetail>)=>{if(lock.current)return;lock.current=true;setBusy(true);try{const updated=await action();setData(updated)}catch(reason){const copy=messageFor(reason);Alert.alert(copy[0],copy[1])}finally{lock.current=false;setBusy(false)}};const prepare=()=>Alert.alert('Preparar pedido','El comprador verá que el pedido está en preparación.',[{text:'Volver',style:'cancel'},{text:'Preparar',onPress:()=>void run(()=>startSellerOrderProcessing(id!,processKey.current))}]);const ship=()=>{if(carrier.trim().length<2||tracking.trim().length<2||!isSafeTrackingUrl(url)){Alert.alert('Revisa el envío','Completa el transportista y seguimiento. El enlace opcional debe usar HTTPS.');return}Alert.alert('Confirmar envío','El comprador verá estos datos de seguimiento.',[{text:'Volver',style:'cancel'},{text:'Marcar como enviado',onPress:()=>void run(()=>shipSellerOrder(id!,{carrierName:carrier,serviceLevel:service,trackingNumber:tracking,trackingUrl:url,sellerNote:note},shipKey.current))}])};
 if(state==='loading')return <View style={[s.root,s.center,{paddingTop:insets.top}]}><ActivityIndicator color={Colors.primary}/></View>;if(state==='error'||!data)return <View style={[s.root,s.center,{paddingTop:insets.top}]}><Text style={s.title}>{error[0]}</Text><Text style={s.muted}>{error[1]}</Text><Pressable accessibilityRole="button" style={s.button} onPress={()=>void load()}><Text style={s.buttonText}>Reintentar</Text></Pressable><Pressable accessibilityRole="button" style={s.secondaryButton} onPress={()=>router.replace('/seller/orders' as never)}><Text style={s.secondaryText}>Volver a pedidos</Text></Pressable></View>;
 return <View style={[s.root,{paddingTop:insets.top}]}><SellerScreenHeader title="Detalle del pedido" fallbackRoute="/seller/orders"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.orderHeader}><View><Text style={s.eyebrow}>PEDIDO</Text><Text style={s.title}>{data.order.orderNumber}</Text><Text style={s.muted}>{new Date(data.order.createdAt).toLocaleString()}</Text></View><StatusBadge status={data.order.status}/></View>{data.postMutationRefreshFailed?<View style={s.refreshNotice}><Text style={s.refreshNoticeText}>El pedido se actualizó, pero no pudimos cargar todos los detalles. Desliza para volver a cargar.</Text></View>:null}
  <Section title="PRODUCTOS">{data.items.map(item=><View key={item.id} style={s.item}>{item.imageUrl?<Image source={{uri:item.imageUrl}} style={s.image}/>:<View style={s.image}/>}<View style={s.flex}><Text style={s.text}>{item.productTitle}</Text><Text style={s.muted}>{item.variantTitle??item.sku}</Text><Text style={s.muted}>{item.quantity} × {formatBDAG(item.unitPrice)}</Text></View><Text style={s.textStrong}>{formatBDAG(item.lineTotal)}</Text></View>)}</Section>
  <Section title="ENVÍO"><Text style={s.textStrong}>{data.shippingAddress.recipientName}</Text><Text style={s.text}>{data.shippingAddress.line1}{data.shippingAddress.line2?`, ${data.shippingAddress.line2}`:''}</Text><Text style={s.text}>{data.shippingAddress.city}, {data.shippingAddress.region} {data.shippingAddress.postalCode}</Text><Text style={s.text}>{data.shippingAddress.country}</Text>{data.shippingAddress.phone?<Text style={s.text}>{data.shippingAddress.phone}</Text>:null}{data.shipment?<View style={s.divider}><Text style={s.textStrong}>{data.shipment.carrierName}</Text><Text style={s.text}>{data.shipment.trackingNumber}</Text></View>:null}</Section>
  <Section title="PAGO / ECONOMÍA"><MoneyRow label="Artículos" value={sellerOrderItemsSubtotal(data.items)}/><MoneyRow label="Envío" value={data.shippingAmount}/><MoneyRow label="Total del pedido" value={data.order.total} strong/><Text style={s.muted}>Estado de pago: {data.payment.status}</Text>{data.allocation?<View style={s.divider}><MoneyRow label="Tarifa de plataforma" value={data.allocation.platformFeeAmount}/><MoneyRow label="Neto vendedor" value={data.allocation.sellerNetAmount}/><Text style={s.muted}>Estado del neto: {data.allocation.status==='released'?'Liberado':data.allocation.status==='held'?'Retenido':data.allocation.status==='refunded'?'Reembolsado':'Reembolso parcial'}</Text></View>:null}</Section>
  <Section title="HISTORIAL"><OrderTimeline events={data.events} allocationStatus={data.allocation?.status??null} settlement={data.settlement}/></Section>
  {data.dispute?<MarketplaceSellerDisputePanel order={data} onSubmitted={setData}/>:null}
  <MarketplaceReturnPanel role="seller" order={data} onUpdated={setData}/>
  {data.order.status==='confirmed'?<Pressable accessibilityRole="button" accessibilityLabel="Preparar pedido" accessibilityState={{disabled:busy}} disabled={busy} style={s.button} onPress={prepare}><Text style={s.buttonText}>Preparar pedido</Text></Pressable>:null}
  {data.order.status==='processing'?<Section title="AGREGAR SEGUIMIENTO"><Field label="Empresa transportista" value={carrier} set={setCarrier}/><Field label="Servicio (opcional)" value={service} set={setService}/><Field label="Número de seguimiento" value={tracking} set={setTracking}/><Field label="Enlace HTTPS (opcional)" value={url} set={setUrl}/><Field label="Nota interna (opcional)" value={note} set={setNote}/><Pressable accessibilityRole="button" accessibilityLabel="Marcar como enviado" accessibilityState={{disabled:busy}} disabled={busy} style={s.button} onPress={ship}><Text style={s.buttonText}>Marcar como enviado</Text></Pressable></Section>:null}
 </ScrollView></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.card}><Text style={s.eyebrow}>{title}</Text>{children}</View>}
function MoneyRow({label,value,strong}:{label:string;value:number;strong?:boolean}){return <View style={s.moneyRow}><Text style={strong?s.textStrong:s.muted}>{label}</Text><Text style={strong?s.textStrong:s.text}>{formatBDAG(value)}</Text></View>}
function Field({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <View><Text style={s.muted}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} style={s.input} placeholderTextColor={Colors.textSubtle}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{alignItems:'center',justifyContent:'center',gap:Spacing.md,padding:Spacing.xl},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:Spacing.xxl},orderHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},refreshNotice:{padding:Spacing.md,borderRadius:Radius.md,backgroundColor:Colors.warningDim,borderWidth:1,borderColor:Colors.warning},refreshNoticeText:{color:Colors.textSecondary,fontSize:FontSize.sm,lineHeight:19},title:{color:Colors.textPrimary,fontSize:FontSize.xl,fontWeight:FontWeight.extrabold},eyebrow:{color:Colors.textSubtle,fontSize:FontSize.xs,fontWeight:FontWeight.bold,letterSpacing:.8},text:{color:Colors.textPrimary},textStrong:{color:Colors.textPrimary,fontWeight:FontWeight.bold},muted:{color:Colors.textSecondary,fontSize:FontSize.sm},card:{backgroundColor:Colors.surfaceElevated,borderRadius:Radius.lg,padding:Spacing.md,gap:Spacing.sm,borderWidth:1,borderColor:Colors.borderSubtle},item:{minHeight:64,flexDirection:'row',alignItems:'center',gap:Spacing.sm},image:{width:52,height:52,borderRadius:Radius.sm,backgroundColor:Colors.surfaceHighlight},flex:{flex:1},divider:{borderTopWidth:1,borderTopColor:Colors.border,paddingTop:Spacing.sm,marginTop:Spacing.xs,gap:6},moneyRow:{flexDirection:'row',justifyContent:'space-between',gap:Spacing.md},input:{minHeight:46,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,color:Colors.textPrimary,paddingHorizontal:12,marginTop:4},button:{minHeight:50,paddingHorizontal:Spacing.lg,backgroundColor:Colors.primary,borderRadius:Radius.md,alignItems:'center',justifyContent:'center'},buttonText:{color:Colors.textOnBrand,fontWeight:FontWeight.bold},secondaryButton:{minHeight:46,paddingHorizontal:Spacing.lg,alignItems:'center',justifyContent:'center'},secondaryText:{color:Colors.primaryLight,fontWeight:FontWeight.bold}});
