import type {AdminIconName} from "../components/AdminIcon";

export type AdminLink={to:string;label:string;capability:string;icon:AdminIconName;primary?:boolean;end?:boolean};
export const adminLinks:AdminLink[]=[
  {to:"/overview",label:"Overview",capability:"admin.shell.access",icon:"overview",primary:true,end:true},
  {to:"/users",label:"Users",capability:"users.accounts.read",icon:"users",primary:true},
  {to:"/reports",label:"Reports",capability:"reports.cases.read",icon:"reports",primary:true},
  {to:"/content",label:"Content",capability:"content.items.read",icon:"content",primary:true},
  {to:"/stories",label:"Stories",capability:"stories.items.read",icon:"stories",primary:true},
  {to:"/chat/reports",label:"Chat",capability:"chat.abuse_reports.read",icon:"chat",primary:true},
  {to:"/live",label:"LIVE",capability:"live.sessions.read",icon:"live",primary:true},
  {to:"/battles",label:"Battles",capability:"battles.sessions.read",icon:"battles",primary:true},
  {to:"/media",label:"Media",capability:"media.assets.read",icon:"media",primary:true},
  {to:"/finance",label:"Finance",capability:"finance.ledger.read",icon:"finance",primary:true,end:true},
  {to:"/finance/accounts",label:"Finance · Accounts",capability:"finance.ledger.read",icon:"finance"},
  {to:"/finance/transactions",label:"Finance · Transactions",capability:"finance.ledger.read",icon:"finance"},
  {to:"/finance/reconciliation",label:"Finance · Reconciliation",capability:"finance.reconciliation.read",icon:"finance"},
  {to:"/finance/anomalies",label:"Finance · Anomalies",capability:"finance.anomalies.read",icon:"finance"},
  {to:"/finance/audit",label:"Finance · Audit",capability:"finance.audit.read",icon:"finance"},
  {to:"/marketplace",label:"Marketplace",capability:"marketplace.overview.read",icon:"marketplace",primary:true,end:true},
  {to:"/marketplace/orders",label:"Marketplace · Orders",capability:"marketplace.orders.read",icon:"marketplace"},
  {to:"/marketplace/disputes",label:"Marketplace · Disputes",capability:"marketplace.disputes.read",icon:"marketplace"},
  {to:"/marketplace/sellers",label:"Marketplace · Sellers",capability:"marketplace.sellers.read",icon:"marketplace"},
  {to:"/marketplace/products",label:"Marketplace · Products",capability:"marketplace.products.read",icon:"marketplace"},
  {to:"/marketplace/creator-commerce",label:"Marketplace · Creator Commerce",capability:"marketplace.creators.read",icon:"marketplace"},
  {to:"/marketplace/promotions",label:"Marketplace · Promotions",capability:"marketplace.promotions.read",icon:"marketplace"},
  {to:"/marketplace/ads",label:"Marketplace · Ads",capability:"marketplace.ads.read",icon:"marketplace"},
  {to:"/marketplace/health",label:"Marketplace · Health",capability:"marketplace.health.read",icon:"marketplace"},
  {to:"/marketplace/activity",label:"Marketplace · Activity",capability:"marketplace.audit.read",icon:"marketplace"},
  {to:"/audit",label:"Audit",capability:"admin.audit.read",icon:"audit",primary:true},
  {to:"/system",label:"System",capability:"system.health.read",icon:"system",primary:true,end:true},
  {to:"/system/jobs",label:"System · Jobs",capability:"system.jobs.read",icon:"system"},
  {to:"/system/audit",label:"System · Audit",capability:"system.audit.read",icon:"system"},
  {to:"/access",label:"Access",capability:"admin.roles.read",icon:"access",primary:true},
];
