begin;
create or replace function public.reconcile_marketplace_settlements() returns jsonb language sql stable security definer set search_path=public as $$
with e as(select id,balance from ledger_accounts where owner_id is null and account_type='marketplace_escrow' and currency='BDAG'),p as(select id from ledger_accounts where owner_id is null and account_type='platform' and currency='BDAG'),h as(select coalesce(sum(gross_amount),0) n from marketplace_payment_allocations where status='held'),x as(select coalesce(sum(balance),0) n from e),lt as(select l.*,s.order_id,s.buyer_id,s.seller_id,f.id tx,f.operation_type,f.amount tx_amount,f.currency tx_currency,f.status tx_status,f.reference_type,f.reference_id,f.from_account_id,f.to_account_id,f.initiated_by from marketplace_settlement_legs l join marketplace_order_settlements s on s.id=l.settlement_id left join financial_transactions f on f.id=l.financial_transaction_id)
select jsonb_build_object(
'released_without_settlement',(select count(*) from marketplace_payment_allocations a left join marketplace_order_settlements s on s.allocation_id=a.id where a.status='released' and s.id is null),
'settlement_without_release',(select count(*) from marketplace_order_settlements s join marketplace_payment_allocations a on a.id=s.allocation_id where a.status is distinct from 'released'),
'delivered_with_held_allocation',(select count(*) from marketplace_orders o join marketplace_payment_allocations a on a.order_id=o.id where o.status='delivered' and a.status='held'),
'released_order_not_delivered',(select count(*) from marketplace_payment_allocations a join marketplace_orders o on o.id=a.order_id where a.status='released' and o.status is distinct from 'delivered'),
'released_shipment_not_delivered',(select count(*) from marketplace_payment_allocations a left join marketplace_order_shipments sh on sh.order_id=a.order_id where a.status='released' and (sh.id is null or sh.status is distinct from 'delivered' or sh.delivered_at is null)),
'delivery_timestamp_mismatch',(select count(*) from marketplace_order_settlements s join marketplace_orders o on o.id=s.order_id left join marketplace_order_shipments sh on sh.order_id=o.id where sh.id is null or o.delivered_at is null or sh.delivered_at is null or o.delivered_at is distinct from sh.delivered_at or s.confirmed_at is distinct from o.delivered_at),
'settlement_amount_mismatch',(select count(*) from marketplace_order_settlements s join marketplace_payment_allocations a on a.id=s.allocation_id where (s.currency,s.gross_amount,s.seller_net_amount,s.platform_fee_amount) is distinct from (a.currency,a.gross_amount,a.seller_net_amount,a.platform_fee_amount)),
'settlement_leg_sum_mismatch',(select count(*) from marketplace_order_settlements s where s.gross_amount is distinct from(select coalesce(sum(amount),0) from marketplace_settlement_legs l where l.settlement_id=s.id and l.status='completed')),
'missing_seller_leg',(select count(*) from marketplace_order_settlements s where not exists(select 1 from marketplace_settlement_legs l where l.settlement_id=s.id and l.leg_type='seller_net')),'missing_platform_leg',(select count(*) from marketplace_order_settlements s where not exists(select 1 from marketplace_settlement_legs l where l.settlement_id=s.id and l.leg_type='platform_fee')),
'duplicate_seller_leg',(select count(*) from(select settlement_id from marketplace_settlement_legs where leg_type='seller_net' group by 1 having count(*)>1)q),'duplicate_platform_leg',(select count(*) from(select settlement_id from marketplace_settlement_legs where leg_type='platform_fee' group by 1 having count(*)>1)q),
'positive_leg_without_transaction',(select count(*) from lt where amount>0 and tx is null),'transaction_amount_mismatch',(select count(*) from lt where amount>0 and tx is not null and tx_amount is distinct from amount),'transaction_currency_mismatch',(select count(*) from lt where amount>0 and tx is not null and tx_currency is distinct from 'BDAG'),'transaction_status_mismatch',(select count(*) from lt where amount>0 and tx is not null and tx_status is distinct from 'completed'),
'transaction_operation_type_mismatch',(select count(*) from lt where amount>0 and tx is not null and operation_type is distinct from case leg_type when 'seller_net' then 'marketplace_seller_settlement' when 'platform_fee' then 'marketplace_platform_fee_settlement' else operation_type end),
'transaction_reference_mismatch',(select count(*) from lt where amount>0 and tx is not null and (reference_type is distinct from 'marketplace_order' or reference_id is distinct from order_id::text or initiated_by is distinct from buyer_id)),
'transaction_source_account_mismatch',(select count(*) from lt where amount>0 and tx is not null and not exists(select 1 from e where e.id is not distinct from from_account_id)),
'transaction_destination_account_mismatch',(select count(*) from lt where amount>0 and tx is not null and ((leg_type='seller_net' and not exists(select 1 from ledger_accounts a where a.id is not distinct from to_account_id and a.owner_id is not distinct from seller_id and a.account_type='user' and a.currency='BDAG'))or(leg_type='platform_fee' and not exists(select 1 from p where p.id is not distinct from to_account_id)))),
'seller_beneficiary_mismatch',(select count(*) from lt where leg_type='seller_net' and beneficiary_user_id is distinct from seller_id),'platform_beneficiary_mismatch',(select count(*) from lt where leg_type='platform_fee' and beneficiary_user_id is not null),
'settlement_order_identity_mismatch',(select count(*) from marketplace_order_settlements s join marketplace_orders o on o.id=s.order_id where(s.checkout_id,s.buyer_id,s.seller_id,s.store_id,s.currency,s.gross_amount)is distinct from(o.checkout_id,o.buyer_id,o.seller_id,o.store_id,o.currency,o.total)),
'settlement_payment_identity_mismatch',(select count(*) from marketplace_order_settlements s join marketplace_payments m on m.id=s.payment_id where(s.checkout_id,s.buyer_id,s.currency)is distinct from(m.checkout_id,m.buyer_id,m.currency)),
'settlement_allocation_identity_mismatch',(select count(*) from marketplace_order_settlements s join marketplace_payment_allocations a on a.id=s.allocation_id where(s.payment_id,s.checkout_id,s.order_id,s.seller_id,s.store_id,s.currency)is distinct from(a.payment_id,a.checkout_id,a.order_id,a.seller_id,a.store_id,a.currency)),
'escrow_expected_held_total',(select n from h),'escrow_actual_balance',(select n from x),'escrow_difference',(select x.n-h.n from x,h),'escrow_shortage',(select greatest(h.n-x.n,0)from x,h),'escrow_surplus',(select greatest(x.n-h.n,0)from x,h));$$;
revoke all on function public.reconcile_marketplace_settlements() from public,anon,authenticated;
grant execute on function public.reconcile_marketplace_settlements() to service_role;
commit;
