begin;

alter table public.marketplace_shipping_profiles add column configuration_status text not null default 'configuration_required'
  check(configuration_status in('explicit_ready','configuration_required','invalid_data'));
alter table public.marketplace_shipping_profiles add column configuration_version bigint not null default 1 check(configuration_version>0);

update public.marketplace_shipping_profiles p set configuration_status=case
 when exists(select 1 from public.marketplace_shipping_profile_regions r where r.profile_id=p.id and r.status='active')then'explicit_ready'
 else'configuration_required'end;
update public.marketplace_shipping_profiles set legacy_unrestricted=false;

alter table public.marketplace_shipping_profile_regions add constraint marketplace_shipping_country_canonical
 check(country_code=btrim(upper(country_code))and country_code~'^[A-Z]{2}$');
alter table public.marketplace_shipping_profile_regions add constraint marketplace_shipping_region_canonical
 check(region_code is null or(region_code=btrim(upper(region_code))and region_code~'^[A-Z0-9-]{1,10}$'));

alter table public.marketplace_order_shipping_snapshots add column matched_rule_id uuid references public.marketplace_shipping_profile_regions(id);
alter table public.marketplace_order_shipping_snapshots add column quote_fingerprint text;
alter table public.marketplace_order_shipping_snapshots add column quoted_at timestamptz;

create or replace function public.marketplace_country_is_valid(p_code text)returns boolean
language sql immutable set search_path=pg_catalog as $$select p_code=any(string_to_array(
'AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH,ER,ES,ET,FI,FJ,FK,FM,FO,FR,GA,GB,GD,GE,GF,GG,GH,GI,GL,GM,GN,GP,GQ,GR,GS,GT,GU,GW,GY,HK,HM,HN,HR,HT,HU,ID,IE,IL,IM,IN,IO,IQ,IR,IS,IT,JE,JM,JO,JP,KE,KG,KH,KI,KM,KN,KP,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,ME,MF,MG,MH,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NC,NE,NF,NG,NI,NL,NO,NP,NR,NU,NZ,OM,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PS,PT,PW,PY,QA,RE,RO,RS,RU,RW,SA,SB,SC,SD,SE,SG,SH,SI,SJ,SK,SL,SM,SN,SO,SR,SS,ST,SV,SX,SY,SZ,TC,TD,TF,TG,TH,TJ,TK,TL,TM,TN,TO,TR,TT,TV,TW,TZ,UA,UG,UM,US,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,ZA,ZM,ZW',','))$$;

create or replace function public.marketplace_normalize_shipping_region(p_country text,p_region text)returns text
language plpgsql immutable set search_path=pg_catalog as $$declare r text:=nullif(upper(btrim(coalesce(p_region,''))),'');begin
 if p_country='US'and(r is null or r<>all(string_to_array('AL,AK,AZ,AR,CA,CO,CT,DE,FL,GA,HI,ID,IL,IN,IA,KS,KY,LA,ME,MD,MA,MI,MN,MS,MO,MT,NE,NV,NH,NJ,NM,NY,NC,ND,OH,OK,OR,PA,RI,SC,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY,DC',',')))then raise exception using errcode='22023',message='marketplace_shipping_region_invalid';end if;
 if p_country='CA'and(r is null or r<>all(string_to_array('AB,BC,MB,NB,NL,NS,NT,NU,ON,PE,QC,SK,YT',',')))then raise exception using errcode='22023',message='marketplace_shipping_region_invalid';end if;
 if r is not null and r!~'^[A-Z0-9-]{1,10}$'then raise exception using errcode='22023',message='marketplace_shipping_region_invalid';end if;return r;end$$;

create or replace function public.quote_marketplace_shipping(p_product_id uuid,p_country_code text,p_region_code text,p_quantity integer default 1)
returns jsonb language plpgsql stable security definer set search_path=public as $$declare p public.products;sp public.marketplace_shipping_profiles;r public.marketplace_shipping_profile_regions;c text;rg text;matches integer;fingerprint text;begin
 if p_product_id is null or p_quantity is null or p_quantity<1 then raise exception using errcode='22023',message='marketplace_shipping_quote_stale';end if;
 select*into p from public.products where id=p_product_id;if not found then raise exception using errcode='P0002',message='marketplace_product_unavailable';end if;
 if p.product_type<>'physical'then return jsonb_build_object('eligible',true,'code','marketplace_shipping_not_required','shipping_profile_id',null,'matched_rule_id',null,'country_code',null,'region_code',null,'shipping_amount',0,'currency','BDAG','processing_days_min',0,'processing_days_max',0,'transit_days_min',0,'transit_days_max',0,'estimated_delivery_days_min',0,'estimated_delivery_days_max',0,'quote_timestamp',now(),'quote_fingerprint',encode(extensions.digest('digital:'||p.id::text,'sha256'),'hex'));end if;
 c:=upper(btrim(coalesce(p_country_code,'')));if not public.marketplace_country_is_valid(c)then raise exception using errcode='22023',message='marketplace_shipping_country_invalid';end if;rg:=public.marketplace_normalize_shipping_region(c,p_region_code);
 if p.shipping_profile_id is null then raise exception using errcode='22023',message='marketplace_shipping_profile_missing';end if;
 select*into sp from public.marketplace_shipping_profiles where id=p.shipping_profile_id;if sp.id is null then raise exception using errcode='22023',message='marketplace_shipping_profile_missing';end if;
 if sp.status<>'active'then raise exception using errcode='22023',message='marketplace_shipping_profile_inactive';end if;
 if sp.configuration_status='configuration_required'then raise exception using errcode='22023',message='marketplace_shipping_configuration_required';elsif sp.configuration_status<>'explicit_ready'then raise exception using errcode='22023',message='marketplace_shipping_rule_ambiguous';end if;
 select count(*)into matches from public.marketplace_shipping_profile_regions x where x.profile_id=sp.id and x.status='active'and x.country_code=c and(x.region_code=rg or x.region_code is null);
 if matches=0 then raise exception using errcode='22023',message='marketplace_shipping_destination_unsupported';end if;
 select*into r from public.marketplace_shipping_profile_regions x where x.profile_id=sp.id and x.status='active'and x.country_code=c and(x.region_code=rg or x.region_code is null)order by(x.region_code is not null)desc;
 if(select count(*)from public.marketplace_shipping_profile_regions x where x.profile_id=sp.id and x.status='active'and x.country_code=c and x.region_code is not distinct from r.region_code)>1 then raise exception using errcode='23505',message='marketplace_shipping_rule_ambiguous';end if;
 if r.shipping_price is null or r.shipping_price<0 then raise exception using errcode='23514',message='marketplace_shipping_price_invalid';end if;
 fingerprint:=encode(extensions.digest(concat_ws('|',sp.id,sp.configuration_version,r.id,r.updated_at,r.shipping_price,r.free_shipping_threshold,sp.updated_at),'sha256'),'hex');
 return jsonb_build_object('eligible',true,'code','marketplace_shipping_eligible','shipping_profile_id',sp.id,'matched_rule_id',r.id,'country_code',c,'region_code',rg,'shipping_amount',r.shipping_price,'currency','BDAG','processing_days_min',sp.processing_days_min,'processing_days_max',sp.processing_days_max,'transit_days_min',r.transit_days_min,'transit_days_max',r.transit_days_max,'estimated_delivery_days_min',sp.processing_days_min+r.transit_days_min,'estimated_delivery_days_max',sp.processing_days_max+r.transit_days_max,'quote_timestamp',now(),'quote_fingerprint',fingerprint,'quantity_policy','per_order_profile');
end$$;

create or replace function public.marketplace_freeze_order_shipping()returns trigger language plpgsql security definer set search_path=public as $$declare a public.marketplace_checkout_shipping_addresses;q jsonb;amount numeric(20,8);exists_snapshot boolean;begin
 select*into a from public.marketplace_checkout_shipping_addresses where checkout_id=new.checkout_id;
 q:=public.quote_marketplace_shipping(new.product_id,a.country,a.region,new.quantity);
 select exists(select 1 from public.marketplace_order_shipping_snapshots where order_id=new.order_id and profile_id=(q->>'shipping_profile_id')::uuid)into exists_snapshot;if exists_snapshot then return new;end if;
 amount:=(q->>'shipping_amount')::numeric;if(q->>'shipping_profile_id')is null then return new;end if;
 if exists(select 1 from public.marketplace_shipping_profile_regions r where r.id=(q->>'matched_rule_id')::uuid and r.free_shipping_threshold is not null and(select subtotal from public.marketplace_orders where id=new.order_id)>=r.free_shipping_threshold)then amount:=0;end if;
 insert into public.marketplace_order_shipping_snapshots(checkout_id,order_id,profile_id,matched_rule_id,destination_country,destination_region,shipping_price,processing_days_min,processing_days_max,transit_days_min,transit_days_max,return_policy_summary,quote_fingerprint,quoted_at)
 select new.checkout_id,new.order_id,(q->>'shipping_profile_id')::uuid,(q->>'matched_rule_id')::uuid,q->>'country_code',q->>'region_code',amount,(q->>'processing_days_min')::int,(q->>'processing_days_max')::int,(q->>'transit_days_min')::int,(q->>'transit_days_max')::int,p.return_policy_summary,q->>'quote_fingerprint',(q->>'quote_timestamp')::timestamptz from public.marketplace_shipping_profiles p where p.id=(q->>'shipping_profile_id')::uuid;
 update public.marketplace_orders set shipping_amount=shipping_amount+amount,total=subtotal+shipping_amount+amount where id=new.order_id;update public.marketplace_checkout_sessions set shipping_amount=shipping_amount+amount,total=subtotal+shipping_amount+amount where id=new.checkout_id;return new;end$$;

create or replace function public.marketplace_shipping_profile_refresh_status()returns trigger language plpgsql security definer set search_path=public as $$declare pid uuid:=coalesce(new.profile_id,old.profile_id);begin update public.marketplace_shipping_profiles p set configuration_status=case when exists(select 1 from public.marketplace_shipping_profile_regions r where r.profile_id=pid and r.status='active')then'explicit_ready'else'configuration_required'end,legacy_unrestricted=false,configuration_version=configuration_version+1,updated_at=now()where id=pid;return coalesce(new,old);end$$;
create trigger marketplace_shipping_rule_refresh_profile after insert or update or delete on public.marketplace_shipping_profile_regions for each row execute function public.marketplace_shipping_profile_refresh_status();

create or replace function public.fetch_my_marketplace_shipping_profiles(p_store_id uuid)returns jsonb language sql stable security definer set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'status',p.status,'configuration_status',p.configuration_status,'processing_days_min',p.processing_days_min,'processing_days_max',p.processing_days_max,'ships_from_country',p.ships_from_country,'return_policy_summary',p.return_policy_summary,'legacy_unrestricted',false,'products_using',(select count(*)from public.products x where x.shipping_profile_id=p.id and x.deleted_at is null),'regions',coalesce((select jsonb_agg(jsonb_build_object('country_code',r.country_code,'region_code',r.region_code,'shipping_price',r.shipping_price,'free_shipping_threshold',r.free_shipping_threshold,'transit_days_min',r.transit_days_min,'transit_days_max',r.transit_days_max,'status',r.status))from public.marketplace_shipping_profile_regions r where r.profile_id=p.id),'[]'::jsonb))order by p.created_at,p.id),'[]'::jsonb)from public.marketplace_shipping_profiles p where p.store_id=p_store_id and p.seller_id=auth.uid()$$;

create or replace function public.set_my_marketplace_product_shipping_profile(p_product_id uuid,p_profile_id uuid)returns void language plpgsql security definer set search_path=public as $$begin update public.products p set shipping_profile_id=p_profile_id,updated_at=now()where p.id=p_product_id and p.seller_id=auth.uid()and exists(select 1 from public.marketplace_shipping_profiles sp where sp.id=p_profile_id and sp.seller_id=auth.uid()and sp.store_id=p.store_id and sp.status='active'and sp.configuration_status='explicit_ready');if not found then raise exception using errcode='42501',message='marketplace_shipping_configuration_required';end if;end$$;

create or replace function public.marketplace_product_requires_shipping_configuration(p_product_id uuid)returns boolean language sql stable security definer set search_path=public as $$select p.product_type='physical'and not exists(select 1 from public.marketplace_shipping_profiles s where s.id=p.shipping_profile_id and s.status='active'and s.configuration_status='explicit_ready'and exists(select 1 from public.marketplace_shipping_profile_regions r where r.profile_id=s.id and r.status='active'))from public.products p where p.id=p_product_id$$;

create or replace function public.marketplace_product_publication_reason(p_product_id uuid,p_actor_id uuid)
returns text language plpgsql stable security definer set search_path=public as $$declare p public.products;active_count integer;inventory_count integer;default_count integer;available integer;begin
 select*into p from public.products where id=p_product_id;if p.id is null or p.seller_id<>p_actor_id then return'marketplace_permission_denied';end if;
 if not public.marketplace_seller_is_approved(p_actor_id)then return'marketplace_seller_not_approved';end if;if not exists(select 1 from public.marketplace_stores s where s.id=p.store_id and s.seller_id=p_actor_id and s.status='active')then return'marketplace_store_inactive';end if;if not exists(select 1 from public.marketplace_categories c where c.id=p.category_id and c.status='active')then return'marketplace_category_inactive';end if;if p.deleted_at is not null then return'marketplace_product_deleted';end if;if p.moderation_status<>'approved'then return'marketplace_product_not_ready_product_not_approved';end if;
 if p.product_type='physical'and public.marketplace_product_requires_shipping_configuration(p.id)then return'marketplace_product_not_ready_shipping_incomplete';end if;
 if p.product_type<>'physical'or p.currency<>'BDAG'then return'marketplace_product_not_ready_unsupported_product_type';end if;
 if cardinality(p.images)<1 or not exists(select 1 from public.media_asset_links l join public.media_assets a on a.id=l.asset_id where l.entity_type='shop_product'and l.entity_id=p.id and a.owner_id=p_actor_id and a.status='ready'and a.visibility='public'and a.media_kind='image'and a.purpose='product_image')then return'marketplace_product_media_required';end if;
 select count(*)filter(where v.status='active'and v.archived_at is null),count(i.variant_id)filter(where v.status='active'and v.archived_at is null),count(*)filter(where v.status='active'and v.archived_at is null and v.is_default),coalesce(sum(greatest(i.on_hand-i.reserved,0))filter(where v.status='active'and v.archived_at is null),0)into active_count,inventory_count,default_count,available from public.marketplace_product_variants v left join public.marketplace_inventory_levels i on i.variant_id=v.id where v.product_id=p.id;
 if active_count=0 then return'marketplace_product_not_ready_no_active_variant';end if;if default_count<>1 or inventory_count<active_count then return'marketplace_product_not_ready_inventory_not_configured';end if;if available<=0 then return'marketplace_product_not_ready_out_of_stock';end if;return null;end$$;

create or replace function public.marketplace_evaluate_live_product_readiness(p_product_id uuid,p_host_id uuid)
returns table(availability text,reason_code text,active_variant_count integer,available_quantity integer,seller_status text,store_status text,moderation_status text)
language sql stable security definer set search_path=public as $$with e as(select p.id,p.status product_status,p.moderation_status,p.deleted_at,p.product_type,p.currency,s.status store_status,ms.status seller_status,public.marketplace_product_requires_shipping_configuration(p.id)shipping_missing,count(v.id)filter(where v.status='active'and v.archived_at is null)::int active_variants,count(i.variant_id)filter(where v.status='active'and v.archived_at is null)::int inventory_rows,count(v.id)filter(where v.status='active'and v.archived_at is null and v.is_default)::int default_variants,coalesce(sum(greatest(i.on_hand-i.reserved,0))filter(where v.status='active'and v.archived_at is null),0)::int available from public.products p left join public.marketplace_stores s on s.id=p.store_id and s.seller_id=p.seller_id left join public.marketplace_sellers ms on ms.user_id=p.seller_id left join public.marketplace_product_variants v on v.product_id=p.id left join public.marketplace_inventory_levels i on i.variant_id=v.id where p.id=p_product_id group by p.id,s.status,ms.status),c as(select*,case when seller_status is distinct from'approved'then'seller_not_approved'when store_status is distinct from'active'then'store_not_active'when deleted_at is not null then'product_deleted'when product_status is distinct from'active'then'product_not_active'when moderation_status is distinct from'approved'then'product_not_approved'when product_type is distinct from'physical'then'unsupported_product_type'when currency is distinct from'BDAG'then'unsupported_currency'when shipping_missing then'shipping_incomplete'when active_variants=0 then'no_active_variant'when default_variants<>1 or inventory_rows<active_variants then'inventory_not_configured'when available<=0 then'out_of_stock'else'ready'end reason from e)select case when reason='ready'then'available'when reason='out_of_stock'then'out_of_stock'else'product_unavailable'end,reason,active_variants,available,seller_status,store_status,moderation_status from c$$;

revoke all on function public.marketplace_country_is_valid(text),public.marketplace_normalize_shipping_region(text,text),public.marketplace_shipping_profile_refresh_status(),public.marketplace_product_requires_shipping_configuration(uuid),public.marketplace_product_publication_reason(uuid,uuid),public.marketplace_evaluate_live_product_readiness(uuid,uuid)from public,anon,authenticated;
grant execute on function public.marketplace_evaluate_live_product_readiness(uuid,uuid)to service_role;
revoke all on function public.quote_marketplace_shipping(uuid,text,text,integer)from public;
grant execute on function public.quote_marketplace_shipping(uuid,text,text,integer)to anon,authenticated,service_role;

comment on function public.quote_marketplace_shipping(uuid,text,text,integer)is 'Authoritative explicit-destination quote. Shipping is charged once per order/profile, not per quantity.';
comment on column public.marketplace_shipping_profiles.configuration_status is 'Legacy profiles without explicit active rules remain manageable but cannot authorize checkout.';

commit;
