import {supabase} from "./supabase";

export type JsonRecord=Record<string,unknown>;
const record=(value:unknown,name:string):JsonRecord=>{if(value===null||typeof value!=="object"||Array.isArray(value))throw new Error(`${name}: respuesta inválida`);return value as JsonRecord};
async function rpc(name:string,args:JsonRecord={}){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message||`No se pudo ejecutar ${name}`);return data as unknown}

export const searchAdminContentSafetyAlerts=async(filters:JsonRecord={})=>record(await rpc("search_admin_content_safety_alerts",filters),"content_safety_alerts");
export const getAdminContentSafetyAlert=async(id:string)=>record(await rpc("get_admin_content_safety_alert",{p_alert_id:id}),"content_safety_alert");
export const searchAdminContentSafetyRules=async()=>record(await rpc("search_admin_content_safety_rules"),"content_safety_rules");
export type ContentSafetyRuleDraftInput={code:string;label:string;category:string;detectorType:string;pattern:string;severity:string;scopes:string[];locale:string;policySource:string;policyReference:string;policyVersion:string|null;rationale:string|null;idempotencyKey:string};
export type ContentSafetyRuleUpdateInput={id:string;label:string;category:string;severity:string;scopes:string[];policySource:string;policyReference:string;policyVersion:string|null;rationale:string|null;idempotencyKey:string};
export const createAdminContentSafetyRule=async(input:ContentSafetyRuleDraftInput)=>record(await rpc("admin_create_content_safety_rule",{p_code:input.code,p_label:input.label,p_category:input.category,p_detector_type:input.detectorType,p_pattern:input.pattern,p_severity:input.severity,p_scopes:input.scopes,p_locale:input.locale,p_policy_source:input.policySource,p_policy_reference:input.policyReference,p_policy_version:input.policyVersion,p_rationale:input.rationale,p_idempotency_key:input.idempotencyKey}),"content_safety_rule_receipt");
export const updateAdminContentSafetyRule=async(input:ContentSafetyRuleUpdateInput)=>record(await rpc("admin_update_content_safety_rule",{p_rule_id:input.id,p_label:input.label,p_category:input.category,p_severity:input.severity,p_scopes:input.scopes,p_policy_source:input.policySource,p_policy_reference:input.policyReference,p_policy_version:input.policyVersion,p_rationale:input.rationale,p_idempotency_key:input.idempotencyKey}),"content_safety_rule_receipt");
export const previewAdminContentSafetyRuleDraft=async(input:{detectorType:string;pattern:string;scopes:string[];locale:string;limit?:number})=>record(await rpc("preview_admin_content_safety_rule_draft",{p_detector_type:input.detectorType,p_pattern:input.pattern,p_scopes:input.scopes,p_locale:input.locale,p_limit:input.limit??20}),"content_safety_rule_draft_preview");
export const previewAdminContentSafetyRule=async(input:{id:string;limit?:number})=>record(await rpc("preview_admin_content_safety_rule",{p_rule_id:input.id,p_limit:input.limit??20}),"content_safety_rule_preview");
export const approveAdminContentSafetyRule=async(input:{id:string;definitionFingerprint:string;idempotencyKey:string})=>record(await rpc("admin_approve_content_safety_rule",{p_rule_id:input.id,p_definition_fingerprint:input.definitionFingerprint,p_idempotency_key:input.idempotencyKey}),"content_safety_rule_receipt");
export const setAdminContentSafetyRuleEnabled=async(input:{id:string;enabled:boolean;definitionFingerprint?:string|null;idempotencyKey:string})=>record(await rpc("admin_set_content_safety_rule_enabled",{p_rule_id:input.id,p_enabled:input.enabled,p_definition_fingerprint:input.definitionFingerprint??null,p_idempotency_key:input.idempotencyKey}),"content_safety_rule_receipt");
export const retireAdminContentSafetyRule=async(input:{id:string;idempotencyKey:string})=>record(await rpc("admin_retire_content_safety_rule",{p_rule_id:input.id,p_idempotency_key:input.idempotencyKey}),"content_safety_rule_receipt");
export const reviewAdminContentSafetyAlert=async(input:{id:string;action:"take_review"|"dismiss"|"resolve";resolution:string|null;note:string|null;idempotencyKey:string})=>record(await rpc("admin_review_content_safety_alert",{p_alert_id:input.id,p_action:input.action,p_resolution:input.resolution,p_note:input.note,p_idempotency_key:input.idempotencyKey}),"content_safety_alert_receipt");
export const retryAdminContentSafetyScan=async(input:{id:string;idempotencyKey:string})=>record(await rpc("admin_retry_content_safety_scan",{p_scan_id:input.id,p_idempotency_key:input.idempotencyKey}),"content_safety_scan_receipt");
export const searchAdminContentSafetyAudio=async()=>record(await rpc("search_admin_content_safety_audio"),"content_safety_audio");
export const getAdminContentSafetyAudioDetail=async(id:string)=>record(await rpc("get_admin_content_safety_audio_detail",{p_scan_id:id}),"content_safety_audio_detail");
export const retryAdminContentSafetyAudio=async(input:{id:string;idempotencyKey:string})=>record(await rpc("admin_retry_content_safety_audio",{p_scan_id:input.id,p_idempotency_key:input.idempotencyKey}),"content_safety_audio_receipt");
