import React,{useCallback,useRef,useState}from'react';
import{ActivityIndicator,FlatList,Pressable,RefreshControl,StyleSheet,Text,View}from'react-native';
import{MaterialIcons}from'@expo/vector-icons';
import{useFocusEffect,useRouter}from'expo-router';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme';
import{SellerScreenHeader}from'@/components/marketplace/SellerScreenHeader';
import{fetchSellerDisputes,type MarketplaceSellerDisputePage,type MarketplaceSellerDisputeSummary}from'@/services/marketplaceFulfillmentService';
import{marketplaceDisputeReasonLabel}from'@/services/marketplaceOrderPresentation';

const PAGE=20;
/* eslint-disable react-hooks/exhaustive-deps -- focus refresh intentionally resets the canonical inbox */
export default function SellerDisputes(){
 const router=useRouter(),insets=useSafeAreaInsets(),lock=useRef(false),generation=useRef(0);
 const[items,setItems]=useState<MarketplaceSellerDisputeSummary[]>([]),[summary,setSummary]=useState({active:0,open:0,review:0}),[next,setNext]=useState<MarketplaceSellerDisputePage['nextCursor']>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[more,setMore]=useState(false),[error,setError]=useState(false);
 const load=useCallback(async(mode:'replace'|'append'='replace')=>{if(mode==='append'&&lock.current)return;if(mode==='append')lock.current=true;const token=++generation.current;if(mode==='append')setMore(true);else if(items.length)setRefreshing(true);else setLoading(true);try{const page=await fetchSellerDisputes({limit:PAGE,cursor:mode==='append'?(next??undefined):undefined});if(token!==generation.current)return;setItems(current=>mode==='append'?[...new Map([...current,...page.disputes].map(item=>[item.id,item])).values()]:page.disputes);setSummary({active:page.activeCount,open:page.openCount,review:page.underReviewCount});setNext(page.nextCursor);setError(false)}catch{if(token===generation.current)setError(true)}finally{if(mode==='append')lock.current=false;setLoading(false);setRefreshing(false);setMore(false)}},[items.length,next]);
 useFocusEffect(useCallback(()=>{generation.current++;setItems([]);setNext(null);void load()},[]));
 return <View style={[s.root,{paddingTop:insets.top}]}><SellerScreenHeader title="Disputas" fallbackRoute="/seller"/>{loading?<ActivityIndicator style={s.center} color={Colors.primary}/>:<FlatList data={items} keyExtractor={item=>item.id} onEndReached={()=>{if(next&&!more)void load('append')}} ListHeaderComponent={<View style={s.summary}><Text style={s.summaryNumber}>{summary.active}</Text><View><Text style={s.title}>{summary.active===1?'Disputa activa':'Disputas activas'}</Text><Text style={s.muted}>{summary.open} abiertas · {summary.review} en revisión</Text></View></View>} ListFooterComponent={more?<ActivityIndicator color={Colors.primary}/>:null} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load()} tintColor={Colors.primary}/>} contentContainerStyle={s.list} ListEmptyComponent={<View style={s.center}><MaterialIcons name={error?'error-outline':'verified'} size={38} color={error?Colors.error:Colors.accent}/><Text style={s.title}>{error?'No pudimos cargar las disputas':'Sin disputas abiertas'}</Text>{error?<Pressable accessibilityRole="button" style={s.retry} onPress={()=>void load()}><Text style={s.retryText}>Reintentar</Text></Pressable>:null}</View>} renderItem={({item})=><DisputeCard item={item} open={()=>router.push(`/seller/orders/${item.orderId}` as never)}/>}/>}</View>
}
function DisputeCard({item,open}:{item:MarketplaceSellerDisputeSummary;open:()=>void}){const status=item.status==='open'?'Abierta':'En revisión';return <Pressable accessibilityRole="button" accessibilityLabel={`Abrir disputa del pedido ${item.orderNumber}. ${status}`} style={s.card} onPress={open}><View style={s.cardHeader}><View style={s.alertDot}/><Text style={s.order} numberOfLines={1}>{item.orderNumber}</Text><Text style={s.status}>{status}</Text></View><Text style={s.reason}>{marketplaceDisputeReasonLabel(item.reasonCode)}</Text><Text style={item.sellerResponseSubmitted?s.responded:s.pending}>{item.sellerResponseSubmitted?'Respuesta enviada':'Respuesta pendiente'}</Text><Text style={s.muted}>{item.affectedItemCount} {item.affectedItemCount===1?'producto afectado':'productos afectados'} · {item.buyerEvidenceCount} {item.buyerEvidenceCount===1?'foto':'fotos'} · {new Date(item.createdAt).toLocaleDateString()}</Text><MaterialIcons name="chevron-right" size={22} color={Colors.textSecondary} style={s.chevron}/></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},list:{padding:Spacing.md,gap:Spacing.md,flexGrow:1},center:{flex:1,minHeight:260,alignItems:'center',justifyContent:'center',gap:Spacing.md},summary:{flexDirection:'row',alignItems:'center',gap:Spacing.md,padding:Spacing.md,borderRadius:Radius.lg,backgroundColor:Colors.warningDim,borderWidth:1,borderColor:'#FFB80044'},summaryNumber:{color:Colors.warning,fontSize:FontSize.xxl,fontWeight:FontWeight.extrabold},title:{color:Colors.textPrimary,fontSize:FontSize.lg,fontWeight:FontWeight.bold},muted:{color:Colors.textSecondary,fontSize:FontSize.xs},card:{position:'relative',padding:Spacing.md,gap:7,borderRadius:Radius.lg,backgroundColor:Colors.surfaceElevated,borderWidth:1,borderColor:Colors.borderSubtle},cardHeader:{flexDirection:'row',alignItems:'center',gap:7,paddingRight:28},alertDot:{width:8,height:8,borderRadius:4,backgroundColor:Colors.warning},order:{flex:1,color:Colors.textPrimary,fontWeight:FontWeight.extrabold},status:{color:Colors.warning,fontSize:FontSize.xs,fontWeight:FontWeight.bold},reason:{color:Colors.textPrimary,fontWeight:FontWeight.semibold},pending:{color:Colors.warning,fontSize:FontSize.sm,fontWeight:FontWeight.bold},responded:{color:Colors.accent,fontSize:FontSize.sm,fontWeight:FontWeight.bold},chevron:{position:'absolute',right:12,top:42},retry:{minHeight:44,paddingHorizontal:Spacing.md,justifyContent:'center',backgroundColor:Colors.primary,borderRadius:Radius.md},retryText:{color:Colors.textOnBrand,fontWeight:FontWeight.bold}});
